### ISSUE TITLE
SpongeForge

### ISSUE THREAD

**Issue by knoxhack** [MinecraftModDevelopment/MMD-Dev-Server#10]
**Mod Name**:
SpongeForge

**Mod Version**:
5.0.0-BETA-1689

**Link To Download**:
http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/index_1.10.2.html

**Dependant Mods**:
Forge-12.18.1.2075

**Recommended Sponge Plugins**:
https://forums.spongepowered.org/t/serverlistplus-3-4-6-api-4-x-5-x/7520

https://forums.spongepowered.org/t/project-portals-v0-11-3/10438

https://forums.spongepowered.org/t/spongecast-now-with-prefixes-v1-1-0/14311

https://forums.spongepowered.org/t/api-4-2-x-5-x-foxguard-the-flexible-world-protection-solution/9952

https://forums.spongepowered.org/t/0-8-0-nucleus-the-ultimate-essentials-plugin-mc-1-8-9-and-1-10-2/11792

https://forums.spongepowered.org/t/permissionsex-v2-0-api-5/6198

https://forums.spongepowered.org/t/griefprevention-official-thread-1-8-9-1-10-2/1123

**If you're not the author of the mod you are requesting, why should this mod be added**:
Why?

It will help our mods have fully compatibility with the Sponge platform by finding bugs on the server.
I know most modded server communities will be using SpongeForge once FTB Infinity 1.10.2, Resonant Rise 4 and other maintream modpacks gets released.
I know for sure the Resonant Rise 4 beta test server is already using SpongeForge so it essential that our mods support it.

Pros: Better Players management (Ranks, Perms, Harambe etc.)
Cos: incompatibility with some mods.

**Comment by p455w0rd** [comment]
Hey, there's another super duper cool dev test server where @gabizou has SpongeForge installed, but never gets on the server. Here's the discord: https://discord.gg/wQFN2ct
