### ISSUE TITLE
Bug Report: EvilCraft

### ISSUE THREAD

**Issue by EmoKiba** [MinecraftModDevelopment/MMD-Dev-Server#102]
The Blood Chest Charges RF on Enderio Items instead of fixing their base durability

**Comment by EmoKiba** [comment]
actually it does both it fixes and charges lol

**Comment by rubensworks** [comment]
Which items exactly are having issues?

**Comment by EmoKiba** [comment]
the enderio darkiron shears with empower 2 on them 
sorry for late response

**Comment by EmoKiba** [comment]
Also unsure if bug or feature but it also has a chance when repairing an item to give it a random enchantment like i was repair my diamond crack hammer and it gave it crushing enchant

**Comment by p455w0rd** [comment]
Paging @rubensworks

**Comment by rubensworks** [comment]
I'll look into it.

@EmoKiba Are you sure it's not giving the breaking enchant? Because that would be the intented behaviour.

**Comment by p455w0rd** [comment]
Looks like @EmoKiba isn't responding. I will close this for now, If a duplicate is created, I will forward to the appropriate repo.
