### ISSUE TITLE
Few mods to add

### ISSUE THREAD

**Issue by battery3996** [MinecraftModDevelopment/MMD-Dev-Server#11]
Mod Name | Version 
------------- | ----------
[Ender IO](https://minecraft.curseforge.com/projects/ender-io) | [1.10.2-0.4.1.1.51-beta] 
[Immersive Engineering](https://minecraft.curseforge.com/projects/immersive-engineering?gameCategorySlug=mc-mods&projectID=231951) | [0.10-38]
[Endercore](https://minecraft.curseforge.com/projects/endercore?gameCategorySlug=mc-mods&projectID=231868) [Dependent mod for Ender IO] | [1.10.2-3.0.1.96_beta]

**If you're not the author of the mod you are requesting, why should this mod be added?** More energy options, processing options, also to fix any bugs come across these as these are fairly popular mods that people use

**Comment by knoxhack** [comment]
We decided to go for Mekanism instead of those 2 mods, Mekanism support all types of energy, has pipes, Power generators etc..

**Comment by p455w0rd** [comment]
I'm definitely in favor of EnderIO, if anyone ever wants my input on the matter. xD

**Comment by TheCodedOne** [comment]
Personally my opinion on those two are no, since my mod will be doing stuff similar to those mods, i feel it would be hard for my mod to get a good test since alot of testers would use the well known route.

**Comment by p455w0rd** [comment]
Ok, discussion over. The staff have spoken. :P
