### ISSUE TITLE
Whitelist Request: MrSwiggity

### ISSUE THREAD

**Issue by ValkyrieofNight** [MinecraftModDevelopment/MMD-Dev-Server#121]
Minecraft IGN: MrSwiggity
Discord Username: MrSwiggity

MrSwiggity is a someone I play minecraft with. He is also going to be working on a new mod with me soon. I hope you don't mind me(ValkyrieofNight) requesting on his behalf.

**Comment by p455w0rd** [comment]
The only issue I have with someone requesting on another's behalf is that we require testers to make big reports..if they are unable/ not willing to submit a whitelist request issue, it's hard to believe that they will be submitting bug reports

**Comment by ValkyrieofNight** [comment]
ok i will get him to submit a whitelist request issue

**Comment by MrTaco9001** [comment]
Hello I'm the person ValkyrieofNight submitted the request for. I am willing to submit bug reports when I come across bugs.
