### ISSUE TITLE
Mod request: Forestry

### ISSUE THREAD

**Issue by ZeroNoRyouki** [MinecraftModDevelopment/MMD-Dev-Server#125]
Mod Name: Forestry

Mod Version: 1.10.2-5.2.9.242

Link To Download: https://minecraft.curseforge.com/projects/forestry/files

Dependant Mods: none

If you're not the author of the mod you are requesting, why should this mod be added:

- bees are fun!
- backpacks!
- i'll be adding bees to Extreme Reactors and Coded want it on top of the TODO list!

**Comment by EmoKiba** [comment]
If we Have this Please for the love of god add Gendustry the Grind bees is terrible

**Comment by p455w0rd** [comment]
If this gets approved, be sure to approve Gendustry as well..I hear it sucks doing bees without it

**Comment by RacerDelux** [comment]
Agreed
