### ISSUE TITLE
Mod Request: Blood Magic

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#127]
Mod Name: Blood Magic

Mod Version: BloodMagic-1.9.4-2.0.4-58 

Link To Download: https://mods.curse.com/mc-mods/minecraft/224791-blood-magic

Dependant Mods: none

If you're not the author of the mod you are requesting, why should this mod be added:

This is a biggish magical mod which takes a lot of doing and other than Evilcraft, we dont have a lot of magical mods

**Comment by p455w0rd** [comment]
Get way join and I'll consider a yes

**Comment by p455w0rd** [comment]
To* - on mobile; can't edit

**Comment by Morpheus1101** [comment]
Im only a player//tester not anyway offical rep to be able to talk to him about such a thing, thats what you guys are for :D

**Comment by RacerDelux** [comment]
@p455w0rd Is this so he can be aware of game breaking bugs faster?
