### ISSUE TITLE
Mod Request: Extra Utilities

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#129]
Mod Name:  Extra Utilities

Mod Version: Extra Utilities 2 1.10.2 Alpha 1.0.1 

Link To Download: https://minecraft.curseforge.com/projects/extra-utilities/files

Dependant Mods: none

It has Watering Can, Chunk Loader and other great stuff that would be of a great asset to the server players

**Comment by p455w0rd** [comment]
👎
