### ISSUE TITLE
Mod Request: Roots

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [MinecraftModDevelopment/MMD-Dev-Server#131]
Mod Name: Roots

Mod Version: roots-1.10.2-0.202.0.jar

Link To Download: https://minecraft.curseforge.com/projects/roots/files/2328890

Dependant Mods: none

It is a mod by one of our mod developers in MMD, I asked him if he wanted to add it himself and he said I can do it, so i am. Its a great mod and I think testing it for him would be nice. I also love the mod so.. yea! and we are in need of more magic mods.

**Comment by EPIICTHUNDERCAT** [comment]
Elucent and more :)

**Comment by RacerDelux** [comment]
i would love to see it
