### ISSUE TITLE
Bug Report: P455w0rd Things & Armor Plus

### ISSUE THREAD

**Issue by EmoKiba** [MinecraftModDevelopment/MMD-Dev-Server#134]
So.. we thought it was a bug with Armor Plus but It is actually with your Carbon Armor it wont allow flight with other armors at least not the EnderDragon Armor but I will call it a Dual Bug somewhere your codes class so im calling both mods

**Comment by p455w0rd** [comment]
It's my code..will get a fix up asap

**Comment by EmoKiba** [comment]
awesome if anyone can get it fixed its you buddy
