### ISSUE TITLE
Bug: Wither Skel not dropping Wither Skeleton Chunk

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#140]
Wither Skull's have a 5.5% chance to drop with Looting 3 and over the last 8hrs i have gained 20 Skulls yet the Wither Skeleton Chunk has a 10% chance to drop and ive not gotten any.  Im not sure if this is due to something on the server or with Mystical Agriculture mod itself.

**Comment by EmoKiba** [comment]
this isnt a bug you should make a soulim Dagger and it gives chunks i have like 4 already
