### ISSUE TITLE
Mod Request: Chicken Chunks

### ISSUE THREAD

**Issue by MrTaco9001** [MinecraftModDevelopment/MMD-Dev-Server#141]
Mod Name: Chicken Chunks

Mod Version: ChickenChunks-1.10.2-2.1.3.36

Link To Download: [Link](http://chickenbones.net/filedownloader/download.html?fn=Q2hpY2tlbkNodW5rcy8xLjEwLjItMi4xLjMuMzYvQ2hpY2tlbkNodW5rcy0xLjEwLjItMi4xLjMuMzYtdW5pdmVyc2FsLmphcg==)

Dependant Mods: [CodeChickenCore-1.10.2-2.1.8.79](http://chickenbones.net/filedownloader/download.html?fn=Q29kZUNoaWNrZW5Db3JlLzEuMTAuMi0yLjEuOC43OS9Db2RlQ2hpY2tlbkNvcmUtMS4xMC4yLTIuMS44Ljc5LXVuaXZlcnNhbC5qYXI=)

If you're not the author of the mod you are requesting, why should this mod be added:
Chunk Loading

**Comment by knoxhack** [comment]
Pls

**Comment by Morpheus1101** [comment]
i thought dark was making one...but this would be great to have and very needed

**Comment by knoxhack** [comment]
Idk, but we need a chunk loader tho

**Comment by Morpheus1101** [comment]
Agreed, it is something we really really do require

**Comment by ValkyrieofNight** [comment]
I've made one. There is one in latest version of environmental tech.

**Comment by knoxhack** [comment]
Nice!

**Comment by p455w0rd** [comment]
Why do we need a chunk loader? TPS is bad enough without one...
