### ISSUE TITLE
Whitelist Request: Sethg_

### ISSUE THREAD

**Issue by Sethgoldfox** [MinecraftModDevelopment/MMD-Dev-Server#142]
Minecraft IGN: Sethg_

Discord Username: Sethg

What you do (i.e streamer, mod developer, ect.): I'm a Pack Maker! I work on too many to list here, but the ones with my name on it are mostly on my Curse page [HERE](https://minecraft.curseforge.com/members/Sethg/projects). My Streamer friend Morpheus1101 referred me to the Minecraft Server, but i've been in the Discord group for a long while.

**Comment by Morpheus1101** [comment]
i've played heaps with seth and he's been one of the guys i've gone to for help with modpackin and ideas when i get stuck, he would be a great person to have on the server :dancers:

**Comment by darkhax** [comment]
I can also agree that he would make another great addition to the server members.
