### ISSUE TITLE
Mod request: Light Level Overlay Reloaded

### ISSUE THREAD

**Issue by EmoKiba** [MinecraftModDevelopment/MMD-Dev-Server#146]
Mod Name: Light  Level Overlay Reloaded

Mod Version:LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar

Link To Download: https://minecraft.curseforge.com/projects/light-level-overlay-reloaded/files/2312553

Dependant Mods: none

If you're not the author of the mod you are requesting, why should this mod be added:

Due to FTB Util Being Removed for being uber Buggy we lost the ability to check light levels similar to F7 in NEI this mod allows you to see the light levels around your area

**Comment by p455w0rd** [comment]
This is a client-side mod..no need to request..just throw it in your instance
