### ISSUE TITLE
Whitelist request: desht

### ISSUE THREAD

**Issue by desht** [MinecraftModDevelopment/MMD-Dev-Server#148]
**Minecraft IGN**: desht

**Discord Username**: desht

**What you do** (*i.e streamer, mod developer, ect.*): Mod developer (Modular Routers)

**Comment by Morpheus1101** [comment]
https://mods.curse.com/mc-mods/minecraft/250294-modular-routers - Looks Interesting a mod

**Comment by p455w0rd** [comment]
@desht could you please join our Discord server

**Comment by desht** [comment]
I've already signed up for Discord and logged in briefly this morning to
check it was working. Can't get on right now (work) but should be fine to
join later.

**Comment by p455w0rd** [comment]
Yeah, Modular Routers was already supposed to be on the server :P
