### ISSUE TITLE
Enhancement: Restart Mining Dimension & Not Enough Wands Fix

### ISSUE THREAD

**Issue by EmoKiba** [MinecraftModDevelopment/MMD-Dev-Server#149]
I am simlply requesting on next update we do a fresh load of the aromas core mining dimension for new ores and such to be loaded for mine and the Not Enough Wands are now costing power and exp the solve is to remove the exp or the RF cost

**Comment by p455w0rd** [comment]
The mining dim is reset frequently, no need to request here :) I'll remove the xp requirement from NAW..it's just odd that there is no way to tell how charged the wand is..this is why I don't like the RF option

**Comment by EmoKiba** [comment]
well you can just give it durability we have tool repair options so we could go that route

**Comment by EPIICTHUNDERCAT** [comment]
it should display the amount of charge it had, i have seen it before... i dont know if mcjty's son removed that. might be worth asking

**Comment by p455w0rd** [comment]
@McJty - thoughts?

**Comment by McJty** [comment]
Client side config matches?

**Comment by p455w0rd** [comment]
ty :)
