### ISSUE TITLE
[BUG] p455w0rd's Things

### ISSUE THREAD

**Issue by p455w0rd** [MinecraftModDevelopment/MMD-Dev-Server#154]
Ender Dragon drops /dank/null panels with incorrect meta data

**Comment by RacerDelux** [comment]
Can this be closed?

**Comment by p455w0rd** [comment]
after it has been added to the pack

**Comment by RacerDelux** [comment]
This is a mod update yes?

**Comment by p455w0rd** [comment]
Please don't close, I'll take care of it after the next update has been added to the pack

**Comment by p455w0rd** [comment]
fixed in #194
