### ISSUE TITLE
Mod Request: Drawers & Bits

### ISSUE THREAD

**Issue by Zaweri** [MinecraftModDevelopment/MMD-Dev-Server#155]
Mod Name: 
-
Drawers & Bits

Mod Version: 
-
DrawersBits-1.10.2-0.31.jar

Link To Download: 
-
https://minecraft.curseforge.com/projects/drawers-bits

It's an addon to Chisels & Bits and Storage Drawers. I don't really have any other reason for adding this other than being able to store individual bits out of bags, as it gets tedious when you have 9 types of bits in one bag.

**Comment by RacerDelux** [comment]
Agreed, I forget though, I thought there used to be some awk compat issues with it.
