### ISSUE TITLE
BUG: Server Crash using EnderIO Pressurised Fluid Conduits with Electrical Advantage Pump & Dimensional Transciever

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#156]
https://github.com/SleepyTrousers/EnderIO/issues/3694

**Comment by Morpheus1101** [comment]
EIO sais this is apparently a bug on EA's side

**Comment by p455w0rd** [comment]
has already been forward to MinecraftModDevelopment/ElectricalAdvantage#1
