### ISSUE TITLE
Mod request: Kiba's Request List

### ISSUE THREAD

**Issue by EmoKiba** [MinecraftModDevelopment/MMD-Dev-Server#16]
Name: Enviromental Tech
Version: 0.10.3a
Download: https://mods.curse.com/mc-mods/minecraft/245453-environmental-tech/2326486

Name: Chance Cubes
Version: 2.2.1.120
Download: https://mods.curse.com/mc-mods/minecraft/233113-chance-cubes/2322515
(For Streamer we Do Donation Chance Cubes A lot when Streaming just disable terrain gen for them in config and then give us a Chance Cube Spawner and we Set)

Name: ArmorPlus
Version: 6.0.4.1
Download: https://mods.curse.com/mc-mods/minecraft/237366-armorplus/2326784

Name: EZ Storage 2
Version: 2.2.2
Download: https://minecraft.curseforge.com/projects/ezstorage-2/files/2320453

(notes - These are just mods I have started tinkering with in 1.10.2 and newer types of mods)

**Comment by knoxhack** [comment]
Name: Enviromental Tech: Not sure why is needed unless the mod author wants us to find bugs here maybe.
Name: Chance Cubes: Why Not,
Name: ArmorPlus: Not sure why is needed unless the mod author wants us to find bugs here maybe.
Name: EZ Storage 2: Why Not

**Comment by EmoKiba** [comment]
I'm going t
