### ISSUE TITLE
[Mod Removal] Chisel

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#161]
Upon the map reset, im asking to have the mod removed unless a fix has been found for chisel being it causes the rftools dim worlds to crash upon entering.  Since chisel is more an Aesthetic mod its not overly in need of testing where rftools dim worlds are.

**Comment by EmoKiba** [comment]
battery and I have went through like 3 rf dimensions it didn't cause us a crash

**Comment by Morpheus1101** [comment]
Well if they're stable and able to be used, then hell, time to dig in deep into the dimensions, but im hesitant, but hey, whats the worst that can happen *g*

**Comment by knoxhack** [comment]
We are using a new version of chisel, thats why I asked you guys to try to make RFTools dims

**Comment by battery3996** [comment]
If need be ill remake a new dim and if it crashes then yes remove but if it doesnt i say keep the mod.

**Comment by RacerDelux** [comment]
if you have a crash report, make an issue on chisel, maybe they can even fix it.

**Comment by Morpheus1101** [comment]
Im trying to make a custom liquid uranium world atm .. not that i know wtf im doing
