### ISSUE TITLE
Mod Request: OpenComputers

### ISSUE THREAD

**Issue by EmoKiba** [MinecraftModDevelopment/MMD-Dev-Server#164]
Mod Name: OpenComputers

Mod Version: OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar

Link To Download: https://minecraft.curseforge.com/projects/opencomputers/files/2320101

If you're not the author of the mod you are requesting, why should this mod be added:
Computers would be easier to maintain reactor control and unsure if Extreme Reactors
has support for this

**Comment by RacerDelux** [comment]
Why opencomputers over computercraft? why not both?

**Comment by p455w0rd** [comment]
CC is TERRIBLY buggy in 1.10.2 still afaik

**Comment by TheCodedOne** [comment]
^ computercraft does not get regular dev builds, it has i think 1 since 1.9.4, so any bugs wont be fixed any time soon, and the turtles crash like hell so yeah.. computercraft not a good option, i was actually gonna request OC. i just forgot :P
