### ISSUE TITLE
Bug: Draconic Evolution - Infusion crash & kick while joining a server

### ISSUE THREAD

**Issue by sokratis12GR** [MinecraftModDevelopment/MMD-Dev-Server#166]
crashed just by looking at the infusion while it finished: https://beta.paste.ee/p/SA7HQ

and I'm getting kicked after adding RF Capacity upgrade to a Draconic Helmet, didn't pick up the helmet from the infusion core
![image](https://cloud.githubusercontent.com/assets/12274096/18579205/e71812ec-7bfc-11e6-8e9a-6c5bd1087363.png)

**Comment by p455w0rd** [comment]
@brandon3055

**Comment by Morpheus1101** [comment]
I believe this has been fixed in the newest version ?

**Comment by Morpheus1101** [comment]
This issue has been fixed, as i have infused all my draconic stuff with all upgrades including RF Capacity and have had no crash issues
