### ISSUE TITLE
Mod Request: Just Enough Resources

### ISSUE THREAD

**Issue by droidicus** [MinecraftModDevelopment/MMD-Dev-Server#173]
**Mod Name**: Just Enough Resources

**Mod Version**: 0.5.1.54

**Link To Download**: https://minecraft.curseforge.com/projects/just-enough-resources-jer

**Dependant Mods**: JEI >= 3.9.3.252 (already in pack)

**If you're not the author of the mod you are requesting, why should this mod be added**: This mod is handy to keep track of ores, drops, and villager trades, and is also handy for debugging these in mods in development.

**Comment by RacerDelux** [comment]
Very useful for development and bug reporting.

**Comment by droidicus** [comment]
I created a custom worldgen file for the addon as well based on the v1.5 of the pack (/profile 10000). I was able to profile the Mining Dimension and the Nether, but unfortunately trying to profile the Overworld caused a crash.

If this file is put in config/jeresources then the actual oregen for the pack will be shown when selecting an ore in JEI.

https://gist.github.com/droidicus/6f6b59d477130aa6aa08cb0133e3f0d9

**Comment by RacerDelux** [comment]
Can you put a crash report when you profile in overworld? This could be an issue a mod author needs to look into.

**Comment by droidicus** [comment]
@RacerDelux this was posted as #189 looks like it has been forwarded on the Random Things mod dev.

**Comment by p455w0rd** [comment]
so this is a client-side mod..you're free to add whatever client-side mods you wish :)

**Comment by darkhax** [comment]
I am fully on board with adding this, was about to suggest adding it myself actually.
