### ISSUE TITLE
Mod Request: Psi

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [MinecraftModDevelopment/MMD-Dev-Server#179]
Mod Name:PSI

Mod Version:PSI-R1.1.0-39

Link To Download: 
http://psi.vazkii.us/dl.php?file=Psi-r1.0-39.jar
https://minecraft.curseforge.com/projects/autoreglib

Dependant Mods: As of build 38, Psi requires AutoRegLib. Make sure to have it.

If you're not the author of the mod you are requesting, why should this mod be added:

Um I know we are not in liking of a specific someone but this mod is amazing and fun to have :) so I'm requesting it for that reason.

**Comment by Morpheus1101** [comment]
This would entail sending reports an communication with Vazkii :-1:

**Comment by EPIICTHUNDERCAT** [comment]
great point :)

**Comment by knoxhack** [comment]
👎 I would prefer to no have to deal with Vazkii either

**Comment by EPIICTHUNDERCAT** [comment]
Um, I was wondering if we can reopen this? since we got botania, I like psi too. (cool programming lol) also, Coded is not here SO QUICK

**Comment by Morpheus1101** [comment]
Im still going to stick with my prev statement...botania is bad enough :D

**Comment by EPIICTHUNDERCAT** [comment]
cool :) just wanted to ask again thanks!
