### ISSUE TITLE
Whitelist request: samip537

### ISSUE THREAD

**Issue by samip5** [MinecraftModDevelopment/MMD-Dev-Server#183]
Minecraft IGN: samip537

Discord Username: samip537

What you do (i.e streamer, mod developer, etc.): Mod tester, might stream sometimes.

**Comment by p455w0rd** [comment]
You must be willing to submit bug reports..quite possibly a lot of them. Will you be able to do this when you come across a bug?

**Comment by samip5** [comment]
Yes, I'll be able to do that as needed.
