### ISSUE TITLE
Remove Lawnmower

### ISSUE THREAD

**Issue by darkhax** [MinecraftModDevelopment/MMD-Dev-Server#184]
Reasons to remove
- The mod is a forced meme
- Contributes very little to the over all experience
- Requires LLibrary which I also want to have removed
- Was voted off ages ago by the majority of the server team

Reasons to keep
- **Might** cause an issue when all the blocks/items from this mod are removed from the world. 
- Will destroy Harambe's evidence against the Clinton campaign!

**Comment by Morpheus1101** [comment]
I agree with dark, the mod has no function in the pack, needs no testing, noone uses it etc etc etc

**Comment by EPIICTHUNDERCAT** [comment]
haha

**Comment by knoxhack** [comment]
We will miss you Harambe

**Comment by darkhax** [comment]
I can no longer maintain my silence on this! Earlier last week Hillary Clinton blackmailed the team. She wants us to remove the Lawnmower mod as part of her mission to finish off Harambe. I have come to learn that Harambe had discovered secrets about Hillary Clinton, which would pose a huge threat to her campaign. It is my belief that Harambe hid these secrets in the Lawnmower mod before his death! We can not let the Clintons get away with this!

![image](https://cloud.githubusercontent.com/assets/2250798/18939559/55295186-85be-11e6-9e0c-68ff82669d09.png)

**Comment by p455w0rd** [comment]
Well, we <3 Harambe, been fun DH...

**Comment by knoxhack** [comment]
Hillary did Harambe 😡

**Comment by TheCodedOne** [comment]
... what the actual fuck....

**Comment by TheCodedOne** [comment]
This has been accepted for removal for 8 days, why is it still here!?

**Comment by darkhax** [comment]
Why next map reset? As we have long since established, removing this mod will have no effect on world gen.

**Comment by Morpheus1101** [comment]
If it has noeffect on the world then deff next update, its had its time in the spotlight as such.
