### ISSUE TITLE
Remove LLibrary

### ISSUE THREAD

**Issue by darkhax** [MinecraftModDevelopment/MMD-Dev-Server#185]
Reasons to remove
- Not used by anything, except for Lawnmower. #184 
- Causes general instability and patches into a bunch of random stuff. 

Reasons to keep
- Your reason here

**Comment by RacerDelux** [comment]
This should be added once issues are resolved with compat.

**Comment by iLexiconn** [comment]
If it does, please report it on the repo

**Comment by p455w0rd** [comment]
after talking with @iLexiconn it seems there is validity in having Llibrary on the server. It is a test server, so it has a home here :)
