### ISSUE TITLE
Whitelist request: carstorm

### ISSUE THREAD

**Issue by carstorm** [MinecraftModDevelopment/MMD-Dev-Server#186]
Minecraft IGN: carstorm

Discord Username: carstorm

What you do (i.e streamer, mod developer, etc.): Want to test mods. May also occasionally make vids/stream. Also requesting to join b/c I don't current play on any active 1.01.2 active servers.

**Comment by p455w0rd** [comment]
You will be required to make bug reports as you come across bugs. Are you willing to do this?

**Comment by carstorm** [comment]
Yes!

**Comment by RacerDelux** [comment]
@carstorm You do realize this is a dev server for 1.10.2. If you are wanting to "play" on a server, I would not recommend this one. You must understand the server will have the occasional down time, bugs will happen, player data could get reset in the instance of a game breaking bug. Is this all stuff you are ok with?

**Comment by carstorm** [comment]
Sorry for the delayed response. Anyways, yes I realize this a test server and what that entails.
