### ISSUE TITLE
Whitelist request: Moritz30

### ISSUE THREAD

**Issue by Moritz30** [MinecraftModDevelopment/MMD-Dev-Server#188]
Minecraft IGN: Moritz30

Discord Username: Moritz30 (Matthias)

What you do (i.e streamer, mod developer, etc.): Mod developer

**Comment by p455w0rd** [comment]
May I ask what mod you have developed?

**Comment by Moritz30** [comment]
ArmorPlus, TheDragonCore and some other mods.

**Comment by p455w0rd** [comment]
According to https://github.com/TheDragonTeam/ArmorPlus/commits?author=Moritz30 and https://github.com/TheDragonTeam/TheDragonCore/graphs/contributors you've basically contributed edited a couple of text files. I have also verified this with sokratis, so until I see actual code, I vote no.

**Comment by Moritz30** [comment]
@p455w0rd TheDragonCore's whole HTTP lib is written by me. Sokratis just uploaded it to GitHub.

**Comment by RacerDelux** [comment]
We need to have Sokratis post here verafying your involvement with the project.

**Comment by sokratis12GR** [comment]
@Moritz30 Wrote the HTTP part of TheDragonCore,
