### ISSUE TITLE
Null pointer exception when using JER profiling in overworld (harvestcraft/hempfarmer/JER)

### ISSUE THREAD

**Issue by droidicus** [MinecraftModDevelopment/MMD-Dev-Server#189]
VERY long call stack on this one between harvestcraft, hempfarmer, and JER. Don't know what is going on:

https://gist.github.com/droidicus/93160c68fdc7af94ceb8b8499430e963

**Comment by SeqSEE** [comment]
That looks normal for HempFarmer world generation. Assuming that this was creating a new world?

**Comment by droidicus** [comment]
Not world generation, I was doing a Just Enough Resources profile, so in this case it was generating ~10,000 chunks.

**Comment by p455w0rd** [comment]
Forwarded to lumien231/Random-Things#129
