### ISSUE TITLE
TesterRequest:DracoIIVenom

### ISSUE THREAD

**Issue by DracoIIVenom** [MinecraftModDevelopment/MMD-Dev-Server#19]
Minecraft IGN:DracoIIVenom

Discord Username:DragonKilla

I usually play modded minecraft and noticed you are in need of testers and would like to help. I love to play and build on modded minecraft. I would love to help please consider adding me to the server to test.  

Thanks for taking your time to read this.

**Comment by jriwanek** [comment]
Don't forget to join the MMD discord

**Comment by p455w0rd** [comment]
Sorry, but I must reject this application due to items included below
![Violation of agreement](http://p455w0rd.net/mc/Screenshot_28.png)
![Part of agreement violated](http://p455w0rd.net/mc/Screenshot_29.png)

**Comment by DracoIIVenom** [comment]
I understand
