### ISSUE TITLE
MMD Whitelist Request

### ISSUE THREAD

**Issue by TrikSteve** [MinecraftModDevelopment/MMD-Dev-Server#192]
Minecraft IGN: TrikSteve

Discord Username: TrikSteve

What you do (i.e streamer, mod developer, ect.):  Tester.  Dabble in hosting servers for friends, fixing issues with dead mod packs and reporting issues as I see them.  Have known Knoxhack for awhile and have tested and helped find issues with his various packs over the past year or so.  Would love to help diagnose issues with the mods to make them the best they can be!  Also, by day i'm an IT Network Engineer so finding ways to fix issues is my life :)

**Comment by knoxhack** [comment]
He would be of great help! Has lots of experience reporting issues while making modpacks.

**Comment by RacerDelux** [comment]
@TrikSteve You should have perms now for server. Let me know if you need anything else.
