### ISSUE TITLE
Bug: JEI

### ISSUE THREAD

**Issue by MrTaco9001** [MinecraftModDevelopment/MMD-Dev-Server#193]
Anyone can go into cheat mode a spawn in items. Even me and I don't have perms.

**Comment by TheCodedOne** [comment]
Thats an.. interesting bug..

**Comment by p455w0rd** [comment]
Forwarded to Thutmose/Thut#14

**Comment by Thutmose** [comment]
hopefully I will be able to get this fixed, I don't know if forge sends events in the correct places though.  A temporary solution is to set allowUse in thutpermissions.cfg to false, but that will prevent players from using op commands assigned to their groups without them being op themselves.
