### ISSUE TITLE
Bug: Base Metals Ore not working in EIO SAG mill

### ISSUE THREAD

**Issue by droidicus** [MinecraftModDevelopment/MMD-Dev-Server#195]
The Base Metals Silver Ore is not working in EIO SAG mills, and cannot be inserted.

**Comment by Morpheus1101** [comment]
Im surprised any of the BM stuff works with any machines atm

**Comment by jriwanek** [comment]
Some of it is standard, some isn't I'll take a look after I've finished the current round of other things.

**Comment by Morpheus1101** [comment]
Whats the update status of this jriwanek?

**Comment by jriwanek** [comment]
Hoping to have a new test release out sometime before I move

**Comment by TheCodedOne** [comment]
Any news on this?

**Comment by jriwanek** [comment]
It should be in the dev tip, I'm currently checking everything over to make sure it's good enough for a quick test build for the dev server.

**Comment by Morpheus1101** [comment]
Will this include a quick fix for the Creative Menu crash bug?

**Comment by jriwanek** [comment]
Yes.
