### ISSUE TITLE
Whitelist request: willywizard

### ISSUE THREAD

**Issue by willywizard** [MinecraftModDevelopment/MMD-Dev-Server#197]
Minecraft IGN: willywizard

Discord Username: willywizard

What you do (i.e streamer, mod developer, ect.): mod developer

**Comment by RacerDelux** [comment]
I saw your other issue with the mod you made, but it is easier if you link to your mod in this issue =)

**Comment by willywizard** [comment]
OK sure ill edit it, to have both in one

**Comment by willywizard** [comment]
If you want i can merge the 2

**Comment by EmoKiba** [comment]
@willywizard i was trying to find your source code so i could see how you handled the "charging effect" but couldnt find it do you have it posed like on github or something

**Comment by willywizard** [comment]
I dont have a github page for my mod yet, its fairly new.

And i dont understand what you mean charge effect. There is no pullback effect it just shoots

**Comment by RacerDelux** [comment]
You should go ahead and get a page for it. Your mod needs to be functional in some sense.

**Comment by willywizard** [comment]
Eh whatever

**Comment by p455w0rd** [comment]
@willywizard @RacerDelux Hold the phone..wot? Afiak Elemental Slingshots is functional?Also having a mod has nothing to do with being whitelisted.

**Comment by TheCodedOne** [comment]
Please join the discord

**Comment by p455w0rd** [comment]
Also Racer is wrong..whitelist requests need to be separate from mod requests..you did the right thing @willywizard
