### ISSUE TITLE
Whitelist request: RogueLogic

### ISSUE THREAD

**Issue by RougeLogic** [MinecraftModDevelopment/MMD-Dev-Server#199]
Minecraft IGN: RougeLogic

Discord Username: RogueLogic

What you do (i.e streamer, mod developer, ect.): mod developer.

I changed my username. previous Killerall5385.

**Comment by Morpheus1101** [comment]
Ahh i c you develop Big Fusion, the addon to Extreme Reactors

**Comment by p455w0rd** [comment]
no, @Morpheus1101 , he upload a 100% non-functional jar to Curse to get the dev (now modder) role on Discord..I am waiting to see what he produces.

**Comment by RougeLogic** [comment]
i replaced that with a functional jar.

**Comment by RougeLogic** [comment]
welp I'm screwed. ill just get a better version out and request again.
