### ISSUE TITLE
MOD REQUEST: Endergizer

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#200]
Mod Name: Endergizer

Mod Version: Endergizer-1.10.2-1.1.0.jar

Link To Download: https://minecraft.curseforge.com/projects/endergizer

Dependant Mods: Tesla (all ready in pack)

If you're not the author of the mod you are requesting, why should this mod be added: This mod adds wireless battery's for Tesla which i feel is something need and would work well with the new Tesla Arsenal & Tools added in with ArmorPlus

**Comment by EmoKiba** [comment]
you get a battery from AA and it can be charged

**Comment by Morpheus1101** [comment]
Im aware of the AA one, but this would be better etc etc etc blahh blahh :P

**Comment by knoxhack** [comment]
Don't worry I'm adding a bunch of capacitors (batteries) to Energy Arsenal, I Might add some higher tiers if necessary. Best of all, they support Tesla,RF and Forge Energy :)
