### ISSUE TITLE
Whitelist Equinoxintense

### ISSUE THREAD

**Issue by EquinoxIntense** [MinecraftModDevelopment/MMD-Dev-Server#204]
Minecraft IGN: Equinox_Intense

Discord Username: EquinoxIntense

What you do (i.e streamer, mod developer, ect.): I am a streamer that plays a lot of mad packs and currently learning how to work and put some packs together

**Comment by EmoKiba** [comment]
A great streamer and a good friend and very familiar with modded minecraft (testing modpacks is also his forte)

**Comment by EmoKiba** [comment]
http;//twitch.tv/equinoxintense

**Comment by p455w0rd** [comment]
@EquinoxIntense you have the votes, but we require you to be on the Discord server first.

**Comment by EquinoxIntense** [comment]
Ok would be able to be around until 6ish est on
