### ISSUE TITLE
Mod Updates & Request

### ISSUE THREAD

**Issue by darkhax** [MinecraftModDevelopment/MMD-Dev-Server#206]
|Modname|Version|Link|
|-----------------------|-------|------|
|Bookshelf|1.4.1.321|[curse](https://minecraft.curseforge.com/projects/bookshelf/files/2332251)|
|DarkUtils|1.1.4.86|[curse](https://minecraft.curseforge.com/projects/dark-utilities/files/2332232)|
|Enchanting Plus|4.1.0.112|[curse](https://minecraft.curseforge.com/projects/enchanting-plus/files/2332236)|

I know some people think E+ is a bit over powered, and in many ways it kind of is. However I would like to remind people that the mod now has a grind element to it which prevents players from grabbing any enchantment they want right away, and the EXP costs are much higher compared to Vanilla. The system added in vanilla 1.8 lowered the cost of a max tier enchanting to 3 from 30. I also really need the help testing it out and working on further improving balance and experience.

**Comment by EPIICTHUNDERCAT** [comment]
awesome! E+ would be an amazing addition to MMD :) I want to see it lol

**Comment by p455w0rd** [comment]
next version of PWThings will be requiring bookshelf so =D
