### ISSUE TITLE
Bug: singleplayer in offline mode.

### ISSUE THREAD

**Issue by DoctorFTB** [MinecraftModDevelopment/MMD-Dev-Server#208]
After start modpack in offline mode, not access to internet and join / create singleplayer world - crash. http://pastebin.com/L2GTFy8B

**Comment by Morpheus1101** [comment]
I just created and joined a SP world and looked up p455w0rd mod in JEI an received no crash, this is on a Superflat World & BOp World with no crash issues myself

**Comment by TheCodedOne** [comment]
@Morpheus1101 the issue isn't with singleplayer, its to do with no internet access. Cause @p455w0rd downloads a list from the internet it wont crash if you have internet, only if you dont.

**Comment by Morpheus1101** [comment]
Ahhh, i c .. well there ya go, im never unplugged, thats just plain scary

**Comment by p455w0rd** [comment]
Thank, this is fixed in the update I'll be releasing today :)
