### ISSUE TITLE
Mod Update: Fluid Converters

### ISSUE THREAD

**Issue by rubensworks** [MinecraftModDevelopment/MMD-Dev-Server#209]
Mod Name: Fluid Converters

Version: 1.10.2-2.0.3-44

Link to Updated JAR: https://dl.bintray.com/cyclopsmc/dev/org/cyclops/fluidconverters/FluidConverters/1.10.2-2.0.3-44/FluidConverters-1.10.2-2.0.3-44.jar

Changelog (can be a link): Support new Forge fluid capabilities; Dev build of https://github.com/CyclopsMC/FluidConverters/commit/866c961a779c498b89255722d751c380dc99a8c2

**Comment by p455w0rd** [comment]
Please provide an actual changelog

**Comment by rubensworks** [comment]
@p455w0rd Added a link to the (single changed) commit, will that suffice?

**Comment by p455w0rd** [comment]
yes, you could've also just put:

Changelog (can be a link): Support new Forge fluid capabilities

thank you

**Comment by Morpheus1101** [comment]
This will be most excellent, since i need this for EvilCraft to use with tinkers to use with ID
