### ISSUE TITLE
Whitelist Request: OPG_Skipper

### ISSUE THREAD

**Issue by G6skipper** [MinecraftModDevelopment/MMD-Dev-Server#21]
MMD Dev Server Whitelist Template

Minecraft IGN: OPG_Skipper

Discord Username: OPG_Skippper

What you do: Minecraft buildings on twitch.tv/g6skipper also help updating the plugin Dwarf forge long time ago.(2years ago)

**Comment by TheCodedOne** [comment]
We're going to hold off on whitelisting anyone who doesnt have a mod on the server to give devs the opportunity to apply. We will accept more non-dev apps at a later date.

**Comment by p455w0rd** [comment]
@G6skipper are you still interested in being whitelisted?

**Comment by G6skipper** [comment]
Yes i am and willing

**Comment by Morpheus1101** [comment]
Please join our Discord Channel
