### ISSUE TITLE
Mod Request: Chiseled me

### ISSUE THREAD

**Issue by battery3996** [MinecraftModDevelopment/MMD-Dev-Server#210]
Mod Name: Chiseled Me

Mod Version: v1.0

Link To Download: [Link](https://minecraft.curseforge.com/projects/chiseled-me)

Dependant Mods: none

If you're not the author of the mod you are requesting, why should this mod be added:
 Would love to extreme test it also build be cool to shrink down to the size of nothing while working with tiny tiny tiny bits of blocks

**Comment by battery3996** [comment]
Who disliked it

**Comment by iLexiconn** [comment]
![crssdqh](https://cloud.githubusercontent.com/assets/5201999/18851026/655ec3f4-843a-11e6-9d61-0d9dae6fa468.png)

**Comment by RacerDelux** [comment]
https://i.gyazo.com/f5e3e3e9db3b9395e332f8fdfa3cce6b.png

**Comment by battery3996** [comment]
Hence the reason it needs to be tested and if we can get him in contact with us it might be viewed more. but i already know its a 50 50 chance on it getting in

**Comment by battery3996** [comment]
Well i have been testing it for the past 40 mins or so and no crash besides with optifine.
