### ISSUE TITLE
ArmorPlus Server Crash 

### ISSUE THREAD

**Issue by knoxhack** [MinecraftModDevelopment/MMD-Dev-Server#215]
Version: 1.10.2-7.0.1.0.1-dev
https://gist.github.com/knoxhack/b3212cbb7b0e19d2dd3bd15471488231

**Comment by sokratis12GR** [comment]
It was fixed at: https://github.com/MinecraftModDevelopment/MMD-Dev-Server/issues/213#issuecomment-250396654
