### ISSUE TITLE
MMD Server whitelist

### ISSUE THREAD

**Issue by thecrazycimfam** [MinecraftModDevelopment/MMD-Dev-Server#218]
Minecraft IGN: Thecrazycimfam

Discord Username: Thecrazycimfam

What you do (i.e streamer, mod developer, ect.):
I am a Small time streamer till marching season is over then ill be doing decent hours (more then 2 probably).. www.twitch.tv/thecrazycimfam

**Comment by Morpheus1101** [comment]
Welcome to the server :)
