### ISSUE TITLE
Mod update request: Extreme Reactors

### ISSUE THREAD

**Issue by ZeroNoRyouki** [MinecraftModDevelopment/MMD-Dev-Server#224]
Mod Name: Extreme Reactors

Version: 1.10.2-0.4.5.16

Link to Updated JAR:
https://minecraft.curseforge.com/projects/extreme-reactors/files/2333287

Changelog (can be a link):
* Added support for Forge Energy to RF Power Taps
* Handling neighbor changes only when needed. Close  ZeroNoRyouki/BigReactors#16
* Fixed coolant container update on the client. Close  ZeroNoRyouki/BigReactors#18
* Fixed Turbine fluid port I/O
* Implemented getPickBlock(). Close  ZeroNoRyouki/BigReactors#19. Make The One Probe happy :)
* Bumped version to 0.4.5.16 and updated to Forge 1.10.2-12.18.1.2084

Required Updated Dependency JAR Link(s):
ZeroCore 1.10.2-0.0.8.0 (already on the server)

**Comment by TheCodedOne** [comment]
Just for future reference, doing # number does it for the repo you are commenting on, doing user/repo# number, such as ZeroNoRyouki/BigReactors#16 would link to that repo

**Comment by ZeroNoRyouki** [comment]
My bad! :)
Fixed

**Comment by ZeroNoRyouki** [comment]
A new bug-fix release is out:

https://minecraft.curseforge.com/projects/extreme-reactors/files/2334287

* Fixed a comulative error in the fluid per blade rate
* Fixed RF Power Taps voiding powers if nothing is connected to them
* Fixed Forge Energy capab check
