### ISSUE TITLE
Whitelist Application

### ISSUE THREAD

**Issue by elucent** [MinecraftModDevelopment/MMD-Dev-Server#226]
IGN: Elucent
Discord: Elucent
What I do: Mod Dev

**Comment by Morpheus1101** [comment]
Good to c the roots Mod Dev :)

**Comment by EPIICTHUNDERCAT** [comment]
LET him in :)

**Comment by Morpheus1101** [comment]
Well i certainly need someone to teach me what im doing wrong with roots, so i can become even more omnipotent on the server

**Comment by Morpheus1101** [comment]
Welcome to the server
