### ISSUE TITLE
Mod Request: Embers(WIP)

### ISSUE THREAD

**Issue by elucent** [MinecraftModDevelopment/MMD-Dev-Server#227]
I just compiled a theoretically functional version of my WIP magitech mod, Embers. I'd love to be able to test this on the MMD server, since it gives me an excuse to try this pack out, and especially since the guy who runs my normal testing server is away at the moment.

The mod can be downloaded here for now: https://dl.dropboxusercontent.com/s/rnirl8run61f1bp/embers-0.001.jar?dl=0

It will likely need its oregen configured off. It adds copper, lead, and silver ore (the latter of which is currently unused, but will be very important in future updates), which I assume the server probably has from some other mod.

**Comment by EPIICTHUNDERCAT** [comment]
:)
