### ISSUE TITLE
 Whitelist Request: DemonGirl143

### ISSUE THREAD

**Issue by EmoKiba** [MinecraftModDevelopment/MMD-Dev-Server#228]
Minecraft IGN: DemonGirl143

Discord Username: Demon#1475

What you do (i.e streamer, mod developer, ect.):
I'm a streamer getting started I watch a lot of Kiba's Streams so I have general knowledge I excel in building though

**Comment by Morpheus1101** [comment]
is your partner not able to do a request herself kiba?

**Comment by EmoKiba** [comment]
she's at the doctor and just got the pc it was gonna be a suprise for her

**Comment by Morpheus1101** [comment]
Very nice of you :D

**Comment by EPIICTHUNDERCAT** [comment]
haha, yay

**Comment by EmoKiba** [comment]
where is that approval haha

**Comment by darkhax** [comment]
Probably waiting on me, sorry lol. Haven't been feeling so good the last few days.

**Comment by Morpheus1101** [comment]
What is your new username demon so we can add you?

**Comment by EmoKiba** [comment]
d3m0nG1rl143

**Comment by Morpheus1101** [comment]
She has been added to the whitelist an is good to go :D
