### ISSUE TITLE
Whitelist Request: Fae_Vena

### ISSUE THREAD

**Issue by Faenum** [MinecraftModDevelopment/MMD-Dev-Server#233]
Minecraft IGN: Fae_Vena

Discord Username: Faenum

What you do (i.e streamer, mod developer, ect.): Artist and mod creator

**Comment by Morpheus1101** [comment]
What mod ?

**Comment by Faenum** [comment]
Better Agriculture is my creation, Knox is coding it for me as I cant code. Ive also done textures for nether metals and epic_thundercats thundercats mod and tesla arsenol. Knox codes for me, I texture for knox when he needs it

**Comment by RacerDelux** [comment]
@knoxhack can you confirm?

**Comment by knoxhack** [comment]
Yeah, she is also MMD staff she helps jriwanek(cyb3kat) and me with textures.

https://minecraftmoddevelopment.github.io/members.html
