### ISSUE TITLE
Mod Request: Big Fusion

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#236]
Mod Name: Big Fusion

Mod Version: 0.0.1

Link To Download: https://minecraft.curseforge.com/projects/big-fusion/files

Dependant Mods: Tesla, Extreme Reactors, and ZeroCore

If you're not the author of the mod you are requesting, why should this mod be added:

Big Fusion is a fusion reactor expansion based on the Extreme Reactors (Big Reactors) mod and be a good alternative to test out also being a new mod with the Author also wanting to become Whitelisted as part of the MMD crew.

**Comment by RogueLogic** [comment]
I approve. no recipes ATM though so its creative only.

**Comment by Morpheus1101** [comment]
Can always delay its addition IF accepted untill recipes are added

**Comment by RogueLogic** [comment]
i mean it is a test server so i could push a small update with temp recipes.

**Comment by RogueLogic** [comment]
@Morpheus1101 Tesla, Extreme Reactors, and ZeroCore (required for ER anyway) of any version are required dependents. no additional dependents are required afaik.

**Comment by RacerDelux** [comment]
If you make sure to actively fix bugs that may appear, I am all for it.

**Comment by RogueLogic** [comment]
not a problem. i thought that was part of being a developer.

**Comment by Morpheus1101** [comment]
Soon as you can add in some recipes etc for use with survival, we'll add it in :)

**Comment by RogueLogic** [comment]
Nuice.

**Comment by TheCodedOne** [comment]
Any word on this?

**Comment by RogueLogic** [comment]
I'm working on the recipes ATM and should have them and FE support done this weekend.

**Comment by RogueLogic** [comment]
i have recipes done but need to test / bugfix (i know it wont work first try) on multiplayer.

**Comment by RogueLogic** [comment]
surprisingly, it worked first time on multiplayer. ive still got a couple of bugs (NBT) to fix but it SHOULD be ready tomorrow.

**Comment by Morpheus1101** [comment]
Whats the update on this in terms of recipes ?

**Comment by RogueLogic** [comment]
just pushed new version with recipes (0.0.1.1).
