### ISSUE TITLE
Mod Request: Immersive Engineering

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#237]
Mod Name: Immersive Engineering

Mod Version: Immersive Engineering 0.10 - 44	

Link To Download: https://mods.curse.com/mc-mods/minecraft/231951-immersive-engineering

Dependant Mods: None?

If you're not the author of the mod you are requesting, why should this mod be added:
This mod a lot of different an unique ways to create power and be able to transmit power without simply jsut hooking up a cable an off u go, you have to beware of having to much or burning the wire out or causing dmg to machines by running to much, i loved this pack in 1.7.10 and with all the content updates, im excited to want to try this on the Dev server rather than using the public server.

**Comment by RacerDelux** [comment]
I actually never go to play around with this mod...

**Comment by p455w0rd** [comment]
It's an amazing mod, but last I checked there were game breaking bugs..i'll check soon and see what state it's currently in

**Comment by p455w0rd** [comment]
Looked into it, seems BluSunrise it regularly fixing stuff...I'm for it :)
