### ISSUE TITLE
Mod Removal Request: Hempfarmer

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#239]
This mod adds basically nothing in the game of any value that requires testing or any sort of functionality.

**Comment by SeqSEE** [comment]
Working on an update for hybridization that will need testing along with a
bunch of other things. Can be removed, but will request again once the
update is finished.

**Comment by darkhax** [comment]
Keep in mind that running the mod in a large environment is also testing. I don't think we should ever remove a mod because it's too stable.

**Comment by Morpheus1101** [comment]
Its not that its to stable as no mod can ever be to stable

**Comment by Morpheus1101** [comment]
See https://github.com/MinecraftModDevelopment/MMD-Dev-Server/issues/242
