### ISSUE TITLE
Mod Removal Request: Better Agriculture

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#240]
Adds no functionality to the game other then diff types of the vanilla animals which require its own type in able to be bred and has no interaction with the vanilla animals

**Comment by darkhax** [comment]
I am on the fence with this mod. I like what it is trying to do, although it lacks creativity. Is the dev part of MMD? If not, I saw we remove it.

**Comment by knoxhack** [comment]
Cyb3rkat (jriwanek), me and Faenum are the devs, so yeah we all mmd staff. I would like it to stay since we are gonna be soon adding more content that will need testings. (Crossbreeding,wardrove, and other blocks with GUIs and more)

**Comment by knoxhack** [comment]
And yeah the mod still in alpha stage, lots of features on our to do lost are still yet to be implemented.

**Comment by knoxhack** [comment]
*list

**Comment by Morpheus1101** [comment]
see https://github.com/MinecraftModDevelopment/MMD-Dev-Server/issues/242

**Comment by knoxhack** [comment]
Ok, whatever
