### ISSUE TITLE
Whitelist Request: Mysteryem

### ISSUE THREAD

**Issue by Mysteryem** [MinecraftModDevelopment/MMD-Dev-Server#243]
Minecraft IGN: mysteryem

Discord Username: Mysteryem#3552

What you do (i.e streamer, mod developer, ect.): Mod developer. I also manage a small community's Minecraft servers, if that's relevant here.

**Comment by Morpheus1101** [comment]
Could you do a separate request for your mod please.

**Comment by Mysteryem** [comment]
Done, see #245 for the mod request.
