### ISSUE TITLE
Whitelist Application

### ISSUE THREAD

**Issue by gamingninja10** [MinecraftModDevelopment/MMD-Dev-Server#25]
Minecraft IGN: THEGamingninja12

Discord Username: THEGamingninja

What you do (i.e streamer, mod developer, ect.): [Youtuber](https://www.youtube.com/channel/UCxApCMvksyuz1oagzH23ocA) (PS My microphone makes me sound younger than I am, I have sort of fixed it recently though)

**Comment by TheCodedOne** [comment]
We're going to hold off on whitelisting anyone who doesnt have a mod on the server to give devs the opportunity to apply. We will accept more non-dev apps at a later date.

**Comment by p455w0rd** [comment]
@gamingninja10 are you still interested in being whitelisted?

**Comment by gamingninja10** [comment]
Yes

**Comment by gamingninja10** [comment]
@p455w0rd Yes

**Comment by Morpheus1101** [comment]
Were you added to the whitelist ?

**Comment by gamingninja10** [comment]
As far as I can tell, no

**Comment by Morpheus1101** [comment]
At this stage its a waiting game untill required votes have been placed, so just keep checking periodically :)

**Comment by RacerDelux** [comment]
Being a youtuber is good and all, but being a dev server, are you able to report bugs, and do you understand that things like items being deleted, crashes or even world resets can happen?

**Comment by gamingninja10** [comment]
@RacerDelux Yes, I understand all this stuff, I like to play some beta/alpha games
