### ISSUE TITLE
Mod Request: Realistic Terrain Generation

### ISSUE THREAD

**Issue by whichonespink44** [MinecraftModDevelopment/MMD-Dev-Server#251]
**Mod Name:**
Realistic Terrain Generation

**Mod Version:**
4.1.1.2

**Link To Download:**
https://minecraft.curseforge.com/projects/realistic-terrain-generation/files/2333854

**Dependant Mods:**
Since Biomes O' Plenty is currently in the pack, you would also need either [Climate Control](https://minecraft.curseforge.com/projects/climate-control) or [BiomeTweaker](https://minecraft.curseforge.com/projects/biometweaker) in order to generate BOP biomes in the 'Realistic' world type. Climate Control (also known as GeographiCraft) is essentially plug 'n' play, whereas BiomeTweaker requires some [initial configuration](https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/1.10.2-master/etc/biometweaker/BiomesOPlenty).

**If you're not the author of the mod you are requesting, why should this mod be added:**
I'm one of the authors.

**If the mod is not currently hosted anywhere, please give a brief description of the mod:**
Realistic Terrain Generation (RTG) is a mod that adds a new world type which generates realistic terrain. It doesn't add new blocks. It doesn't add new mobs. It doesn't even add new biomes. It simply generates more realistic-looking terrain for existing Overworld biomes (including those added by other mods).

**Comment by p455w0rd** [comment]
I'd like to see this in v2.0

**Comment by srs-bsns** [comment]
Just so it is absolutely clear, RTG is a server-side mod and is not required on the client. The same goes for the support mods (GeographiCraft/ClimateControl, BiomeTweaker) in order to utilise mod added biomes.

**Comment by whichonespink44** [comment]
Thanks for adding RTG to the mod pack - hope it doesn't disappoint.

I noticed that you also added both Climate Control and BiomeTweaker, but... you don't need either of those two mods if you're **not** running BOP, so... unless you've included them for something else, you can remove those two mods and RTG will work perfectly fine.

(And if you *do* end up using BOP, you only need to include one or the other, so... either Climate Control **or** BiomeTweaker.)

((And finally, if you *do* end up using Climate Control, be advised that it has a bias towards oceanic worlds by default, so at a bare minimum, you'll probably want to set `separateLandmasses=false` in the CC configs.))

\</parentheses>

**Comment by srs-bsns** [comment]
And don't forget `level-type=RTG` in `server.properties`.. it gets overlooked sometimes.

**Comment by Morpheus1101** [comment]
Woops, forgot about BOP, but yes we are running it and the s.prop has RTG in the level type and BT was removed leaving CC behind
