### ISSUE TITLE
Mod Request: Reliquary

### ISSUE THREAD

**Issue by EmoKiba** [MinecraftModDevelopment/MMD-Dev-Server#257]
Mod Name: Reliquary

Mod Version: 1.1.0

Link To Download: https://mods.curse.com/mc-mods/minecraft/241319-reliquary-v1-3#
Dependant Mods: None
Reasons to add: Reliquary has a lot of functions useful for increasing growth ticks and stuff and add its own loot drops and im curious how these drops will work with my eve shard drops

**Comment by Morpheus1101** [comment]
The way id see it would be, add reliquary, remove mystical Agriculture as lillypads of fertility + mysticl agri would make things way to OP

**Comment by EmoKiba** [comment]
im down for the removal of MA its not needed in a ore generated world personally and if you want yellorite thats why we added forestry ping Zero about the yellorite bees addon he was adding to Extreme Reactors

**Comment by p455w0rd** [comment]
Okay..so without trying to make either of you mad, I will say that this is a dev env. OP has nothing to do with the server. There is no competition. I have nothing against the mod being on the server as something being OP is 100% irrelevant. I strongly dislike the acronym as modded in general is OP when comparing to vanilla. DE is OP compared to damn near any other mod. However, we have a decent sized base mod list and I feel we should wait until v2.0 is live before adding new mods to the pack (save for mods that are in-dev and already planned to be added).
