### ISSUE TITLE
Whitelist Request: Saereth

### ISSUE THREAD

**Issue by Saereth** [MinecraftModDevelopment/MMD-Dev-Server#258]
# MMD Dev Server Whitelist Template

**Minecraft IGN**: Saereth

**Discord Username**: Saereth

**What you do** (_i.e streamer, mod developer, ect._): Mod and Modpack Developer

**Comment by Morpheus1101** [comment]
What mods Have//Do you develop currently?

**Comment by Saereth** [comment]
Modpacks - Nuts and Bolts as well as Everything is hostile Technic Launcher
Mod - https://minecraft.curseforge.com/projects/nova
as well as several lesser known projects and contributions to other mods
https://github.com/breakinblocks
