### ISSUE TITLE
Mod Request: Cyclops mods

### ISSUE THREAD

**Issue by rubensworks** [MinecraftModDevelopment/MMD-Dev-Server#26]
| Mod Name | Version | Download | Dependencies |
| --- | --- | --- | --- |
| CyclopsCore | 0.7.7 | [curse](https://minecraft.curseforge.com/projects/cyclops-core/files/2327552) | N/A |
| EvilCraft | 0.10.11 | [curse](https://minecraft.curseforge.com/projects/evilcraft/files/2327571) | CyclopsCore |
| Integrated Dynamics | 0.5.1 | [curse](https://minecraft.curseforge.com/projects/integrated-dynamics/files/2327561) | CyclopsCore, Common Capabilities |
| Common Capabilities | 1.1.2 | [curse](https://minecraft.curseforge.com/projects/common-capabilities/files/2327580) | CyclopsCore |
| Colossal Chests | 1.3.9 | [curse](https://minecraft.curseforge.com/projects/colossal-chests/files/2322782) | CyclopsCore |
| Structured Crafting | 0.1.6 | [curse](https://minecraft.curseforge.com/projects/structured-crafting/files/2312900) | CyclopsCore |
| Fluid Converters | 2.0.3 | [curse](https://minecraft.curseforge.com/projects/fluidconverters/files/2312916) | CyclopsCore |
| Energy Synergy | 1.0.1 | [curse](https://minecraft.curseforge.com/projects/energysynergy/files/2327575) | CyclopsCore |
| Everlasting Abilities | 1.1.1 | [curse](https://minecraft.curseforge.com/projects/everlastingabilities/files/2327556) | CyclopsCore |

**Comment by knoxhack** [comment]
I vote yes to all.

**Comment by knoxhack** [comment]
¯\_(ツ)_/¯

**Comment by rubensworks** [comment]
To the person responsible for adding the mods:
It would be best to enable retrogen in the EvilCraft config file to make sure that mod can be played.
For Integrated Dynamics, it would be good to add some cheat in some Menril Trees and place them on spawn, so people have a way to get those saplings instead of having to generate new chunks.

**Comment by battery3996** [comment]
well considering with more mods being added and with certain update to the mod that are still being developed, there is most likely going to be a new world brought onto the server

**Comment by rubensworks** [comment]
Note: I updated the versions of some of the mods in this list. If you want me to report these changes somewhere else instead, please let me know.
