### ISSUE TITLE
Whitelist Request: Aarronmc

### ISSUE THREAD

**Issue by Aarronmc** [MinecraftModDevelopment/MMD-Dev-Server#261]
Minecraft IGN: Aarronmc

Discord Username: Aarron

What you do: Mod Developer

**Comment by Morpheus1101** [comment]
What mods do you//have you made?

**Comment by Aarronmc** [comment]
https://github.com/Aarronmc/Wallpapers?files=1

Currently in development.

**Comment by p455w0rd** [comment]
next time you're on discord, ping me and I'll set your role/give info
