### ISSUE TITLE
Mod Request: Recurrent Complex (v2)

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftModDevelopment/MMD-Dev-Server#262]
Mod Name: Recurrent Complex

Mod Version: 1.2.2 (It is very important this version and not 1.2.3 is used)
(Oh and if we use it don't update RTG past 4.1.1.4 unless WhichOnesPink removes the dependency)

Link To Download: https://minecraft.curseforge.com/projects/recurrent-complex/files/2337490

If you're not the author of the mod you are requesting, why should this mod be added:

The mod adds neat structures around the world and also has additions to village generation that are good to explore.

**Comment by srs-bsns** [comment]
This is a bad idea. We've added a custom tree decoration event in the latest version of RTG (4.1.1.5) to mitigate issues of over-decoration (Mostly apparent with RecurrentComplex). We worked with IvorForce to solve the issue and he has added code to utilise the new tree decoration events in ReC v1.2.3, however there is still an issue in this version of ReC (resource loading). I'd suggest waiting for newer version of ReC that addresses this issue.

**Comment by Shadows-of-Fire** [comment]
Either way, we can't use ReC 1.2.3, and we can't use RTG 4.1.1.5 with ReC 1.2.2.   
There is a config that basically fixes the issue that 1.2.3-4.1.1.5 fixes (for the most part)

**Comment by Morpheus1101** [comment]
This is on hold untill all issues have been resolved and all Admins are back onboard :D

**Comment by Morpheus1101** [comment]
Due to multiple conflicts with RTG and the lack of any timely updates of this mod, we feel it wouldnt suit this environment
