### ISSUE TITLE
Mod Request: Cyberware

### ISSUE THREAD

**Issue by Flaxbeard** [MinecraftModDevelopment/MMD-Dev-Server#264]
**Mod Name**:
Cyberware

**Mod Version**:
Beta 0.2.3

**Link To Download**:
https://minecraft.curseforge.com/projects/cyberware/files/2333106

**Dependant Mods**:
N/A, integrates with Tough as Nails and will have future integration with Botania, Blood Magic, Roots, and Embers. None of these are required.

**Comment by Morpheus1101** [comment]
This most certainly seems very interesting and im quite intrigued
