### ISSUE TITLE
Mod Update: ArmorPlus (v2)

### ISSUE THREAD

**Issue by sokratis12GR** [MinecraftModDevelopment/MMD-Dev-Server#266]
**Mod Name**: ArmorPlus

**Version**: 1.10.2-8.0.0.2

**Link to Updated JAR**: http://fdn.redstone.tech/TheDragonTeam/armorplus/jars/1.10.2-8.0.0.2/armorplus-1.10.2-8.0.0.2.jar

**Link to sources**: http://fdn.redstone.tech/TheDragonTeam/armorplus/jars/1.10.2-8.0.0.2/

**Changelog (can be a link)**: https://github.com/TheDragonTeam/ArmorPlus/blob/1.10.2/github-changelogs.md#armorplus-1102-8002

**Required Updated Dependency JAR Link(s)**:

**Comment by sokratis12GR** [comment]
Mobile pls

**Comment by Morpheus1101** [comment]
On Hold untill crash issue fixed :D
