### ISSUE TITLE
Mod Removal: Localized Weather & Storms

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#276]
While pretty this mod seems to be generating a lot of annoyance among testers. From it's constant thundering 24/7 to random tornadoes damaging things to massive lag due to its cloud system. I checked the Github and I cannot find who requested it nor does anyone seem to know who did. I'm personally unsure why we have it as it doesn't seem to assist in testing nor game play in any way.

So I'd like to call for its removal unless there is a significant reason to keep it.

**Comment by p455w0rd** [comment]
Tho I have yet to log on to the server, I agree that it should be removed. It seems to be causing a lot of hassle which can only hinder actual testing and deter users from wanting to log on. Thanks for this report :)
