### ISSUE TITLE
Mod Request: Mouse Tweaks

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#277]
**Mod Name**: Mouse Tweaks

**Mod Version**: 2.6.4

**Link To Download**: https://mods.curse.com/mc-mods/minecraft/mouse-tweaks

**Dependant Mods**: None that I know of

**If you're not the author of the mod you are requesting, why should this mod be added**: More efficiency in dealing with inventories and slots, especially the scroll wheel to move items feature.

**Comment by Morpheus1101** [comment]
MT is a client side only mod :D
