### ISSUE TITLE
Mod Request: World Control

### ISSUE THREAD

**Issue by dmf444** [MinecraftModDevelopment/MMD-Dev-Server#278]
**Mod Name:** World Control

**Mod Version:** 1.10.2-0.1.0a

**Link To Download:** if accepted, can build and send

**Dependant Mods:** none

**If you're not the author of the mod you are requesting, why should this mod be added:** 
I am the co-author.

**If the mod is not currently hosted anywhere, please give a brief decription of the mod:**
Mod is the spiritual successor to Nuclear Control 2. We are currently removing dependencies from IC2 so we've renamed the mod. If IC2 is not present, there are a couple other features that have been added. (Goal is to test the mod's network usage, I want to make sure its decent when it gets released.)

Side note: Can I be whitelisted on the sever as well? MC name is dmf444

**Comment by Morpheus1101** [comment]
At this stage we would rather wait untill it is completely independant from IC2 and we would gladly look to add it in a bug test it to death for you :D

**Comment by dmf444** [comment]
it's 100% ic2 independent, atm.

**Comment by p455w0rd** [comment]
looking forward to it :)
