### ISSUE TITLE
Mod request: AE2 Stuff

### ISSUE THREAD

**Issue by juryjr** [MinecraftModDevelopment/MMD-Dev-Server#279]
Mod Name: AE2 Stuff

Mod Version: AE2Stuff 0.6.0.3 (MC 1.10.2)

Link To Download: https://minecraft.curseforge.com/projects/ae2-stuff/files/2341488

Dependant Mods: ae2
If you're not the author of the mod you are requesting, why should this mod be added:
 a lot of people on the dev server have asked for it even one of the admins of the server it would be great for us to see how well it works also

**Comment by EmoKiba** [comment]
no
plz no

**Comment by p455w0rd** [comment]
please use the request form to submit the request properly
