### ISSUE TITLE
Mod Request: Draconic Evolution

### ISSUE THREAD

**Issue by brandon3055** [MinecraftModDevelopment/MMD-Dev-Server#28]
Mod | Download | Dependency
------ | -------- |  ------- 
Draconic Evolution | https://puu.sh/qTX1R/2691868f50.jar | Brandon's Core 
Brandon's Core | https://puu.sh/qTWZk/9fa39a0c3f.jar | Code Chicken Lib (Includes Dep Downloader)

**Comment by p455w0rd** [comment]
I have heavily tested with the current (v1.1.1) pack and could not get the game to crash
