### ISSUE TITLE
Mod Request: HelpFixer

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#280]
**Mod Name**: HelpFixer

**Mod Version**: 1.4.15

**Link To Download**: https://minecraft.curseforge.com/projects/helpfixer?gameCategorySlug=mc-mods&projectID=223797

**Dependant Mods**: None that I know of

**If you're not the author of the mod you are requesting, why should this mod be added**: Because modders still have not learned to fill in their auto-created code stubs thereby breaking the /help command for any mod pack with more than 1 mod. We need this. In 2.0 by chance /help was working now in 2.0.5 it is not.

**Comment by p455w0rd** [comment]
since help is working, i'm just going to set this to on-hold and close it for now
