### ISSUE TITLE
Whitelist Request: SeriousCreeper

### ISSUE THREAD

**Issue by Kiyaku** [MinecraftModDevelopment/MMD-Dev-Server#281]
**Minecraft IGN:** SeriousCreeper

**Discord Username:** SeriousCreeper

**What you do (i.e streamer, mod developer, ect.):** I'm mostly a YouTuber focusing on minecraft and other variety games. Been doing this for around 5 years now. Worked a lot on my own custom modpacks with modifications, and eventually started to check out creating mods as well. I only have a small one on curse at this point (Crafting Runes) and submitted a few fixes/changes for other mods (Mariculture, Harvest Festival). 

Would love to join the server and help testing new mods/updates when they come out. Having played a lot of modded and worked on packs and mods myself, i'm hoping my knowledge can help out somewhat! 

Thanks,
SC

**Comment by Morpheus1101** [comment]
Could you give us a link to your YT channel plz?

**Comment by Kiyaku** [comment]
Ah yes, of course! https://www.youtube.com/SeriousCreeper

**Comment by EPIICTHUNDERCAT** [comment]
could we have him join XD
