### ISSUE TITLE
Whitelist request : P1st0lpr0

### ISSUE THREAD

**Issue by P1st0lpr0** [MinecraftModDevelopment/MMD-Dev-Server#288]
Minecraft IGN: XxSTEGxX_i

Discord Username: P1st0lpr0 (But on MMD Server "Pista")

What you do (i.e streamer, mod developer, etc.): I'm the modpack maker of "StegiCraft" (Curse), and I really like minecraft mods, and I would want to test some on the dev server. Tho, I would not only test mods, I would play daily / every second day on the server. I'd like to cooperate with the modder/streamer community in-game, too.

**Comment by P1st0lpr0** [comment]
+I'm very experienced with mods, and if my english is sometimes bad, it's becouse I'm from germany.

**Comment by p455w0rd** [comment]
Are you aware that it is a requirement to file bug reports as you find them? The mods on the server canat times be very buggy and we run the server to find the bugs quicker to be able to get the mods to a stable state faster.

**Comment by P1st0lpr0** [comment]
Well , as I said I would try to find bugs and report them as I see them. And I know that the server can be buggy sometimes, becouse I know it's there to test mods.

**Comment by p455w0rd** [comment]
pin me next time you're on discord

**Comment by P1st0lpr0** [comment]
@p455w0rd What do you mean with "Pin me"? I can't pin you somewhere on discord.

**Comment by p455w0rd** [comment]
i meant ping
