### ISSUE TITLE
Bug Report: Tinkers' Construct Crafting Stations Duplicating Materials Randomly

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#291]
Steps to reproduce (Randomly):

1. I placed 1 Tinkers' Construct Crafting Station down with no blocks around it.
2. I placed the ingredients for a Get Ya' Tanks Here Tank upgrade. 5 cobble, 4 glass panes.
3. I then placed a second Tinkers' Construct Crafting Station down on the left (south) side of the first table. I opened it curious if it would display the other table as an inventory, it did. I closed it and opened the first table.
4. I removed the product and the 4 glass panes were left in the crafting grid. I thought I had inserted double by mistake.
5. Then I attempted to craft 2 Blue Chicken Eggs from the Chickens mod in the same table. 2 Eggs, 2 Lapis. The first product reduced both ingredients to 1 each, however the second craft left the egg behind.

I attempted to reproduce this using cobble making tons of slabs, and also attempted the above again and could not get a duplicate ingredient.

**Comment by Morpheus1101** [comment]
I've attemtped to reproduce what you instructed here, but am unable to re-produce this myself...could you try it after this update and see if it still occurs?

**Comment by Morpheus1101** [comment]
I've attemtped to reproduce what you instructed here, but am unable to re-produce this myself...could you try it after this update and see if it still occurs?

**Comment by Aedda** [comment]
Since it seems to randomly occur I'll report if it happens again.
