### ISSUE TITLE
Bug Report: Veinminer

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#292]
Veinminer is randomly causing ore to not drop. At this time no pattern to when it deletes ore has been revealed. It is not dependent on inventory being full.

**Comment by Morpheus1101** [comment]
They drop, but they disappear into a hole somewhere, ive had this issue as well but no idea had to reproduce consistently

**Comment by Morpheus1101** [comment]
The Mod maker has tagged this issue as Enhancement, so its now a matter of time to if//when it will be done.
