### ISSUE TITLE
Mod Removal: Ender Zoo (or at least removal of Khndrel Keght)

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#296]
As the title says. I just lost 24 levels of exp because I broke a piece of grass with a Mattock, and it turned into one of those damned things as large as my house. Even with a 12 damage sword it beat me before I could beat it. Then it killed me again trying to get to my grave to get my sword back.

https://i.imgur.com/qYH9CSW.png

Not reasonable, not fun, it just makes digging a pain in the ass, and sometimes a fatal pain in the ass.

**Comment by p455w0rd** [comment]
After experiencing what this mod has become, I agree..it's trash...just another to go on the list of mods that were cool but are now just annoying af
