### ISSUE TITLE
Bug Report: Dying due to Chance Cube maze trap does not spawn Gravestone

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#297]
Not sure where this even falls. Broke a Chance Cube, got stuck in the bedrock maze trap, died. When I respawned all my things were scattered around where the cube was with no Grave. However a Death Info paper was successfully spawned in my inventory.

**Comment by p455w0rd** [comment]
morph... :)

**Comment by EPIICTHUNDERCAT** [comment]
It should be noted that you break chance cubes at your own risk, this is not a bug because the maze breaks blocks when despawning and spawning. what happened here was the grave was broken as the maze disappeared.

**Comment by Aedda** [comment]
Ah well then that is explained and also why I put this here instead of directly on the authors issue tracker. Thanks @EPIICTHUNDERCAT
