### ISSUE TITLE
Bug Report: Gravestone / Botania

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#299]
When dying the Death Note produced by Gravestone lists every Botania flower as Mystical White Flower. It is obviously not recording the meta/damage of the item only the name/id.

**Comment by Morpheus1101** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod/issues/6

**Comment by Morpheus1101** [comment]
Could you give me a screenshot of this plz?

**Comment by Aedda** [comment]
https://i.imgur.com/KvDHDv2.png

**Comment by Morpheus1101** [comment]
This has been fixed now and will be in the next update.
