### ISSUE TITLE
Bug Report: Buckets with fluid clicked against blocks spawn fluid on backside of block

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#302]
Buckets with fluid clicked against blocks spawn fluid on backside of block.

Only tested against water and lava as it is all I had to test with. When clicking a block with an air block behind it the fluid spawns there instead of on the front face of the block.

**Comment by Aedda** [comment]
I have confirmed this, in SSP with the following mods the bug can be reproduced. It does not reproduce if CoFHCore is removed.

CoFHCore-1.10.2-4.0.0.4-universal
CodeChickenLib-1.10.2-2.4.3.128-universal
CodeChicken Core 1.10.2-2.3.5.91-universal

**Comment by Morpheus1101** [comment]
@p455w0rd wasnt this an issue mentioned with cofh ?

**Comment by Morpheus1101** [comment]
Atm, this unf will remain a thing for a lil bit as a re-write of a portion is needed.
