### ISSUE TITLE
Config Change: Add Tinkers' Construct Mattock to Veinminer Axe list

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#303]
The Mattock is actually a Shovel, Hoe, and Axe in one and is effective against logs. However it lacks an entry under axes in the Vein Miner config. Would be nice to have that added.

**Comment by Morpheus1101** [comment]
It maybe myself adding this in wrongly, but when added into the config veinminer cracks a stink about it...i'll have more of a play with this tomorrow and see if i cant get it working.

**Comment by Aedda** [comment]
Error log? :)

**Comment by Aedda** [comment]
I have discussed with @Morpheus1101 that I would be fine with forgoing this change as 1) it seems to just make it angry, 2) the damage is already done in terms of floating trees everywhere, and 3) VeinMiner is unable to consistently cut down large trees so the change seems to be moot.
