### ISSUE TITLE
Config Change: VeinMiner increase radius from 20 to 50

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#304]
We have a lot of really tall trees thanks to BoP. Unfortunately VeinMiner by default isn't configured for anything nearly as large. This is resulting in floating tree tops in some areas and it becomes a pain to then finish the job. I've measured the tallest common trees I can find and they are 50 blocks tall. So it seems it would make sense to increase that limit.

**Comment by Morpheus1101** [comment]
This where making a LumberAxe comes into play, it will veinmine the very large tree's as long as it has the durability otherwise it will veinmine untill it breaks, if its unbreakable it could even do a forest :D

**Comment by Aedda** [comment]
The problem with that as I see it is progression, it is infinitely easier to get a normal axe than it is a Tinkers' Construct tool. This means trees are most likely to be Veinmined with a regular axe before the player has access to the latter and once the tree tops are there they are just a pain to clean up then. This is one reason I really liked TreeCapitator over the other options as it had the option to break the furthest blocks first. Actually that doesn't sound like an entirely bad feature for Veinminer to support either...
