### ISSUE TITLE
Bug Report: [Ender Utilities] Chests & Tinkers Crafting Station

### ISSUE THREAD

**Issue by sokratis12GR** [MinecraftModDevelopment/MMD-Dev-Server#305]
![image](https://cloud.githubusercontent.com/assets/12274096/20042621/25f10b5c-a486-11e6-8e77-9a76ceeff6c5.png)
Extended Memory Chest upgraded storage doesn't support Tinkers' Construct Crafting Station

**Comment by Morpheus1101** [comment]
This isnt a bug, but more a feature request for added support
