### ISSUE TITLE
Update request: Literal Ascension

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [MinecraftModDevelopment/MMD-Dev-Server#306]
**Mod Name**: Literal Ascension

**Version**: 0.0.5.0

**Link to Updated JAR**: https://minecraft.curseforge.com/projects/literal-ascension/files/2342550

**Changelog (can be a link)**:
* Added carvable wood types from Biomes O' Plenty
* Added Stepladder types from Biomes O' Plenty
* Added carvable stone types from Environmental Tech

**Required Updated Dependency JAR Link(s)**: N/A

## This changes several block and item IDs. It should not affect the world very badly as most features are not used much on the server, but it's worth mentioning.

**Comment by Morpheus1101** [comment]
Im downloading a copy of the world so i can test what affect it will have on things, if its ok, we'll update, if it causes a lot of conflicts etc due to ID changes, we'll have to hold of untill next map reset unf.
