### ISSUE TITLE
Config Change: Reduce Spawn Frequency of p455w0rdsThings Endermen

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#307]
Endermen are great, five endermen standing outside my wall so I cannot sleep is not so great. Their spawning frequency seems a bit excessive and it is making sleeping a pain some days. Unlike normal mobs torches and fences and not even walls will keep them away.

So I request that the frequency be turned down a bit.

**Comment by p455w0rd** [comment]
changed
