### ISSUE TITLE
Mod Request: Random Things

### ISSUE THREAD

**Issue by lumien231** [MinecraftModDevelopment/MMD-Dev-Server#31]
Mod Name: Random Things
Mod Version: 3.7.5
Link To Download: [Curseforge](https://minecraft.curseforge.com/projects/random-things)

**Comment by Mattabase** [comment]
Super loving the additions to this mod in 1.10 Would love to put it through its paces.

**Comment by TheCodedOne** [comment]
I'd like to see this added too tbh

**Comment by EmoKiba** [comment]
I love random things but no blood moons

**Comment by lumien231** [comment]
Random Things doesn't have Bloodmoons in 1.10 :)
