### ISSUE TITLE
Mod Request: Qubble 

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [MinecraftModDevelopment/MMD-Dev-Server#310]
Mod Name: Statue and Qubble(if you want qubble)

Mod Version: 1.0.0

Link To Download: https://minecraft.curseforge.com/projects/qubble

Dependant Mods: 

If you're not the author of the mod you are requesting, why should this mod be added: This should be added because first, gegy is an MMD and his mod is new therefore I believe it is as important as any other mod to be tested, this mod is not just for modeling but also very much a decoration mod, if you make a model using qubble(which it is up to u to add) u can import it ingame and everyone will see it. 

So overall, this mod can be used for decoration in MMD, and qubble is just an addon to make custom decoration mobs or blocks! that you can indeed distribute if you want, also works great for us mod devs who want to play mmd while modeling!(lol)

**Comment by EPIICTHUNDERCAT** [comment]
0.1.2 qubble

**Comment by EPIICTHUNDERCAT** [comment]
i believe this requires LLibrary too, but i also think we have it already :P

**Comment by Morpheus1101** [comment]
Thumbs down

**Comment by EPIICTHUNDERCAT** [comment]
:( everyone voted down?

**Comment by EPIICTHUNDERCAT** [comment]
sad day

**Comment by EPIICTHUNDERCAT** [comment]
it does need testing tho, i had found a bug ...

**Comment by Morpheus1101** [comment]
I am but 1 of 3 ppl who can vote

**Comment by EPIICTHUNDERCAT** [comment]
okay, well for the 2 that are left, this mod is as valid as draconic evolution and cyberware. As my case before, this mod is a mod from someone in MMD, I also think that the mod needs some testing and I'm sure Gegy would agree, I rarely play on MMD, but I'm pushing this mod to be accepted, like I was Kanekas, because I don't think it will create any type of imbalance in the pack, as it is only a decoration mod. as of now. just know that I myself will be on the pack just to play with this mod too, because i think its a great decor mod, so much flexibility! I rest my case.. lol

**Comment by EPIICTHUNDERCAT** [comment]
An addition to my argument, The only mod we would actually need to add is Statue, i believe that Gegy said qubble is a client side mod, so if people want to use statue they can choose to make their own by adding qubble. if not statue can be used for normal MC mobs decor.

**Comment by darkhax** [comment]
I think this mod would be great to add. I have only seen screenshots but it seems to be a purely decorative thing, and I am all for that. Can't wait to play with it one the server ^^ (Unless password says no and crushes my dreams)

**Comment by EPIICTHUNDERCAT** [comment]
fantastic! YAY :D thank you guys!!!
