### ISSUE TITLE
Bug Report: Not Enough Wands: Capturing Wand Can Kill Mob Contained

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#312]
p455w0rd said to post this here:

If a Capturing Wand from Not Enough Wands, which contains a mob, is right clicked on a block the mob will spawn on top of that block inside any block on top of it causing it to suffocate. e.g. clicking the side of a wall with the wand will cause the mob to spawn inside that wall.

Expected behavior is that of vanilla spawn eggs with the mob being placed into the air block immediately next to the block clicked in relation to the side clicked. e.g. front clicked, mob spawns in front of the block; right clicked, mob spawns to right of block, etc.

MMD-dev-server specific: With the Chickens mod requiring chickens to be moved around and the Capturing Wand being one of the methods being used to do so and the expense and rarity of some of the chickens this may cause the loss of those chickens given they suffocate faster than a block can be broken to save them.

Reference: https://github.com/romelo333/notenoughwands/issues/36

**Comment by Morpheus1101** [comment]
This mod has had an update, but could you post it over @ https://github.com/romelo333/notenoughwands/issues
