### ISSUE TITLE
Mod Request: Dragon Tweaks

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#315]
Mod Name: Dragon tweaks (by Brandon3055 from Draconic)

Mod Version: 1.0.0

Link To Download: https://minecraft.curseforge.com/projects/dragon-tweaks

Dependant Mods: None

If you're not the author of the mod you are requesting, why should this mod be added:

This mod allows for the Dragon Egg to continually drop from each dragon thats killed

**Comment by EPIICTHUNDERCAT** [comment]
good idea :)

**Comment by p455w0rd** [comment]
is too OP-DENIED

**Comment by Morpheus1101** [comment]
rofl...i know right
