### ISSUE TITLE
Mod Request: Storage Drawers

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#317]
**Mod Name**: Storage Drawers

**Mod Version**: 1.10.2-3.4.2

**Link To Download**: https://mods.curse.com/mc-mods/minecraft/223852-storage-drawers

**Dependent Mods**: Chameleon https://minecraft.curseforge.com/projects/chameleon

**If you're not the author of the mod you are requesting, why should this mod be added**:
We have many storage solutions already but nothing in terms of single item storage other than Quantum Storage which is fine for super insane mass storage of a single resource like cobblestone but lacks a certain ease of use for manual access.

Some of the most inventive sorting systems I've seen have featured Barrels/JABBA/Storage Drawers, and the more inventive the system and the more involved it is the more chance for unique solutions that may reveal unique problems and bugs. I also would like a way to sort my Botania flowers on a wall.

**Comment by p455w0rd** [comment]
i say yes because we need something...this is rly the only decent solution even if not so resource friendly
