### ISSUE TITLE
Server Property Change Request: PVP

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [MinecraftModDevelopment/MMD-Dev-Server#319]
Hey guys, this is a request to basically turn PVP on. There is honestly no reason for it to be off in the first place since the server is whitelisted>no trolls, also a lot of mods have items that are meant to be PVP, so if people who would want to PVP each other they can, and test the items that aren't meant for PVP. Simple request, wouldn't hurt anyone to have it on.

**Comment by Aedda** [comment]
This would seem like a sensible thing for testing. As long as others respect each other and ask before engaging in pvp then I see no possible problem from it.

**Comment by EPIICTHUNDERCAT** [comment]
oh this got accepted :D

**Comment by Morpheus1101** [comment]
This will take effect after next reboot in 30min from now approx
