### ISSUE TITLE
Bug Report: ArmorPlus armor durability randomly changes, even into negative values

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#320]
Back in a previous server version, I think 2.1.1? My almost completely used Lava Armor from ArmorPlus restored itself to 90-95% durability. I had the armor stored in an Actually Additions Small Crate. I discussed with sokratis12GR this issue and he said it could not be the mod itself causing it.

Here is a screenshot of the randomly repaired armor: https://i.imgur.com/ocTBLMD.png

I moved the armor to a Vanilla chest to watch it for several days. Nothing happened. Last night before server update 2.1.11 I went out mob hunting , the armor was still 90-95% full on durability. I was only hit 9-10 times by skeleton arrows and a couple of zombies. When returning to base the armor was still at least 90% durability. I placed it back into the Vanilla chest and proceeded to do other things.

I went to bed and the server was updated to 2.1.11, when I went to put on my armor I found it in the following state, the three pieces I had used (chest, helm, and leggings were now worn out again), the chest piece being negative durability.

Screenshot of the chest piece: https://i.imgur.com/nAmD6pg.png

**Comment by sokratis12GR** [comment]
This is really strange because I couldn't manage to reproduce it, I tried everything and nothing happend

**Comment by Morpheus1101** [comment]
Aedda...is this bug still occuring with the updated vers?

**Comment by Aedda** [comment]
It isn't that sort of bug, it is impossible to say. The one armor piece is still negative durability but that wasn't the bug, the bug is the durability randomly changed twice after using it following updates to the mod and following config changes. Since that armor is almost busted there is no way to test it unless someone gives me a new set or the means to make a new set. The materials were gifted by @sokratis12GR the first time and are beyond my ability and desire to mine just for the purpose of trying to recreate the problem.

**Comment by Morpheus1101** [comment]
What armor set was it you require for testing?

**Comment by sokratis12GR** [comment]
Lava

**Comment by Aedda** [comment]
Ok, I'm calling this one not reproducible at this time. It is my belief the conditions to cause the issue happened in two stages following two different updates to the mod both affecting the durability or the way it is calculated/shown/stored. Reproducing it will probably require going back through previous versions to recreate the steps affecting the durability the first time. As such as long as the author does not alter the durability math again I don't see this issue reoccurring on its own.
