### ISSUE TITLE
Whitelist Request: A_Deathly_Touch

### ISSUE THREAD

**Issue by ADeathyTouch** [MinecraftModDevelopment/MMD-Dev-Server#321]
Minecraft IGN: A_Deathly_Touch

Discord Username: ADeathlyTouch

What you do (i.e streamer, mod developer, ect.): I am a Mod Developer (Tesla Essentials, Avionics), Modpack Developer (Avion), streamer (https://www.twitch.tv/a_deathly_touch), and YouTuber (https://www.youtube.com/channel/UCPbW25z576ZKY9KlPbt8flg).

**Comment by Morpheus1101** [comment]
You have been added to the whitelist

**Comment by ADeathyTouch** [comment]
Thank you.
