### ISSUE TITLE
Bug Report: Everlasting Abilities / Chickens mod / Not Enough Wands Capture Wand Interaction

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#324]
Not sure which mod this falls under.

Everlasting Abilities makes certain mobs drop a totem item. If a mob has this item a particle affect is shown over them.

If you capture a chicken from the ChickensMod which exhibits these particles and then release it using the wand often the particle effect is gone. After some testing I discovered that whether or not they contained a totem changed each time they entered and exited the wand. By continuously capturing and releasing the same chicken eventually the particles appeared.

I killed a number of chickens in both states to verify that the totems indeed dropped or failed to drop in accordance with that.

References:
https://github.com/romelo333/notenoughwands1.8.8/issues/14

**Comment by Morpheus1101** [comment]
To cover both bases, id drop a line of this over on NotEnoughWands and see what mcjty has to say .. wouldnt surprise me if this is ultimately an issue with the Chickens Mod

**Comment by Aedda** [comment]
I also tested the Capturing Wand on few Villagers and on some their Title in WAILA changed, for instance from Leatherworker to Butcher. However their actual trade and texture did not change. Also their title did not change in The Other Probe, nor in their actual trade window.

**Comment by Morpheus1101** [comment]
Chicken Mod part of this we can no longer test, but the NEW issue is still there an so far no response form mod Author

**Comment by Morpheus1101** [comment]
Im going to close this issue for now, th emod author hasnt responded in nearly a mnth, so at this stage im not expecting a resolution anytime soon.
