### ISSUE TITLE
Mod Removal Request: Chickens Mod

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#325]
This was mostly added to aid in the Awakend Draconium gathering, but for the mass amount of chickens youd need, since there drop rate is extremely limited in time and dropping a nugget, makes this impractical for further use, especially with mysitcal Agriculture.

**Comment by Aedda** [comment]
Having experimented with Chickens Mod myself I can only completely agree with its removal. It appears impossible currently to use this mod for any point of gain without severely crippling the server.
