### ISSUE TITLE
Bug report : ae2 stuff or drconic evolution 

### ISSUE THREAD

**Issue by juryjr** [MinecraftModDevelopment/MMD-Dev-Server#329]
If you brake a ae2 stuff item with a drconic  staff the item  is destroyed

**Comment by Morpheus1101** [comment]
I'll talk to brandon about this and see what he sais

**Comment by brandon3055** [comment]
Is this on AOE mode, 1x1 mode or both?

**Comment by brandon3055** [comment]
Is this on AOE mode, 1x1 mode or both?

**Comment by brandon3055** [comment]
Is this on AOE mode, 1x1 mode or both?

**Comment by Morpheus1101** [comment]
We need to know what exact block you were trying to break as i have tried all the usual AE2 items one would have for making an ME system using a draconic staf of power an they all return to my inv
Same using AE2stuff(the mod) items

**Comment by juryjr** [comment]
Not from ae2 from ae2 stuff mod it was doing it with the advanced  inscriber I'm sorry I didn't think about how it looked when I posted it

**Comment by juryjr** [comment]
As I can't recreation it and it's not happining anymore I'm guessing  it was due to how fast I brake blocks I do have max haste and server lag at the time I'm there closing the issue
