### ISSUE TITLE
Whitelist request

### ISSUE THREAD

**Issue by Rushmead** [MinecraftModDevelopment/MMD-Dev-Server#33]
Minecraft IGN:Rushmead

Discord Username:Rushmead

What you do (i.e streamer, mod developer, ect.): Streamer, Mod Developer(Some Times), other stuff.

**Comment by p455w0rd** [comment]
oooo..dunno bout this one

**Comment by TheCodedOne** [comment]
We're going to hold off on whitelisting anyone who doesnt have a mod on the server or a request for their mod to be added to the server to give devs the opportunity to apply. We will accept more non-dev apps at a later date.
