### ISSUE TITLE
Bug Report: EnderIO Powered Spawner occasionally spawning 0.5 blocks outside range

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#330]
It appears that EnderIO Powered Spawners sometimes spawn a mob slightly outside the displayed range. This occurs on the West and North directions.

Steps to reproduce:

1. Place spawner
2. Display spawning range
3. Build 2 high wall around range
4. Power spawner
5. Wait

After a period of time, sometimes up to an hour, or as little as every couple minutes a mob will appear half on the West or North wall, and half inside the intended range.

West wall: https://i.imgur.com/0Sxy1xd.png

North wall: https://i.imgur.com/cHpC42n.png

After more testing: https://i.imgur.com/Xv8lJqe.png

**Comment by p455w0rd** [comment]
are you positive this isn't vanilla?..i don't see any torches up there in the screenshots

**Comment by Morpheus1101** [comment]
ive been using these spawners quite fine and so long as u build a wall 1 block outside the spawn range it sais for each mob, they dont spawn outside.

**Comment by Aedda** [comment]
With torches: https://i.imgur.com/5J2wBXe.png

I used tick rate changer to accelerate the testing, actual time before spawning would have been 2 minutes.

**Comment by Aedda** [comment]
This has been reported to the authors tracker by @Mysteryem and has been marked as code-complete by the author and the fix has been committed.

References:
https://github.com/SleepyTrousers/EnderIO/issues/3849

**Comment by Morpheus1101** [comment]
Code to fix this has been done, now just waiting on a new release of EnderIO

**Comment by Morpheus1101** [comment]
There is a new vers of EIO out .. could u test this and see if the issue is fixed

**Comment by Morpheus1101** [comment]
There is a new vers of EIO out .. could u test this and see if the issue is fixed

**Comment by Aedda** [comment]
I ran a 200 irl day simulation and the mobs never appeared outside their intended area so assuming this has been fixed.
