### ISSUE TITLE
Whitelist request

### ISSUE THREAD

**Issue by vengpjer** [MinecraftModDevelopment/MMD-Dev-Server#34]
Minecraft IGN: vengpjer

Discord Username: veng

What you do (i.e streamer, mod developer, ect.): Just a normal citizen, but I have been playing minecraft for more than six years now and I have a lot of experience in modded. This is why I would love to take part in testing and exploring new mods

**Comment by TheCodedOne** [comment]
We're going to hold off on whitelisting non-devs to give devs the opportunity to apply. We will accept more non-dev apps at a later date.
