### ISSUE TITLE
MMD v3.0 Mod Vote: Botania

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#341]

**Comment by Aedda** [comment]
I initially abstained but I've decided I'm sick of redoing and redesigning my "flower factory" every time the author decides something needs a nerf and will no longer work that way.

**Comment by TheCodedOne** [comment]
kill it with fire

**Comment by darkhax** [comment]
I thought we were waiting 3 days before rejecting a mod?

**Comment by TheCodedOne** [comment]
Its 5 aparently.

**Comment by Morpheus1101** [comment]
There is no way this will make it, 3 yes 10 no ... thats basically the entire user base...its guranteed to not make it.
