### ISSUE TITLE
MMD v3.0 Mod Vote: ChanceCubes

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#343]

**Comment by Aedda** [comment]
I'll change my vote to positive if 1) a policy is established for the safe and timely removal of cubes in unwanted places, and 2) if the most destructive risks are removed, massive explosions, withers, etc. as they have the potential for unintended foolishness overflowing onto those who want no involvement.

**Comment by EmoKiba** [comment]
as long as they are not in world spawn and not craftable i will gladly upvote this

**Comment by Morpheus1101** [comment]
After now having it in the "wild" so to speaki dont overly find them worth of any use, so im not apposed to having them for Streamers only

**Comment by darkhax** [comment]
I am against having them spawn naturally as well, or at least lowering their spawn rates.

**Comment by srs-bsns** [comment]
I agree with @darkhax, if they stay, their spawn rate needs to be lowered substantially. When I first joined the server after I was whitelisted, I had a nether star and some OP equipment in <20 minutes of gameplay... I felt like I was cheating.  :astonished:

**Comment by Morpheus1101** [comment]
This will go back to being for Streamers who request them.
