### ISSUE TITLE
Mod Request: Refined Storage

### ISSUE THREAD

**Issue by raoulvdberge** [MinecraftModDevelopment/MMD-Dev-Server#36]
Mod Name: Refined Storage

Mod Version: 0.9.4 

Link To Download: https://minecraft.curseforge.com/projects/refined-storage/files/2326651

Dependant Mods: MCMultiPart

**Comment by p455w0rd** [comment]
already on the server :)

**Comment by raoulvdberge** [comment]
Ah, in that case your modlist is out of date :P

**Comment by battery3996** [comment]
what really need and no need to hurt anybodys feelings but we would kinda want applied energistics more

**Comment by TheCodedOne** [comment]
@battery3996 i dont know if you noticed, but RS is a mod that needs testing, and AE isnt for 1.10
