### ISSUE TITLE
MMD v3.0 Mod Vote: Geographicraft

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#363]

**Comment by srs-bsns** [comment]
Just a reminder, GeographiCraft is required if using both RTG and Biomes O' Plenty together, else the world will not have BoP biomes.
Since GeographiCraft has a slight bias towards worlds with a lot of ocean some of the time, it is still recommended to set `B:SeparateLandmasses` to `false`.

**Comment by Morpheus1101** [comment]
This is on hold pending if BOP makes it in, since this addon is based upon adding BOP biomes in with RTG
