### ISSUE TITLE
Whitelist request

### ISSUE THREAD

**Issue by MrBurd** [MinecraftModDevelopment/MMD-Dev-Server#37]
Minecraft IGN: Snateraar

Discord Username: MrBurd

What you do (i.e streamer, mod developer, ect.): I'm terrific at breaking mods. Let's just say once you combine everything with everything, eventually stuff starts breaking.
I also make mod textures/models, so for those of you in need of textures; hi :)

**Comment by TheCodedOne** [comment]
We're going to hold off on whitelisting anyone who doesnt have a mod on the server to give devs the opportunity to apply. We will accept more non-dev apps at a later date.
