### ISSUE TITLE
Whitelist request for droidicus

### ISSUE THREAD

**Issue by droidicus** [MinecraftModDevelopment/MMD-Dev-Server#39]
Minecraft IGN: droidicus1

Discord Username: droidicus

What you do (i.e streamer, mod developer, ect.): Experienced Modded MC player, experienced tester, willing to break things and report issues to mod devs.

**Comment by TheCodedOne** [comment]
We're going to hold off on whitelisting anyone who doesnt have a mod on the server to give devs the opportunity to apply. We will accept more non-dev apps at a later date.
