### ISSUE TITLE
MMD v3.0 Mod Vote: VarietyTrees

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#402]

**Comment by cleverpanda** [comment]
As far as testing goes, I longer need it to be on the server, and it doesn't make much sense gameplay wise with BOP or forestry.

**Comment by srs-bsns** [comment]
If this mod adds/modifies trees to biome decoration, it would be nice to make sure it plays nice with RTG.

**Comment by Morpheus1101** [comment]
we're currently using it on the dev server with RTG :D

**Comment by srs-bsns** [comment]
Yes, but new chunks aren't generated very often, so continuing to use this mod along with RTG provides more thorough testing, and thorough testing is better than less testing. :)

Besides, who hates tree?

**Comment by Morpheus1101** [comment]
I've gone into new un-generated chunks after this was added with RTG an had no issues that ive noticed
