### ISSUE TITLE
MMD Dev Server Whitelist  KAT

### ISSUE THREAD

**Issue by juryjr** [MinecraftModDevelopment/MMD-Dev-Server#407]
Minecraft IGN:Helofor

Discord Username: KAT

What you do (i.e streamer, mod developer, ect.): would like to become a dev server tester

**Comment by p455w0rd** [comment]
Being a tester means reporting bugs as you find them. Being that she isn't willing to even create a github account (a requirement to be able to report bugs), I doubt she would have any motivation to report bugs. From what she said, she just wants tot play minecraft. We have a public server for that.

**Comment by Morpheus1101** [comment]
Please feel free to use our Public MMD Server Pack from https://minecraft.curseforge.com/projects/mmd-project-ultimate
