### ISSUE TITLE
MMD v3.0 Mod Vote: Embers

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [MinecraftModDevelopment/MMD-Dev-Server#409]
why was this not included.

**Comment by Morpheus1101** [comment]
An oversight

**Comment by Morpheus1101** [comment]
https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TEMPLATE.md

**Comment by EPIICTHUNDERCAT** [comment]
follow your own rules morpheus
