### ISSUE TITLE
Mod Request: RecStat

### ISSUE THREAD

**Issue by iTitus** [MinecraftModDevelopment/MMD-Dev-Server#41]
Mod Name: RecStat

Mod Version (newest as of the creation of this issue): 1.10.2-2.2.2

Link To Download: [CurseForge](https://minecraft.curseforge.com/projects/recstat)

Reasoning (although I made it): I would like another server for extensive testing and feedback. The functionality of the mod can also be very useful.

**Comment by battery3996** [comment]
I would have to say this use for those who are live streamers or youtubers.
