### ISSUE TITLE
MMD v3.0 Mod Vote: TombmanyGraves

### ISSUE THREAD

**Issue by juryjr** [MinecraftModDevelopment/MMD-Dev-Server#410]

**Comment by TheCodedOne** [comment]
https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TEMPLATE.md

**Comment by juryjr** [comment]
Coded why didn't u dot this to rock candy or embers

**Comment by Morpheus1101** [comment]
This on hold untill voting for which specific Gravestone Mod players are wanting

**Comment by Morpheus1101** [comment]
KeepInventory has won the choice by the users.
