### ISSUE TITLE
Config Change Request: Perfect Spawn

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#413]
Some effort has been make to secure new and unfortunate players returning to world spawn. However while walls have been constructed on our structure a roof cannot be, the player is spawning on top of it.

I understand we have Perfect Spawn, according to the description the X Z and Y can be set. As well as setting the spawn point to be exact. I think we have few enough respawning members that the collisions at spawn point will be no issue for the server.

I would like the Perfect Spawn config changed to reflect the following:
```
{
   "spawnDimension": 0,
   "spawnX": -56,
   "spawnY": 79,
   "spawnZ": -72,
   "exactSpawn": true,
   "forceBed": true,
   "spawnProtection": false
}
```

This shouldn't even require a server restart.

**Comment by srs-bsns** [comment]
`"spawnDimension": 1,`

That is not the Overworld

**Comment by Aedda** [comment]
Thank you, that was a royal screw up, fixed!

**Comment by TheCodedOne** [comment]
srs ffs, i was gonna wait for it to get accepted and make everyone spawn in the end :(

**Comment by juryjr** [comment]
RIGHT CODED

**Comment by Morpheus1101** [comment]
Far as i know we arent using this mod nor do i recall seeing a mod request for it.....unless ive missed something

**Comment by TheCodedOne** [comment]
@Morpheus1101 #82

**Comment by darkhax** [comment]
With the server reset coming up soon, does this even matter?

**Comment by TheCodedOne** [comment]
Not really for this map @darkhax , but the same issue will be had next map, so why not fix it at the very start
