### ISSUE TITLE
MMD v3.0 Mod Vote: Growable Cells

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftModDevelopment/MMD-Dev-Server#415]
https://minecraft.curseforge.com/projects/growable-storage-cells

This is a good idea.  I mean, we already have mystical agriculture, so whatever.

**Comment by EPIICTHUNDERCAT** [comment]
I WANTS IT

**Comment by darkhax** [comment]
I think we should abandon AE2 and move to refined storage. (which is an MMD mod in need of testing which is kind of the point of this server).

**Comment by Morpheus1101** [comment]
i c no reason why both cant be on the server

**Comment by Morpheus1101** [comment]
i c no reason why both cant be on the server, im just no in favour of this particular addition to it.

**Comment by EPIICTHUNDERCAT** [comment]
I can't say I agree, i think we should have both actually, mainly because there are many add-on mods(like this one) that would need testing i think having both would be okay for that reason.
