### ISSUE TITLE
Whitelist Application: MrTrollNugnug

### ISSUE THREAD

**Issue by MrTrollNugNug** [MinecraftModDevelopment/MMD-Dev-Server#417]
Minecraft IGN: MrTrollNugnug

Discord Username: Cazsius

What you do (i.e streamer, mod developer, ect.): I am currently a mod developer on the texture and coding end. I am fairly good at texturing simpler scale items and I am learning at a faster than slower pace to develop more complex mods.

**Comment by Morpheus1101** [comment]
What mods have you done textures & coding for?

**Comment by MrTrollNugNug** [comment]
https://minecraft.curseforge.com/members/MrTrollNugNug/projects This is the best resource for that. I coded on all mods and have done most of the item textures for ArkCraft. P.S. All SBM mods I am on, I am only porting them to newer versions. The rest I code for new content on.
