### ISSUE TITLE
Bug Report: p455w0rd's things Jetpack and Jetplate break inventory while flying

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#419]
If one is actively flying using either the Carbon Jet Pack or Emerald Infused Carbon Jetplate it becomes impossible to click the inventory, move items, etc. Landing resolves the issue, which reoccurs as soon as one is flying again. Tested this against two other creative-style flight items and nether had the same problem.

Assuming this was intended to prevent removing the jetpack while flying but somehow blocked the rest of the inventory too.

**Comment by p455w0rd** [comment]
it's a "feature"

**Comment by p455w0rd** [comment]
XD fixing now :)

**Comment by darkhax** [comment]
Did you also fix that issue where taking off the jetpack doesn't completely remove flight? The other night we had 3 or so people all flying using only one jet pack.
