### ISSUE TITLE
Bug Report: Mystical Agriculture Supremium armor breaks flying

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#420]
If one is wearing any piece of Mystical Agriculture armor then all flying ability triggered by double-space is broken. Removing the piece of armor allows normal flight again. It does not break real-creative-mode flight however.

**Comment by EPIICTHUNDERCAT** [comment]
this is true

**Comment by Morpheus1101** [comment]
Supremium Armor set gives you flight ability, so id say its intended with how those pieces r done to why it breaks other flight.  I Shall pass it along and see what the modder sais to get around this.

**Comment by Morpheus1101** [comment]
https://minecraft.curseforge.com/projects/mystical-agriculture/issues/28

**Comment by Aedda** [comment]
The problem is all 4 pieces are required for flight however any 1 piece disables flight by other means.

**Comment by Aedda** [comment]
Additional: Equipping any piece while flying immediately cancels flight.

**Comment by Morpheus1101** [comment]
The author was going to "see" what they could do, im not sure if they can/will being its a side effect of having to require an entire piece
