### ISSUE TITLE
Config Change Request: Not Enough Wands

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#421]
Could the maximum capacity of the Building Wand be increased say ten fold? It uses a lot of power due to its nature and having to charge it (for the whole 1 second it needs to be full) every minute is getting a bit tedious.

**Comment by Morpheus1101** [comment]
isnt there a builders wand thats unbreakable and dosent require rf at all ?

**Comment by Aedda** [comment]
I think it needs a nether star, which isn't exactly a problem however I don't think it builds nearly as well as the Building Wand. I will test both to be certain.

**Comment by Aedda** [comment]
Ok, the diamond one may work for my purposes. I'll reopen this if I run into a limitation with that.

**Comment by Aedda** [comment]
Reopening, the Diamond Better Builder's wand is nice but the NEW Building Wand is a bit more intuitive and requires much less mode switching to get the job done.

**Comment by Morpheus1101** [comment]
This will be changed in v3 from 64k to 640k
