### ISSUE TITLE
Mod Request: Parallel

### ISSUE THREAD

**Issue by RogueLogic** [MinecraftModDevelopment/MMD-Dev-Server#422]
Mod Name: Parallel

Mod Version: 0.0.0

Link To Download: https://minecraft.curseforge.com/projects/parallel

Dependent Mods: None

If you're not the author of the mod you are requesting, why should this mod be added: author. requesting now for long term stability test.

If the mod is not currently hosted anywhere, please give a brief description of the mod: multi-threading library.

**Comment by TheCodedOne** [comment]
If this mod doesnt actually do anything by itself, it cant really be tested :/
