### ISSUE TITLE
Mod Request: (3.0) Mob Farm

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftModDevelopment/MMD-Dev-Server#423]
Mod Name: Mob Farm

Mod Version: 0.0.1

Link To Download: https://minecraft.curseforge.com/projects/mob-farm/files/2348149

Dependent Mods: none

If you're not the author of the mod you are requesting, why should this mod be added: Author.  Could use server balance/viability testing, perhaps lag testing in large scales.

**Comment by Morpheus1101** [comment]
I say no due to having heard from quite a few players from the Public server that was using this mod and it causing massive amounts of tps issues and lag on the server.
