### ISSUE TITLE
Whitelist Application: abused_master

### ISSUE THREAD

**Issue by abused** [MinecraftModDevelopment/MMD-Dev-Server#424]
Minecraft IGN: abused_master

Discord Username: abused_master

What you do (i.e streamer, mod developer, ect.): Mod Developer

**Comment by Morpheus1101** [comment]
What mod/s have u devaloped?

**Comment by abused** [comment]
At the moment the ones listed here https://minecraft.curseforge.com/members/abused_master/projects
and im working on a new tech mod as we speak, https://github.com/abused/Tech-Expansion
