### ISSUE TITLE
Mod Request: Fluxed Redstone

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#425]
Mod Name: Fluxed Redstone

Mod Version: 2.5.0.51

Link To Download: https://mods.curse.com/mc-mods/minecraft/240484-fluxed-redstone

Dependant Mods: RebornCore

If you're not the author of the mod you are requesting, why should this mod be added: This adds various cables that are able to transfer larger amounts of power than what we currently have available

**Comment by darkhax** [comment]
It also supports Tesla so 👍
