### ISSUE TITLE
Whitelist Request: DoodleFungus

### ISSUE THREAD

**Issue by Gaelan** [MinecraftModDevelopment/MMD-Dev-Server#426]
IGN: DoodleFungus

Discord: Gaelan#0424

What you do: I'm a developer, though not for Minecraft. I can read a stack trace and get a pretty good idea of what went wrong. I'd like to apply as a play tester. I might also get around to making MCubed someday.

EDIT: I'm also on a lower-end computer, so I will be able to file issues for fixable performance bugs that others don't run into.

**Comment by Morpheus1101** [comment]
Are you familiar with modded minecraft?

**Comment by Gaelan** [comment]
From a technical perspective (installing packs, running them, etc) no problem. I don't know a lot of mods super well, but I can figure things out by myself.
