### ISSUE TITLE
MMD V3.0 Mod list as @ 03.12.16

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#428]
**_ADDED:_**

AE2
ActuallyAdditions
AE2Stuff
ArmorPlus
Arsmagica2
BadWitherNoCookie _(Client Side Only)_
Bagginses
Basemetals
BetterBuildersWands
Big Fusion
Bloodmagic
BOP
ChanceCubes _(Streamers Only If Requested)_
ChickenChunks
Chisel
CraftTweaker
Cyberware
DarkUtilities
DeepResonance
DraconicEvolution
DragonTweaks
EnderIO
EnderStorage
EnderUtilities
EnvironMentaltech
EviLCraft
ExtremeReactors
FastleafDecay
Forestry
Gendustry
GeographiCraft
GravestoneMod  _(On hold untill vote for which of the 2 Gravestone mods is most wanted)_
GYTH
ImmersiveEngineering
IronBackpacks
IronChests
JEI
Journeymap
LiteralAscension
Morpheus
NaturesGift
NetherMetals
NotEnoughWands
OreDictionaryConverter
OreSpawn
P455w0rdsthings
Plasmids
QuantunStorage
Reliquary
rftools
rftoolsctrl
rftoolsdim
roguelikedungeons
roots
RTG
TinkersConstruct
TrashSlot
Teslafied
TinkersTollleveling
UniDict
UpDownAndAllAround
Veinminer
Vitality
Waila
RockCandy
Embers
TombManyGraves _(On Hold Untill Vote for which Gravestone Mod is wanted has finished)_
BetterAgriculture
Modularity27
GrowableCells
EnchancedProgression
RedstoneFluxArsenal
MobFarm

**_Removed Since v2_**

Botania
ElementalDimensions
EverlastingAbilities
IntergratedDynamics
MoreChickens
MysticalAgrictulture
OpenComputers
PSI
Statue
TheOneProbe
Translocators
VarietyTrees
WorldControl
Chickens

**Comment by EPIICTHUNDERCAT** [comment]
and embers cus i think u forgot.
