### ISSUE TITLE
Slow down lawnmower grass growth

### ISSUE THREAD

**Issue by TheCodedOne** [MinecraftModDevelopment/MMD-Dev-Server#43]
it seems to grow way too fast

**Comment by SeqSEE** [comment]
Maybe even just add it to a config?

**Comment by TheCodedOne** [comment]
it is in a config @SeqSEE im just making an issue to see if people want/dont want it slowed down.

**Comment by Morpheus1101** [comment]
Yes, it does seem to grow ridiculously fast

**Comment by SeqSEE** [comment]
@TheCodedOne Haha, oh okay. :p
A way to adjust the config value in game would be helpful then?

**Comment by p455w0rd** [comment]
Also, I would say maybe have to use something like grass seeds or something to define the area where the grass re-grows. Our area is screwed. Now I gotta hire a lawn crew.
