### ISSUE TITLE
Bug Report: p455w0rd's Things colored item names not Vanilla anvil compatible

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#430]
If you place any armor item from p455w0rd's Things into a Vanilla anvil and that item has a colored name the anvil will display that the enchantment cost is 1 and offer the item as output. The output name is changed from the Green "Item Name Here" to a generic White name saying "aoItem Name Here".

This issue also affects Actually Additions armor pieces but not Mystical Agriculture armor pieces which retain their colored names.

ETA: Placing the armor items into an Enchanting Plus enchanting table does not alter the item name.

**Comment by p455w0rd** [comment]
ah, didn't think about this..easy enough to fix..when I have time I'll fix it :)
