### ISSUE TITLE
Bug Information Collection: Boats crashing

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#433]
If you are experiencing boats crashing when placed please comment below, also please feel free to ask your own questions if you think their answers may help figure out the conditions of this randomly occurring bug.

What time of day was it: Morning, Noonish, Evening, Night

Do you know if hostile mobs were present near by?

Is so do you know if they were zombies?

Were the hostile mobs in water or on land or both?

Were you standing in the water on a solid surface when you spawned the boat?

Were you swimming in water when you spawned the boat?

Were you standing on land when you spawned the boat?

Where were you when you tried placing the boat (be as specific or as unspecific as you feel comfortable with, but please at least your quadrant if willing e.g. -X+Z)

Were you wearing armor when the crash occurred?

Will update this with more questions as I think of them.

**Comment by Aedda** [comment]
Evening, mobs had just started spawning.
Hostile mobs were present near by.
There were zombies, not sure what kind.
They were swimming towards me.
I was swimming when I spawned the boat.
Not sure my location I was on the run, but I may be able to figure it out later.
I was not wearing armor.

**Comment by Morpheus1101** [comment]
Closing this for now untill other instances of this issue pop up and we can re-open.
