### ISSUE TITLE
Whitelist Request: Aeronica 

### ISSUE THREAD

**Issue by Aeronica** [MinecraftModDevelopment/MMD-Dev-Server#434]
# MMD Dev Server Whitelist Template

**Minecraft IGN**: Aeronica

**Discord Username**: Aeronica / Rymor

**What you do** (*i.e streamer, mod developer, ect.*): mod developer for mxTune

**Comment by Morpheus1101** [comment]
Id like you to please go over https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/whitelist/TERMS.md and indicate in here to if you Agree or Disagree with the terms put forth plz.

**Comment by Aeronica** [comment]
I agree to the terms set forth in the agreement indicated.

**Comment by Morpheus1101** [comment]
Please make sure your in our General Discord Chat Channel Please
