### ISSUE TITLE
Mod Request: mxTune 

### ISSUE THREAD

**Issue by Aeronica** [MinecraftModDevelopment/MMD-Dev-Server#435]
# Mod Update Template

**Mod Name**: mxTune

**Version**: mxtune-1.10.2-0.3.1.0-dev.9

**Link to Updated JAR**: [mxtune-1.10.2-0.3.1.0-dev.9 - jar](https://minecraft.curseforge.com/projects/mxtune/files/2349510/download)

**Changelog (can be a link)**: [mxtune-1.10.2-0.3.1.0-dev.9 - change log](https://minecraft.curseforge.com/projects/mxtune/files/2349510)

**Required Updated Dependency JAR Link(s)**: n/a

**Comment by Morpheus1101** [comment]
Could you use the below template for the request of this mod plz:

Mod Name:

Mod Version:

Link To Download:

Dependant Mods:

If you're not the author of the mod you are requesting, why should this mod be added:

If the mod is not currently hosted anywhere, please give a brief decription of the mod:

**Comment by Aeronica** [comment]
Mod Name: mxTune

Mod Version: 0.3.1.0-dev.9

Link To Download: https://minecraft.curseforge.com/projects/mxtune/files/2349510/download

Dependant Mods:

**Comment by Morpheus1101** [comment]
Looking over this mod, i feel its an individual standalone mod that has no interaction with other mods and as such cant really see this being tested other than by those who wish to use such a method of music listening.

**Comment by Aeronica** [comment]
I disagree. The mod is not a music player per se. It also allows player to group up and play together. It has features such as whitelisting. I want to test that with other players online. That is difficult to test locally or on my own test server. I need players online to I can move them into lists, check to see they are saved correctly. Yes I have tested extensively on my own, but in general not in the presence of other mods and with other players present.

**Comment by Aedda** [comment]
I'd like to point out if not obvious that @Aeronica is the author of this mod and is therefore requesting the addition of their own mod, if that makes a difference in the consideration.

Also I've personally tried this recently in an existing pack and it was unable to load the soundbank for the instruments saying there were either too many mods or not enough memory, that pack had fewer mods than we use, and I tried giving the pack an additional 10gb of memory in ~3gb increments. Reporting this issue however got buried under other things.

**Comment by Aeronica** [comment]
Thank you for reminding me Aedda. That is also an Issue I need to resolve. I added some error messages to warn the users, but I have not spent enough time working on this problem. At this point it could be a mod conflict. mxTune relies heavily on javax.sound.midi.*, and com.sun.media.sound.AudioSynthesizer. I don't really have a good handle on the memory requirements or it's behaviour on memory or competition for resources. Sound runs in it's own thread, and mxTune also has a small thread pool for the MML audio chain. 

The mod is not an MP3 type of player for MML notation. This is Social/RPG/Adventure mod that allows player to perform their musical scores for each other in solo or group sessions. I have not worked on progression or other aspect that MML could provide. Such as magical instruments/tunes that can heal a party, or harm near by mobs. Musical blocks that can be used to add a local theme, or background music, or be triggered by redstone. I;'ve even considered Tesla energy to power a the instruments of ROCK band.  All ideas of course, but the basis of supporting any of this is a solid reliable audio subsystem and play mechanics.

**Comment by p455w0rd** [comment]
I would be all for it if it didn't have the aforementioned bug still. With our dev packs using on average ~5GB before GC, I don't think this is a good idea at all. If you fix the memory issues come back back and I'll give it a thumbs up.

**Comment by Aedda** [comment]
I'm not sure it actually uses a lot of memory, rather it just seems to act oddly under certain circumstances and then complains it doesn't have enough.

**Comment by Aeronica** [comment]
At this point I'm going to update to the mod for 1,11. I'm not going to push this at the moment. Thanks for your consideration all.
