### ISSUE TITLE
Whitelist Request: SwodoBaggins

### ISSUE THREAD

**Issue by swodobaggins** [MinecraftModDevelopment/MMD-Dev-Server#436]
Minecraft IGN: SwodoBaggins

Discord Username: .Swodo

What you do (i.e streamer, mod developer, ect.): Student, kind of get started with mods and lose inspiration, game dev for silly little RPG that I've recently started.

**Comment by Morpheus1101** [comment]
Id like you to please go over https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/whitelist/TERMS.md and indicate in here to if you Agree or Disagree with the terms put forth plz.
