### ISSUE TITLE
Update Request: Vitality

### ISSUE THREAD

**Issue by raphydaphy** [MinecraftModDevelopment/MMD-Dev-Server#438]
**Mod Name:** Enhanced Progression

**Version:** 1.2.0 (or whatever is latest when you read this)

**Link to Updated JAR:**https://minecraft.curseforge.com/projects/vitality latest file there

**Changelog (can be a link):** https://gist.github.com/raphydaphy/b1f3a2a623f0be6b10b9a70406361db4

**Required Updated Dependency JAR Link(s)**: um none 😄 

Also heres a kitten because aparently kittens are good 🐈

**Comment by Morpheus1101** [comment]
Has this project been moved//deleted ?

**Comment by Growlith1223** [comment]
https://minecraft.curseforge.com/projects/vitality i believe it's this now

**Comment by raphydaphy** [comment]
Yea oops sorry that's the new link

**Comment by Morpheus1101** [comment]
lol, had my thoroughly confused :D
