### ISSUE TITLE
Whitelist Request: Kashdeya

### ISSUE THREAD

**Issue by Kashdeya** [MinecraftModDevelopment/MMD-Dev-Server#439]
Minecraft IGN:Kashdeya

Discord Username:Kashdeya

What you do (i.e streamer, mod developer, ect.):Mod Developer and Modpack Creator.

**Comment by Morpheus1101** [comment]
Id like you to please go over https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/whitelist/TERMS.md and indicate in here to if you Agree or Disagree with the terms put forth plz

**Comment by Kashdeya** [comment]
Agree

**Comment by Morpheus1101** [comment]
Please Make sure you have joined and are in our Discord Channel
