### ISSUE TITLE
Whitelist request:Jonharn

### ISSUE THREAD

**Issue by jonharn** [MinecraftModDevelopment/MMD-Dev-Server#440]
Minecraft IGN: Jonharn

Discord Username: Jonharn

What you do (i.e streamer, mod developer, ect.): I am streamer that streams at https://www.twitch.tv/jonharngaming. I also play on a whitelisted beta testing server for the modpack unstoppable. I have been playing minecraft for multiple years (5+/-).

**Comment by Morpheus1101** [comment]
Id like you to please go over https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/whitelist/TERMS.md and indicate in here to if you Agree or Disagree with the terms put forth plz.

**Comment by jonharn** [comment]
I agree with the terms put forth. 
Its fine if i'm not allowed to but i guess i am not allowed to record or stream on the server.

**Comment by darkhax** [comment]
That is not what the terms are refering to. There are certain mods on the current V3 version of the pack which are not released to the public, such as official ports of CoFH stuff. You can have these things in videos, screenshots and streams however they are not allowed to be the focus of such things. For example, posting a screenshot bragging about how you have access to X mod is not okay. Making a mod spotlight on a released mod is also an example of something that would not be okay.

**Comment by jonharn** [comment]
Ok just double checking I agree to that and the terms

**Comment by Morpheus1101** [comment]
Please make sure your in our General discord Channel
