### ISSUE TITLE
Mod Request: Bed Bug Buster

### ISSUE THREAD

**Issue by gr8pefish** [MinecraftModDevelopment/MMD-Dev-Server#442]
Mod Name: Bed Bugs ~~Buster~~

~~[CurseForge link](https://minecraft.curseforge.com/projects/bed-bug-buster/)~~
New link, as the page/mod name changed: [CurseForge link](https://minecraft.curseforge.com/projects/bed-bugs/)

Tiny mod. Provides a fix to the vanilla bug of getting stuck in a bed. As I couldn't replicate the issue myself, some more testing is needed, hence this request 👌

I don't mind if it's just added in v3 to make your lives easier (assuming that's not *too* far away).

**Comment by darkhax** [comment]
If this fixes bed bug issues, I am all for it.

**Comment by gr8pefish** [comment]
Yeah, I mean that's the entire idea behind it :P

Looks like it [does work](https://www.reddit.com/r/feedthebeast/comments/5g7m3s/i_made_a_small_110_mod_to_help_players_getting/daq6xa3/) as well.

**Comment by Morpheus1101** [comment]
Ohh im so behind it  100% that bed bug is beyond annoying for everyone and i can only hope this fixes the issue

**Comment by p455w0rd** [comment]
i guess my CMD has been tested and it works just fine, so in order to actually test this, I suppose we should allow it on the server :/

**Comment by gr8pefish** [comment]
I overhauled the mod from the first time I posted this, the button is fancier, it is totally unobtrusive unless you actually get stuck now. Also added a command for it.

**Comment by knoxhack** [comment]
thanks for this mod 👍 adding it to Project Ultimate

**Comment by Aedda** [comment]
I still feel this is a conspiracy by @p455w0rd to get his CMD updated since as soon as it was I stopped having the bed glitch. Also his face is blue and as everyone knows the color blue is supposed to be calming but what exactly is he calming us about? Beds are red, he is blue, and Mojang isn't even a color. None of it makes any sense.

In any case I'm up for giving it a go.
