### ISSUE TITLE
[1.10.2] TrashSlot Dosent Show when using HandyBag from Enderutilities

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#444]
![2016-12-04_14 05 20](https://cloud.githubusercontent.com/assets/10524952/20864005/dc891094-ba2a-11e6-9749-6f627c325a49.png)

https://github.com/blay09/TrashSlot/issues/27

**Comment by Aedda** [comment]
Handy Bags override the standard inventory GUI to display the extra features. You will notice also absent are the Baubles button. Sneak activating the player inventory displays the vanilla inventory GUI and thus the missing buttons. However the author Ender Utilities may be able to add in support on their GUI for both of these.

**Comment by Morpheus1101** [comment]
Unf(so im told) this cant be fixed in 1.10.2, but it is in 1.11 of TrashSlot
