### ISSUE TITLE
Mod Request: Extra Utilities2

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#446]
Mod Name: Extra Utilities

Mod Version: Extra Utilities2 1.10.2-1.1.1

Link To Download: https://minecraft.curseforge.com/projects/extra-utilities/files

Dependant Mods: none

This has the various xfer nodes which would be super handy as well as beginner generators etc for power, compressed cobblestone(who dosent want a way to compress it) and so many more great features thatd be super fun to play with

**Comment by p455w0rd** [comment]
it is super buggy..if you want proof..just check how many rollbacks jax macky has had to do in the past 2 days on his treams

**Comment by Morpheus1101** [comment]
Welp if its still buggy then screw having it on MMD sadly

**Comment by darkhax** [comment]
It's not as buggy as Pass makes it sound, however it does have its issues. I would prefer to limit bugged mods to ones in the mmd community.

**Comment by p455w0rd** [comment]
it is that buggy dark..the pipes specifically..and being that pipes are probably the most used thing in ExU2..i'd say it's srsly buggy
