### ISSUE TITLE
[1.10.2] VarieyTree's preventing Apples Dropping from Oak tree's

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#447]
After spending a good 10-20min chopping down oak tree's i didn't get a Single Apple Drop, while this isnt overly a bad thing Apples are needed for use with DraconicEvolution upgrades, Evil Craft & ActuallyAdditions, ironically Also needed for Apple seeds from VT as well :D

**Comment by Aedda** [comment]
Can confirm. I set up a test involving 251 Oak Trees. Those trees consisted of 18083 leaf blocks. When the logs were removed 576 Acorns dropped (an average of 2.29 acorns per tree, this also seems low), no apples.

It appears the only way to obtain apples is via apple seeds from apples from apple trees. Do these even spawn in the world? I've never seen one. Also I am sure apples were dropping before.

**Comment by Morpheus1101** [comment]
I spoke with cleverpanda and it is intended behaviour, although im not sure as to the frequency of Apple tree's, but i cant say as to there existence as ive not seen one myself

**Comment by cleverpanda** [comment]
Apples trees have an 8% of generating an any biome that is or extends BiomeForest per chunk. I had personally checked to be sure this works on the server, and found some apple trees. However, I do recognize that BOP reduces the amount it generates, and I'm adding BOP support and a config option to remove apple trees and the removal of apples from oaks to adjust for different play styles.
