### ISSUE TITLE
Whitelist Request: Growlith1223

### ISSUE THREAD

**Issue by Growlith1223** [MinecraftModDevelopment/MMD-Dev-Server#449]
Minecraft IGN: Growlith1223

Discord Username: Growlith1223

What you do (i.e streamer, mod developer, ect.): general programmer and mod developer

I do agree to the Terms of Play as well.

I was messaged a couple weeks ago about my port of Ars Magica getting added to a server and was invited to the discord lol, figured i could apply to the server as well

**Comment by Morpheus1101** [comment]
Please make sure your in our Discord Channel

**Comment by Growlith1223** [comment]
I am in the discord channel
