### ISSUE TITLE
Mod Request: Natures Gift

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [MinecraftModDevelopment/MMD-Dev-Server#45]
Mod Name: Natures Gift

Mod Version:0.6

Link To Download:
https://minecraft.curseforge.com/projects/natures-gift?gameCategorySlug=mc-mods&projectID=247291
Dependant Mods:
None
If you're not the author of the mod you are requesting, why should this mod be added: I am, I want my mod to be added so that I can receive feedback on what I have and what should be worked on, and even suggestions on what should be added in the near future.

**Comment by jriwanek** [comment]
Don't close the issue @EPIICTHUNDERCAT, makes it harder for them to keep track of the todo list.

**Comment by knoxhack** [comment]
This can be closed tho. The mod is already on the server
