### ISSUE TITLE
Mod Request: Cyclic

### ISSUE THREAD

**Issue by PrinceOfAmber** [MinecraftModDevelopment/MMD-Dev-Server#450]
Mod Name: Cyclic

Mod Version: 1.8.4

Link To Download: https://minecraft.curseforge.com/projects/cyclic

Dependant Mods: (optional: Baubles)

If you're not the author of the mod you are requesting, why should this mod be added:

If the mod is not currently hosted anywhere, please give a brief decription of the mod:

**Comment by EmoKiba** [comment]
Dis Mod is Amazing Ask Epiic we need it on MMD Dev v3 Plz
