### ISSUE TITLE
Whitelist Request: Lothrazar

### ISSUE THREAD

**Issue by PrinceOfAmber** [MinecraftModDevelopment/MMD-Dev-Server#451]
Minecraft IGN: Lothrazar

Discord Username: Lothrazar

What you do (i.e streamer, mod developer, ect.): Mod dev of Cyclic and others

 I agree to the terms set forth in the MMD Dev Server's Terms of Play

**Comment by Morpheus1101** [comment]
Please make sure your in our Discord Channel and i look fwd to looking at your mod :D
