### ISSUE TITLE
Whitelist Request: GiorgioBrux

### ISSUE THREAD

**Issue by GiorgioBrux** [MinecraftModDevelopment/MMD-Dev-Server#452]
Minecraft IGN: GiorgioBrux

Discord Username: GiorgioBrux

What you do (i.e streamer, mod developer, ect.): Modpack Creator.

I agree to the terms set forth in the MMD Dev Server's Terms of Play

**Comment by Morpheus1101** [comment]
What modpack have you created and could you share a link with us plz?

**Comment by GiorgioBrux** [comment]
Sorry for the delay of my answer.

I'm created modpack with my friend named QuantMint that uploaded them on technic launcher.
You can see our first modpack here that is like a test modpack.

>>>http://www.technicpack.net/modpack/the-galacticraft-pack-addon.843335
>Don't sure if you can still download it because we "abandoned" it.

You can see our new and fresh modpack updated 3 days ago here:

>>>http://www.technicpack.net/modpack/techasda.928226

It is actually in beta and some important part that we would like to use (like quest system) are missing because we're working for implement solder api (http://docs.solder.io/) in our vps.

I and my friend are also creating an adventure modpack but it is in embryonic state and far of releasing it.

P.S if you cannot download second modpack from launcher you can download and try it from here:

>>>https://www.dropbox.com/s/w0hkyvjrs7qnc3w/modpack.zip?dl=0

**Yours sincerely.**
