### ISSUE TITLE
MMD V3.0 Mod list as @ 12.12.16

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#453]
cyclic(by Lothrazar)
Ars Magica(Growlith1223)
Bed Bugs(gr8pefish)
Roots (by elucent)
Just Enough Items (JEI) (by mezz)
Bagginses (by lorddusk)
LunatriusCore (by Lunatrius)
Applied Energistics 2 (by AlgorithmX2)
LLibrary (by iLexiconn)
Gendustry (by bdew)
Mantle (by mDiyo)
Mystical Agriculture (by BlakeBr0)
WanionLib (by WanionCane)
Brandon's Core (by brandon3055)
HelpFixer (by matthewprenger)
BdLib (by bdew)
Morpheus (by Quetzi)
Tinkers' Tool Leveling (by bonusboni)
QuantumStorage (by Gigabit1011)
Iron Backpacks (by gr8pefish)
Wawla - What Are We Looking At (by darkh4x)
Teslafied (by TheRealp455w0rd)
Chisel (by tterrag1098)
p455w0rd's Things (by TheRealp455w0rd)
Practical Plasmids (by EmoKiba)
Nether Metals (by knoxhack)
ZeroCore (by ZeroNoRyouki)
MMD OreSpawn (by jriwanek)
AutoRegLib (by Vazkii)
Guide-API (by TehNut)
TheDragonLib (by Moritz30)
Bookshelf (by darkh4x)
Get Ya' Tanks Here (by darkh4x)
RFTools Dimensions (by McJty)
CodeChicken Lib 1.8.+ (by covers1624)
Actually Additions (by Ellpeck)
Forestry (by SirSengir)
RFTools Control (by McJty)
Reliquary v1.3 (by P3pp3rF1y)
Roguelike Dungeons (by Greymerk)
ArmorPlus (by Moritz30)
Better Builder's Wands (by Portablejim)
OreDictionaryConverter (by EXTER7)
Light Level Overlay Reloaded (by oldjunyi)
UniDict (by WanionCane)
Immersive Engineering (by BluSunrize)
JourneyMap (by techbrew)
VeinMiner (by Portablejim)
Iron Chests (by progwml6)
Not Enough Wands (by romelo333)
Literal Ascension (by JamiesWhiteShirt)
CraftTweaker (by jaredlll08)
RFTools (by McJty)
TESLA (by darkh4x)
AE2 Stuff (by bdew)
Shadowfacts' Forgelin (by shadowfactsmc)
TrashSlot (by BlayTheNinth)
Biomes O' Plenty (by Glitchfiend)
ValkyrieLib (by ValkyrieofNight)
Chicken Chunks 1.8.+ (by covers1624)
Tinkers Construct (by mDiyo)
RebornCore (by modmuss50)
CodeChicken Core 1.8.+ (by covers1624)
Climate Control (by Zeno410)
Bad Wither No Cookie! (by droidicus)
Realistic Terrain Generation (by WhichOnesPink)
Inventory Tweaks (by Kobata)
Waila (by ProfMobius)
Storage Drawers (by jaquadro)
Chameleon (by jaquadro)
Blood Magic (by WayofTime)
Chance Cubes (by turkey2349)
InGame Info XML (by Lunatrius)
MCMultiPart (by amadornes)
Embers (by elucent)
EnderCore (by tterrag1098)
FastLeafDecay (by Olafskii)
Extreme Reactors (by ZeroNoRyouki)
EvilCraft (by kroeser)
Ender IO (by CrazyPants_MC)
ElecCore | Rendering Library (by Elec332)
Dragon Tweaks (by brandon3055)
Ender Utilities (by masa_)
Cyclops Core (by kroeser)
Environmental Tech (by ValkyrieofNight)
Ender Storage 1.8.+ (by covers1624)
Draconic Evolution (by brandon3055)
Cyberware (by stuntrally)
Deep Resonance (by McJty)
Dark Utilities (by darkh4x)
Enchanting Plus (by darkh4x)
Base Metals (by jriwanek)
CompatLayer (by McJty)
McJtyLib (by McJty)
Rock Candy (by EmoKiba)
Better Agriculture (by knoxhack)
Growable Storage Cells (by ShadowsOfFire)
Redstone Flux Arsenal (by knoxhack)
Mob Farm (by ShadowsOfFire)
Fluxed Redstone (by modmuss50)
Progressive Automation (by VanhalMinecraft)
Vitality (by raphydaphy)
CoFHCore(by KingLemming, Covers1624)
ThermalFoundation(by KingLemming, Covers1624)

![mmd v3 modlist](https://cloud.githubusercontent.com/assets/10524952/21142088/3a358304-c18c-11e6-9054-1be4a3f6da61.png)

**Comment by Growlith1223** [comment]
nooo, no ars magica! kidding, that's a lot of mods though yo!

**Comment by EmoKiba** [comment]
wait we decided no ars magica

**Comment by Growlith1223** [comment]
i was kidding, and that's more or less understandable xD

**Comment by knoxhack** [comment]
Wasnt it accepted? https://github.com/MinecraftModDevelopment/MMD-Dev-Server/issues/432

**Comment by Growlith1223** [comment]
honestly, i wouldn't be surprised if it was removed last minute, the mod may be playable(and, so far i've fixed most of the crashes), but it's still wip

**Comment by Morpheus1101** [comment]
This was redone to keep it on top of the list
