### ISSUE TITLE
Mod Request: Test Mod Please Ignore

### ISSUE THREAD

**Issue by tkdberger** [MinecraftModDevelopment/MMD-Dev-Server#455]
**Mod Name**: Test Mod Please Ignore

**Mod Version**: The first version with fully working survival content should be `0.0.6-gamma` for 1.11. Currently the next release is `0.0.5-gamma` for 1.11

**Link To Download**: https://minecraft.curseforge.com/projects/test-mod-please-ignore

**Dependant Mods**: [Baubles v 1.4.2 or later](https://minecraft.curseforge.com/projects/baubles)

**Comment by Morpheus1101** [comment]
Could you plz provide a 1.10.2 vers if this 1.11 vers dosent work on 1.10.2

**Comment by tkdberger** [comment]
Actually, I haven't tried to run the 1.11 version in 1.10.2

I'll give that a shot later today. Who knows, maybe we'll get luck

**Comment by Morpheus1101** [comment]
Using the current version in curse, this loads in a server instance, so id say its safe that with the compat thing from mcjty it'll work fine.

**Comment by tkdberger** [comment]
It'll work with CompatLayer, but I don't intend to backport.
