### ISSUE TITLE
[1.10.2] Vitality: Error with coal oredict name

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#458]
Vitality adds dustCoal to the oredict of coal causing the EnderIO sagmill to grind coal into coal and not coal into coal dust

https://github.com/raphydaphy/Vitality/issues/4

**Comment by Mysteryem** [comment]
Smelting logs also gives you coal rather than charcoal.

**Comment by raphydaphy** [comment]
its fixed now lol i was on holiday :(
