### ISSUE TITLE
Whitelist Request

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [MinecraftModDevelopment/MMD-Dev-Server#46]
Minecraft IGN: EPIIC_THUNDERCAT

Discord Username: EPIIC_THUNDERCAT

What you do (i.e streamer, mod developer, ect.): 
Mod Developer, developing Natures Gift, and Thundercats, also part dev on SeqSee's SWAT mod :)

**Comment by knoxhack** [comment]
Mod developer confirmed.
Added iTitus to the whitelist
