### ISSUE TITLE
Mod Request: remove Waila, add Hwyla

### ISSUE THREAD

**Issue by srs-bsns** [MinecraftModDevelopment/MMD-Dev-Server#461]
**Mod Name**: Hwyla

**Mod Version**: 1.8.1-B13_1.10.2

**Link To Download**: https://minecraft.curseforge.com/projects/hwyla/files/2344352

**Dependant Mods**: N/A

**If you're not the author of the mod you are requesting, why should this mod be added**: The pack currently has Waila-1.7.0-B3_1.9.4.jar, which is very old and suffers from a display bug that shows the wrong blockstate in the Waila in-world tooltip (calls getDefaultState() instead of passing the correct blockstate). This bug has been known for quite a long time. TehNut's fork (Hwyla) fixes this issue, as well as some other things.

Note: This uses the same mod ID as Waila (in fact, the only difference is the jar name, and the config), so it should just work out-of-the-box as if it were Waila. The config is moved from `config/waila.cfg` to `config/waila/waila.cfg`, and there are a few additions, but nothing of consequence. Here's a config diff: https://gist.github.com/srs-bsns/737327ea52afc28f8410910417ae3f12

Waila:
![waila](https://cloud.githubusercontent.com/assets/8453133/21393937/9b271ec4-c764-11e6-980d-b0d6b1bdfd5a.png)

Hwyla:
![hwyla](https://cloud.githubusercontent.com/assets/8453133/21393945/a077886e-c764-11e6-8c88-92a28a2f9be4.png)

**Comment by Aedda** [comment]
I would have to concur. While this is a testing server for the purpose of finding bugs it does no good when updates are over six months apart. It has been 7 months since the last update as is.

**Comment by Morpheus1101** [comment]
I concur a lot of issues are in waila which the maintainer works at mojang now, so after spending all day I would concur that a switch is due, esp due to the period of time between updates.

**Comment by EmoKiba** [comment]
#TOP is superior

**Comment by Morpheus1101** [comment]
What drugs r u on kiba?
