### ISSUE TITLE
Mod Request: Wither Skeleton Fixer

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftModDevelopment/MMD-Dev-Server#464]
Mod Name: Wither Skeleton Fixer

Mod Version: 1

Link To Download: https://minecraft.curseforge.com/projects/wither-skeleton-fixer

If you're not the author of the mod you are requesting, why should this mod be added: I own it

If the mod is not currently hosted anywhere, please give a brief decription of the mod: Its on curse

Fresh off the gradlew.

**Comment by Morpheus1101** [comment]
Could u include everything from the template for a mod request plz shadow :D

**Comment by Shadows-of-Fire** [comment]
there u go but idk why you wanted those.

**Comment by Morpheus1101** [comment]
lol, whats it fix with the wither skel ?

**Comment by Shadows-of-Fire** [comment]
if (this.worldObj.provider instanceof WorldProviderHell && this.getRNG().nextInt(5) > 0)
The fact that vanilla uses RNG to decide if skeletons in the nether are wither.
