### ISSUE TITLE
Mod Update Request: UpAndDownAndAllAround v2.4

### ISSUE THREAD

**Issue by Mysteryem** [MinecraftModDevelopment/MMD-Dev-Server#467]
Mod Name: UpAndDownAndAllAround 

Version: 2.4

Link to Updated JAR: https://github.com/Mysteryem/Up_And_Down_And_All_Around/releases/download/v2.4/UpAndDownAndAllAround-2.4.jar

Changelog (can be a link): https://github.com/Mysteryem/Up_And_Down_And_All_Around/releases/tag/v2.4

Required Updated Dependency JAR Link(s): None

**Comment by Morpheus1101** [comment]
Has there been any further updates to this mod since 2.4 ?

**Comment by Mysteryem** [comment]
No, though I'm preparing for a 2.5 release later today/tomorrow morning.

**Comment by Morpheus1101** [comment]
awesome stuff

**Comment by Mysteryem** [comment]
v2.5 https://minecraft.curseforge.com/projects/up-and-down-and-all-around/files/2374421/download
or https://github.com/Mysteryem/Up_And_Down_And_All_Around/releases/tag/v2.5 (also has changelog)

It's also no longer an 'experimental' project, so you should be able to get it straight from the Curse Launcher.

https://minecraft.curseforge.com/projects/up-and-down-and-all-around
