### ISSUE TITLE
Mod Update Req: Growable Cells (0.0.1 -> 0.1.0)

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftModDevelopment/MMD-Dev-Server#469]
Mod Name: Growable Cells

Version: 0.1.0

Link to Updated JAR: https://minecraft.curseforge.com/projects/growable-storage-cells/files/2360867

Changelog (can be a link): https://minecraft.curseforge.com/projects/growable-storage-cells/files/2360867

Required Updated Dependency JAR Link(s): n/a

**Comment by Shadows-of-Fire** [comment]
I would say hold up to 0.2.0 but we don't have RS so updating to GC 0.2.0 would be pointless now wouldn't it.

**Comment by Morpheus1101** [comment]
RS ?

**Comment by Shadows-of-Fire** [comment]
Refined Storage

**Comment by Morpheus1101** [comment]
Yes, the mod was voted down by the Community for use in v3
