### ISSUE TITLE
Whitelist Request: DarkS_0

### ISSUE THREAD

**Issue by DarkShadow07** [MinecraftModDevelopment/MMD-Dev-Server#474]
Minecraft IGN: DarkS_

Discord Username: DarkS_0#3523

What you do (i.e streamer, mod developer, ect.): I make mods for minecraft, only released one.

 I agree to the terms set forth in the MMD Dev Server's Terms of Play

**Comment by Morpheus1101** [comment]
What mod have u released ?

**Comment by DarkShadow07** [comment]
I've made IRC Mod http://i.imgur.com/RQP1HRq.png, I know LapisSea

**Comment by Morpheus1101** [comment]
While your interest in MMD and its Dev Server is appreciated we cannot in good faith approve of your whitelist application at this time. We hope that this does not discourage you from your endeavors and hope to still see you as a general member of MMD.
