### ISSUE TITLE
Whitelist Request: InsomniaKitten

### ISSUE THREAD

**Issue by InsomniaKitten** [MinecraftModDevelopment/MMD-Dev-Server#475]
**Minecraft IGN**: InsomniaKitten

**Discord Username**: InsomniaKitten#0833

**What I do**: I'm texture/graphics artist and mod developer

**I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md).**

**Comment by Morpheus1101** [comment]
What mod/s have u devaloped?

**Comment by InsomniaKitten** [comment]
All of my current WIP mods are unreleased; I make a decoration mod called Model Village, and an advanced lighting solution mod called Ambient Illumination - feel free to look at my repos although they're not up-to-date as of posting this.

I spend most of my 'work' hours texturing rather than coding. I've contributed to the Unity resource pack, Fancy Fluid Storage, and have pending textures for MattDahEpic's Exchange Orb mod currently. Other mods are planned for texture work although I prefer not to disclose until details are confirmed on my end.

**Comment by Morpheus1101** [comment]
Could you plz make a Gitlab  username and let me know what it is plz.

**Comment by InsomniaKitten** [comment]
**GitLab:** [@InsomniaKitten](https://gitlab.com/InsomniaKitten)

**Comment by Morpheus1101** [comment]
Ok, you've now been added to Gitlab and have access to download the MMD-Dev Server pack
