### ISSUE TITLE
Whitelist Request: RebelKeithy

### ISSUE THREAD

**Issue by RebelKeithy** [MinecraftModDevelopment/MMD-Dev-Server#478]
# MMD Dev Server Whitelist Template

**Minecraft IGN**: RebelKeithy

**Discord Username**: RebelKeithy

**What you do**: Modder, I worked on Metallurgy 2 & 3, Aquaculture, Atum and several other mods in the past. I've gotten back into modding after about 2 years, my current released mods are DualHotbars and Deep Pockets.

**How did you hear about MMD** (*i.e existing user, facebook etc.*): FTB reddit

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
Could you make a Gitlab username please and let me know what it is.

**Comment by RebelKeithy** [comment]
I just made an acount, name is RebelKeithy

**Comment by Morpheus1101** [comment]
You have been added to Gitlab https://gitlab.com/MinecraftModDevelopment/MMD-Dev-Server
