### ISSUE TITLE
Whitelist Request

### ISSUE THREAD

**Issue by Lomeli12** [MinecraftModDevelopment/MMD-Dev-Server#48]
Minecraft IGN: Lomeli12
Discord Username: Lomeli12
What you do (i.e streamer, mod developer, ect.): [Mod Developer](https://minecraft.curseforge.com/members/Lomeli12/projects)

**Comment by p455w0rd** [comment]
What mod do you wish to have added to the server for testing?

**Comment by Lomeli12** [comment]
LomLib, which I'm nearly finished on its 1.10 port, and another mod that relies on LomLib which I'm not ready to publicly disclose, but is working in SP and I would like to test in a SMP environment.

**Comment by knoxhack** [comment]
Mod developer confirmed.
Added Lomeli12 to the whitelist
