### ISSUE TITLE
Bug Report: JourneyMap Bookmark coords shifting/changing when enabling Nether display

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#488]
This issue causes the coords in bookmarks to change from their originally set point.

Steps to reproduce the problem:

1) Make bookmarks in Overworld
2) Travel to Nether
3) Edit each bookmark, Enable Nether in dimension list.
4) Return to Overworld
5) Bookmarks will now be shifted from their original sites.

Example:
These bookmarks were originally centered on each Nether Portal: [https://i.imgur.com/EOTxNh4.png](https://i.imgur.com/EOTxNh4.png)

References:
https://bitbucket.org/TeamJM/journeymap/issues/165/bookmark-coords-shifting-changing-when

**Comment by Morpheus1101** [comment]
Is this issue still occuring?

**Comment by Aedda** [comment]
Still happening as of the latest version 5.4.6
