### ISSUE TITLE
Whitelist Request

### ISSUE THREAD

**Issue by ADSKILLER** [MinecraftModDevelopment/MMD-Dev-Server#49]
Minecraft IGN: ADSKILLER

Discord Username: ADSKILLER

What you do (i.e streamer, mod developer, ect.): Tester

**Comment by TheCodedOne** [comment]
We're going to hold off on whitelisting anyone who doesnt have a mod on the server to give devs the opportunity to apply. We will accept more non-dev apps at a later date.

**Comment by p455w0rd** [comment]
@ADSKILLER are you still interested in being whitelisted?
