### ISSUE TITLE
Bug Report: Rope-Bridge may randomly break /help

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#495]
As reported by HelpFixer, Rope-Bridge incorrectly overrides compareTo() on 2 help commands. Most likely returning a default of 0 rather than the actual compare result.

```[05:00:08] [Server thread/WARN]  [com.matthewprenger.helpfixer.HelpFixer]: Command [ropebridge, com.mrtrollnugnug.ropebridge.RopeBridgeCommand] incorrectly overrides compareTo: %s```
```[05:00:08] [Server thread/WARN]  [com.matthewprenger.helpfixer.HelpFixer]: Command [ropebridge, com.mrtrollnugnug.ropebridge.RopeBridgeCommand] incorrectly overrides compareTo: %s```

References:
https://github.com/MrTrollNugNug/Rope-Bridge/issues/1

**Comment by Morpheus1101** [comment]
Has been fixed apparently by having the command removed in updated vers

**Comment by Aedda** [comment]
It is fixed in source but has not been released. The latest release 1.4.0 was just prior to the fix and HelpFixer still reports the problem as present.

**Comment by Aedda** [comment]
Appears fixed as of 2.0.0
