### ISSUE TITLE
Mod Request: Ender IO

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#496]
**Mod Name:** Ender IO

**Mod Version:** 1.10.2-3.1.156

**Link To Download:** https://minecraft.curseforge.com/projects/ender-io/files/2362703

**Dependent Mods:** EnderCore (https://minecraft.curseforge.com/projects/endercore/files/2370656)

**If you're not the author of the mod you are requesting, why should this mod be added:** Because doing something that should be as bloody simple as power from A to B is a pain and is counterproductive to our purpose here. If there is already an alternative to Mekanism in this pack, or available, **that requires our testing** then point that out, otherwise we need EIO.

**If the mod is not currently hosted anywhere, please give a brief description of the mod:** n/a

**Comment by knoxhack** [comment]
Flux Network is a good alternative for simple power transfer. https://minecraft.curseforge.com/projects/flux-networks

**Comment by Morpheus1101** [comment]
We also all ready have the cables from Fluxed Redstone mod
