### ISSUE TITLE
Mod Update Request: RTG

### ISSUE THREAD

**Issue by srs-bsns** [MinecraftModDevelopment/MMD-Dev-Server#498]
Mod Name: RTG
Version: 4.1.2.3
Link to Updated JAR: https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/download/v1.10.2-4.1.2.3/RTG-1.10.2-4.1.2.3.jar
Changelog (can be a link): https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/tag/v1.10.2-4.1.2.3

This is basically the same as the dev version currently on the server, but this is the release proper.

**Comment by srs-bsns** [comment]
4.1.2.4 will be out later today.. I had to fix a bug, though it has 0 effect on the dev server, but may as well wait for it anyways.

**Comment by Morpheus1101** [comment]
okies :)

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/download/v1.10.2-4.1.2.4/RTG-1.10.2-4.1.2.4.jar
