### ISSUE TITLE
Whitelist Request

### ISSUE THREAD

**Issue by Rongmario** [MinecraftModDevelopment/MMD-Dev-Server#50]
Minecraft IGN: Rongmario

Discord Username: Rongmario

What you do (i.e streamer, mod developer, ect.): I am a streaming + mod developer, I create video content from time to time but mostly create mods in the 1.4-1.7.10 era, thinking of coming back and this would be a great opportunity. Also, I would be starting to create mods if this server looks like a great test environment, thank you! I am also a certified modder on FTB forums if that helps.

**Comment by jriwanek** [comment]
Don't forget to join the MMD discord!
