### ISSUE TITLE
Whitelist Request: BookerTheGeek

### ISSUE THREAD

**Issue by bookerthegeek** [MinecraftModDevelopment/MMD-Dev-Server#503]
Minecraft IGN: BookerTheGeek
Discord Username: BookerTheGeek
What you do: I play minecraft and report bugs.
How did you hear about MMD: Discord
- [X] I agree to the terms set forth in the MMD Dev Server's Terms of Play

>I `BookerTheGeek` acknowledge and agree to the terms set forth in the Terms of Play, as stated in the new TERMS.md file and my GITLAB username is `BookerTheGeek`

**Comment by Morpheus1101** [comment]
Please join our Discord channel @ http://discord.mcmoddev.com/
