### ISSUE TITLE
Bug Report: Electric Advantage / Power Advantage Conflict Involving Transformers

### ISSUE THREAD

**Issue by Aedda** [MinecraftModDevelopment/MMD-Dev-Server#505]
If you put an Electric-RF Transformer from Power Advantage in the circuit of a Battery Array from Electric Advantage the battery capacity thrashes between a discharged and charged state. I've observed both 0 and 100%, and 50% and 100%. Further if you connect an RF using machine or device then to the transformer it seems to get random RF between 0 and 8rf/t

Steps to reproduce:
1) Place Battery Array
2) Insert Battery (I used an 8K) one
3) Place an Electric-RF Transformer next to Battery Array
4) Observe battery spaz out

**Comment by Morpheus1101** [comment]
Mod is under going a massive re-write
