### ISSUE TITLE
Mod Request: Utility Base Ores

### ISSUE THREAD

**Issue by knoxhack** [MinecraftModDevelopment/MMD-Dev-Server#506]
Mod Name: Utility Base Ores

Mod Version: 1.10.2-1.0

Link To Download: 
https://minecraft.curseforge.com/projects/utility-base-ores

Dependent Mods: MMD Orespawn
https://minecraft.curseforge.com/projects/mmd-orespawn

If you're not the author of the mod you are requesting, why should this mod be added: 
My new mod that just released in need of testing.
You can disable any ore that you dont want from the configs

If the mod is not currently hosted anywhere, please give a brief description of the mod: n/a

**Comment by Aedda** [comment]
This looks like a fun alternative for those who love to mine but hate fighting mobs and gives some food to munch on. OPness would depend on how frequently it spawns.
