### ISSUE TITLE
Whitelist Request: Poke_b

### ISSUE THREAD

**Issue by pokeba** [MinecraftModDevelopment/MMD-Dev-Server#508]
**Minecraft IGN**: Poke_b

**Discord Username**: Poke#1650

**What you do** : Developer of TimeCore and XP-Plus but also a player ;)

**How did you hear about MMD** : From Discord

- [X] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
Please join our Community Discord Channel http://discord.mcmoddev.com/
