### ISSUE TITLE
Mod Request: McJty's Mods

### ISSUE THREAD

**Issue by McJty** [MinecraftModDevelopment/MMD-Dev-Server#51]
Mod Name: RFTools
=====================================
Mod Version: 5.21
Download: https://minecraft.curseforge.com/projects/rftools
Dependencies: McJtyLib: https://minecraft.curseforge.com/projects/mcjtylib
I'm the author

Mod Name: RFTools Dimensions
=====================================
Mod Version: 4.30beta48
Download: https://minecraft.curseforge.com/projects/rftools-dimensions
Dependencies: McJtyLib: https://minecraft.curseforge.com/projects/mcjtylib

Mod Name: Deep Resonance
=====================================
Mod Version: 1.2.2
Download: https://minecraft.curseforge.com/projects/deep-resonance
Dependencies:
McJtyLib: https://minecraft.curseforge.com/projects/mcjtylib
ElecCore: https://minecraft.curseforge.com/projects/eleccore-rendering-library

Mod Name: The One Probe
=====================================
Mod Version: 1.2.2
Download: https://minecraft.curseforge.com/projects/the-one-probe
Dependencies: none

Mod Name: RF Lux
=====================================
Mod Version: 0.0.1
Download: https://minecraft.curseforge.com/projects/rf-lux
Dependencies: McJtyLib: https://minecraft.curseforge.com/projects/mcjtylib
I'm the co-author. The author is my son romelo333

Mod Name: Not Enough Wands
=====================================
Mod Version: 1.3.6
Download: https://minecraft.curseforge.com/projects/not-enough-wands
Dependencies: none
I'm the co-author. The author is my son romelo333

**Comment by battery3996** [comment]
add this pls

**Comment by EmoKiba** [comment]
the RF dimensions would help for new ore and fresh chunk generation

**Comment by Mattabase** [comment]
Would love having his mods <3

**Comment by p455w0rd** [comment]
I feel almost as strongly about these as I do about DE...they should be added

**Comment by EPIICTHUNDERCAT** [comment]
agreed, should be added 100%
