### ISSUE TITLE
Mod Request: M.E.T.A.

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#510]
Mod Name: M.E.T.A.

Mod Version: v1.0 for Forge 1.11.2

Link To Download: https://minecraft.curseforge.com/projects/m-e-t-a/files/2389272

Dependant Mods: None

If you're not the author of the mod you are requesting, why should this mod be added: I would like to test with the community and ensure the mod is stable.

If the mod is not currently hosted anywhere, please give a brief decription of the mod:  Adds a generator creating energy from mod ideas.

**Comment by Morpheus1101** [comment]
At this stage we are using 1.10.2 and will be a couple months or so, before we look at using 1.11.x  If your still needing testing then, please be sure to re-comment on this request.

**Comment by MasterEric** [comment]
I've been thinking about backporting the mod to 1.10.2 using the [CompatLayer library](https://minecraft.curseforge.com/projects/compatlayer), would you use it then?

**Comment by Morpheus1101** [comment]
If its on 1.10.2 and meets required votes, then yes :)

**Comment by MasterEric** [comment]
Version 1.1 has been released, adding CompatLayer as a dependency and creating a single JAR file compatible with both 1.10 and 1.11.
https://minecraft.curseforge.com/projects/m-e-t-a/files/2389610
