### ISSUE TITLE
Whitelist Request: John_Boanerges

### ISSUE THREAD

**Issue by JohnBoahnerges** [MinecraftModDevelopment/MMD-Dev-Server#512]
Minecraft IGN: John_Boanerges

Discord Username: John#3704

What you do (i.e streamer, mod developer, ect.): Modpack developer, along as a youtuber

How did you hear about MMD (i.e existing user, facebook etc.): MyM discord server

- [x] I agree to the terms set forth in the MMD Dev Server's Terms of Play

**Comment by Morpheus1101** [comment]
What modpack do you devalop and your youtubes channel link plz ?

**Comment by JohnBoahnerges** [comment]
Sorry, i've not been home. Our team develops, Mystical Survival. My youtube channel is small, but I try. https://www.youtube.com/channel/UCRwVkCJH4G3w2xdh3nmjTMg

**Comment by JohnBoahnerges** [comment]
I normally live stream too, those don't normally go up on my channel

**Comment by JohnBoahnerges** [comment]
**Discord for my modpack** https://discord.gg/TUeQPwG

**Comment by Morpheus1101** [comment]
Please join our Discord @ http://discord.mcmoddev.com/

**Comment by JohnBoahnerges** [comment]
I'm part of that already

**Comment by JohnBoahnerges** [comment]
The names John
