### ISSUE TITLE
Bug Report: Base Metals - Obsidian Ingots

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#514]
Smelting Redstone Dust in any furnace results in Obsidian Ingots, an item with no texture whose uses include other items with no texture.

**Comment by Morpheus1101** [comment]
This is a known issue and on the list to be fixed.

**Comment by Morpheus1101** [comment]
UPDATE: Artistry work is still in the works for this issue and others, but has not been forgotten

**Comment by Morpheus1101** [comment]
Update: This has been reported as now fixed and will be tested in Next update
