### ISSUE TITLE
Server Config Issue: Vein Miner and ProjectRed

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#515]
ProjectRed's tools are not in the server's config for Vein Miner, and as such cannot be used for vein mining.

This is not a bug with the mod itself, unless it is intended to automatically detect this mod.

**Comment by Morpheus1101** [comment]
So this is actually more of a request for PR tools to be added into the config list of VeinMiner

**Comment by Morpheus1101** [comment]
ruby, sapphire & peridot items have been configured and will be included in the next update

**Comment by Morpheus1101** [comment]
Doing an update now, which will have this.
