### ISSUE TITLE
Bug Report: Colossal Chests + Inventory Tweaks Interaction

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#516]
Attempting to use Inventory Tweaks buttons in a Colossal Chest results in a chat message:
`InvTweaks: [ERROR][3] Failed to sort container: null (l101 in HandlerSorting.java)`
Items in the Colossal Chest are not moved or modified.

**Comment by Morpheus1101** [comment]
The mod author for Inv tweaks has explicitly said they wont ever support being able to use its mod in conjuction with Colossal Chests, a sad fact that a few other mod makers have also said.
