### ISSUE TITLE
Bug Report: Block Update Detector Behavior

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#518]
The Block Update Detector from Dark Utilities breaks when a liquid flows over it, like a torch does, even though it is a full sized block.

**Comment by Morpheus1101** [comment]
https://github.com/Darkhax-Minecraft/Dark-Utilities/issues/56

**Comment by Morpheus1101** [comment]
This has been marked as fixed on the Bug Report for the mod
