### ISSUE TITLE
Mod Request: OreDictionaryConverter

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#519]
Mod Name: OreDictionaryConverter

Mod Version: 1.9.1

Link To Download: https://minecraft.curseforge.com/projects/oredictionaryconverter

Dependant Mods: None

If you're not the author of the mod you are requesting, why should this mod be added: This is less of a "I'd like this tested" and more of a "I need this to not pull my hair out." Since this is not a polished pack, multiple of the same ore and ingot exist, and thus I have trouble dealing with the seven types of Tin in my AE system.

**Comment by Morpheus1101** [comment]
This Mod is all ready installed :D
