### ISSUE TITLE
Bug Report: Cyclic + Colossal Chests Mod Interaction

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#520]
https://youtu.be/Ht453QTyz9c

**Comment by Morpheus1101** [comment]
This issue i have come across myself.  1st of all you removed the core of the chest + 1 other block in your video.  Colossal Chests requires the same structure re-built without the core in a new location an to transplant the core itself which should alleviate the issue your having.  Should it not, please let me know.

**Comment by Morpheus1101** [comment]
Is there any update to this issue as ive been unable to reproduce it?

**Comment by Morpheus1101** [comment]
If this occurs//happens again please feel free to re-comment on this issue.
