### ISSUE TITLE
Bug Report: Fire Pink Pixels

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#521]
![2017-03-26_13 45 34](https://cloud.githubusercontent.com/assets/4635334/24333688/875e492e-122a-11e7-9895-0920e50e6380.png)
These pink pixels across the middle-top of the screen only appear while the fire overlay is active

**Comment by Morpheus1101** [comment]
Were you wearing any armor and if so what type and mod are they from?

**Comment by MasterEric** [comment]
Flux-Infused Helmet/Chest/Leggings + Slime Boots

**Comment by Morpheus1101** [comment]
I tried to reproduce this in my instance but was not able to

**Comment by Aedda** [comment]
Were you using a texture pack?

**Comment by Morpheus1101** [comment]
Closing this issue as myself and others are unable to reproduce.
