### ISSUE TITLE
Mod Request: BetterFPS

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#522]
Mod Name: BetterFPS

Mod Version: 1.3.2

Link To Download: https://minecraft.curseforge.com/projects/betterfps

Dependant Mods: None

If you're not the author of the mod you are requesting, why should this mod be added: This mod provides performance optimizations to users, by optimizing areas that FoamFix does not.

**Comment by Morpheus1101** [comment]
Im surprised this was left out actually.
