### ISSUE TITLE
Bug Report: MASSIVE CLIENT LAG (Embers and Get Ya Tanks Here)

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#523]
https://youtu.be/Qp4vw0SY-B8

**Comment by Morpheus1101** [comment]
Does this occur when using other Fluid Conduits//Pipes as well ?

**Comment by Morpheus1101** [comment]
https://github.com/Darkhax-Minecraft/GYTH/issues/11

**Comment by MasterEric** [comment]
This does not appear to occur with other fluid conduits (it works fine with Fluid Transport Nodes)

**Comment by Morpheus1101** [comment]
https://github.com/RootsTeam/Embers/issues/154

**Comment by Morpheus1101** [comment]
The precise mod responsible is being investigated by both parties at this stage
