### ISSUE TITLE
Mod Request: Chat Bomb

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#525]
**Mod Name**: Chat Bomb

**Mod Version**: 1.1.1

**Link To Download**: https://minecraft.curseforge.com/projects/chat-bomb

**Dependant Mods**: CompatLayer 0.2.2 (same as M.E.T.A.)

**Comment by Aedda** [comment]
As the purpose of the server is to assist in the testing of mods I do not see what assistance we can give for this mod given the simplicity of it. Further, given that its purpose is to cause area damage I cannot see it being generally used on the server accept to interfere with the work others are doing.
