### ISSUE TITLE
Whitelist Request: SpaceWalker189

### ISSUE THREAD

**Issue by SpaceW189** [MinecraftModDevelopment/MMD-Dev-Server#526]
**Minecraft IGN**: SpaceWalker189

**Discord Username**: SpaceW189#3269

**What you do** (*i.e streamer, mod developer, ect.*): I have been playing Minecraft since alpha, modded from like 2012 (Don't quote me on that might me more/less). I am learning to program (mostly just started). I would like to join the community and test out the new mods, I can contribute mostly by finding bugs (and reporting them ofc), but in the future I'd also be on board developing some soft or something fun in that alley :)

**How did you hear about MMD** (*i.e existing user, facebook etc.*): Reddit post under /r/feedthebeast

**Yes I do** agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
What mods have you done and whats the URL to your stream channel?

**Comment by SpaceW189** [comment]
I do wan't to hear if someone dosent approve of me joining, and why :)

**Comment by Morpheus1101** [comment]
Do or Don't ?

**Comment by SpaceW189** [comment]
Do want :)

**Comment by SpaceW189** [comment]
@Morpheus1101 "What mods have you done and whats the URL to your stream channel?" I'm not sure if that question was directed at me, I have a very good knowlage of all the large mods such as Thermal expansion and its addons, AE/AE2 (and the new advanced storage), Botania and BloodMagic, Twilight_Forest, just to name a (very) few. Overall I would say that because I have been playing for _literally_ years I have come to know most mods, except the niche or very new once, that and being completely capable of making bug reports I would belive I could make a good addition for testing and features sugesting.
I'm not the best at selling my self, _as you may tell_, therefor if you have any questions or reasons for not accepting me I would like to clarify where needed/possible :)

**Comment by Morpheus1101** [comment]
A lookup around the modded community shows that despite your saying you've been playing modded since around 2012, you have no fingerprint on the modded scene.  Have you had a previous name?

**Comment by SpaceW189** [comment]
I never considered provinding proof of have played minecraft, and since I have almost always played on local area networks or closed private servers there is as such no 'proof' that I have. I have been a lot more to my self until of late so I don't have anything to present as proof of my experience other then to show it in practice.
I will understand if you will reject my application on this basis, but I hope that you will give me a chance to prove my self in practice :)
Ps I have a Minecraft Forum account form aug'11 but its empty, so wont be much of a show...

**Comment by SpaceW189** [comment]
What about you @Aedda, can you please tell me why? :)

**Comment by Morpheus1101** [comment]
At this stage we are holing off on Whitelist Requests while we prepare for a change over.

**Comment by SpaceW189** [comment]
Okay, I can wait :)

**Comment by Morpheus1101** [comment]
We are now looking to intake users, are you still interested ?

**Comment by SpaceW189** [comment]
I am. However, I will first return from vacation the 5th July :)

**Comment by SpaceW189** [comment]
Yes, I am very much interested  :)
