### ISSUE TITLE
Mod Request: Refined Storage

### ISSUE THREAD

**Issue by MasterEric** [MinecraftModDevelopment/MMD-Dev-Server#527]
Mod Name: Refined Storage

Mod Version: 1.2.25

Link To Download: https://minecraft.curseforge.com/projects/refined-storage

If you're not the author of the mod you are requesting, why should this mod be added: I am interested in experimenting this mod and ensuring its compatibility with other mods.

**Comment by Morpheus1101** [comment]
At this stage we are starting to Focus on 1.11.2 stuff and prepare a new release in a month or so, at this stage we won the grabbing more for 1.10.2 and this mod is all ready included for 1.11.2
