### ISSUE TITLE
Whitelist Request: UpcraftLP

### ISSUE THREAD

**Issue by UpcraftLP** [MinecraftModDevelopment/MMD-Dev-Server#529]
Minecraft IGN:
UpcraftLP

Discord Username:
UpcraftLP#2401

What you do (i.e streamer, mod developer, ect.):
[mod developer](https://minecraft.curseforge.com/members/UpcraftLP/projects)

How did you hear about MMD (i.e existing user, facebook etc.):
been on the MMD discord for quite some time now /shrug

 

- [x] I agree to the terms set forth in the MMD Dev Server's Terms of Play

**Comment by Morpheus1101** [comment]
We are now starting intake of Users, are you still interested?

**Comment by UpcraftLP** [comment]
I am :D
