### ISSUE TITLE
Whitelist Request: Vulturees

### ISSUE THREAD

**Issue by reddvilzz** [MinecraftModDevelopment/MMD-Dev-Server#531]
Minecraft IGN: Vulturees

Discord Username: theBet4

What you do (i.e streamer, mod developer, ect.):
I'm just a player, been around since ftb ultimate and mostly play SSP with small time spent on couple of servers. Currently still playing 1.7.10 with my private modpack and couple of others 1.10.2 modpacks. I'm more of a person who can't stop adding mods that I like in my modpack, in my 1.7.10 pack I have 410 mods working together. That's why I'm very excited when I found this community which offers a server with unlimited expansion of mods and I really like tinkering and trying things out especially new things.

How did you hear about MMD (i.e existing user, facebook etc.):
Feedthebeast reddit and discord

√ I agree to the terms set forth in the MMD Dev Server's Terms of Play

**Comment by Morpheus1101** [comment]
We are now starting intake of Users, are you still interested?

**Comment by reddvilzz** [comment]
Sure thing!

**Comment by reddvilzz** [comment]
Sorry to ask but am I whitelisted now?

**Comment by Morpheus1101** [comment]
Accepted to be in channel, but as yet the server isnt released,  when it is you'll have access to to the server

**Comment by reddvilzz** [comment]
Okay thank you, just making sure the channel is #development? 
Also do you have the rough guess of when will the server is up? I just wanted to start together on a very fresh server and I'm trying to not missed it.

**Comment by Morpheus1101** [comment]
It will bev#dev-server an no exact release yet, but hopefully by end of the week

**Comment by reddvilzz** [comment]
I don't see #dev-server in my MMD discord though? Will it show up when the server is up maybe? Glad to hear that, can't wait.

**Comment by Morpheus1101** [comment]
Im still not seeing you on the MMD Discord

**Comment by reddvilzz** [comment]
I think I might missed something out, but I was in the discord. I PMed you on the discord maybe you could tell me what am I missing?

**Comment by Morpheus1101** [comment]
is Vulturees still your IGN ?

**Comment by reddvilzz** [comment]
Oh yeah I changed recently, my IGN now is theBEt4
