### ISSUE TITLE
Whitelist Request: Prozent

### ISSUE THREAD

**Issue by MrRiegel** [MinecraftModDevelopment/MMD-Dev-Server#532]
Minecraft IGN: Prozent

Discord Username: KidsDontPlay#3550

What you do (i.e streamer, mod developer, ect.): Mod Developer

How did you hear about MMD (i.e existing user, facebook etc.): [reddit](https://www.reddit.com/r/feedthebeast/comments/6as23f/is_there_a_subreddit_for_asking_questions_about/)

- [x] I agree to the terms set forth in the MMD Dev Server's Terms of Play

**Comment by Morpheus1101** [comment]
We are now starting intake of Users, are you still interested?

**Comment by MrRiegel** [comment]
yes
