### ISSUE TITLE
Energy Laser Relay

### ISSUE THREAD

**Issue by Agronox** [MinecraftModDevelopment/MMD-Dev-Server#533]
Every single time I restart the server/client  I have to go through and reconnect every single laser relay in the system. If this is going to be a problem, I would much rather just have physical cables such as the Energy Conduits or the Fluxducts.. Let's face it: wireless is pretty pointless if the practical range of it has a max of 32 blocks.

**Comment by Morpheus1101** [comment]
What pack is this for?

**Comment by Agronox** [comment]
All The Mods 2 

    On Saturday, May 27, 2017 3:40 AM, Morpheus1101 <notifications@github.com> wrote:
 

 What pack is this for?—

**Comment by jriwanek** [comment]
This tracker is for the MMD Dev server pack, closing.
