### ISSUE TITLE
Whitelist request: redBM202

### ISSUE THREAD

**Issue by redBM202** [MinecraftModDevelopment/MMD-Dev-Server#534]
Minecraft IGN:  redBM202

Discord Username: redBM202

What you do (i.e streamer, mod developer, ect.):
Well im not streaming, youtubing or modding.  I have been playing modded minecraft from minecraft version 1.2.3 or 1.2.5. im trying to automate as many things as posible so i usualy find dupebugs, craashes, disconects and stuff like that. 
How did you hear about MMD (i.e existing user, facebook etc.):
WEll i learned about this comunity from samip537
yes I agree- I agree to the terms set forth in the MMD Dev Server's Terms of Play

**Comment by Morpheus1101** [comment]
We are now looking at taking Requests, are you still interested?

**Comment by redBM202** [comment]
Yes. Im interested
