### ISSUE TITLE
Mod Request: JustNuggets

### ISSUE THREAD

**Issue by DeflatedPickle** [MinecraftModDevelopment/MMD-Dev-Server#535]
**Mod Name**: JustNuggets

**Mod Version**: 1.0.5.0

**Link To Download**: https://minecraft.curseforge.com/projects/justnuggets

**Dependant Mods**: None

**Comment by Morpheus1101** [comment]
At this stage we wont be including this mod into the dev-server pack as we feel there is nothing to use what is added or requiring much in the way of testing.
