### ISSUE TITLE
Mod Request: Iron Apples

### ISSUE THREAD

**Issue by XavierDD1st** [MinecraftModDevelopment/MMD-Dev-Server#536]
Mod Name:
Iron Appls
Mod Version:
1.1
Link To Download:
https://minecraft.curseforge.com/projects/iron-apples
Dependant Mods:
No mods are needed.

**Comment by Morpheus1101** [comment]
The 1st Round of intakes has been done, however intakes will happen frequently for both ModRequests and Whitelist Requests.

**Comment by Morpheus1101** [comment]
We are looking to add in new mods etc in a few days or so.

**Comment by Morpheus1101** [comment]
At this time thi shas been rejected. We dont feel that it adds any game content or requires testing.
