### ISSUE TITLE
White-List Request: XavierDD

### ISSUE THREAD

**Issue by XavierDD1st** [MinecraftModDevelopment/MMD-Dev-Server#537]
Minecraft IGN:
XavierDD

Discord Username:
XavierDD1st#8549

What you do (i.e streamer, mod developer, ect.):
[mod developer](https://minecraft.curseforge.com/members/XavierDD1st/projects)

How did you hear about MMD (i.e existing user, facebook etc.):
I don't honestly remember, but I think I heard about it from Ewy

■ I agree to the terms set forth in the MMD Dev Server's Terms of Play

**Comment by Morpheus1101** [comment]
You are all ready idling in the dev-server channel, when the pack is released you will see an announcement in the channel on how to grab the pack.
