### ISSUE TITLE
Whitelist Request: blupilot

### ISSUE THREAD

**Issue by blupilot** [MinecraftModDevelopment/MMD-Dev-Server#538]
Minecraft IGN: blupilot

Discord Username: blupilot#0191

What you do (i.e streamer, mod developer, ect.): Mod Developer

How did you hear about MMD (i.e existing user, facebook etc.): Morpheus1101#8985 on discord

I agree to the terms set forth in the MMD Dev Server's Terms of Play

**Comment by Morpheus1101** [comment]
Please join our Discord server as i dont see you listed in there currently.

**Comment by Samuel-Harbord** [comment]
He is there, I see him often. He is under "Blu [Menu Books]".
