### ISSUE TITLE
Whitelist Request: PaleoCrafter

### ISSUE THREAD

**Issue by PaleoCrafter** [MinecraftModDevelopment/MMD-Dev-Server#539]
**Minecraft IGN**: PaleoCrafter

**Discord Username**: PaleoCrafter#1259

**What you do**: Mod developer

**How did you hear about MMD**: MMD Discord

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
You have been added to the dev-server channel, when the pack is released you will see an announcement in the channel on how to grab the pack.
