### ISSUE TITLE
Whitelist Request: Lemons

### ISSUE THREAD

**Issue by Lemonszz** [MinecraftModDevelopment/MMD-Dev-Server#540]
Minecraft IGN: Lemons

Discord Username: Lemon#8046

What you do (i.e streamer, mod developer, ect.):
Mod Developer - Anima Mundi, Simple Teleporters, Autoplant

How did you hear about MMD (i.e existing user, facebook etc.):
I think it saw a like on /r/FeedTheBeast a few months ago.

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
You have been added to the dev-server channel, when the pack is released you will see an announcement in the channel on how to grab the pack.
