### ISSUE TITLE
Whitelist Request: Samuel_H

### ISSUE THREAD

**Issue by Samuel-Harbord** [MinecraftModDevelopment/MMD-Dev-Server#541]
**Minecraft IGN**: Samuel_H

**Discord Username**: FlashfireEX

**What you do** (*i.e streamer, mod developer, ect.*): Mod Developer

**How did you hear about MMD** (*i.e existing user, facebook etc.*): Google

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
Please join our MMD Discord Server
