### ISSUE TITLE
Whitelist Request: xDJ_

### ISSUE THREAD

**Issue by xDJx** [MinecraftModDevelopment/MMD-Dev-Server#542]
**Minecraft IGN:** xDJ_
**Discord Username:** DJ#4623
**What you do (i.e streamer, mod developer, ect.):** Aspiring mod developer, Spigot plugin developer
**How did you hear about MMD (i.e existing user, facebook etc.):** I was looking for a Minecraft plugin development Discord online, but I found something even better :)

**I agree to the terms set forth in the MMD Dev Server's Terms of Play:** I do indeed

**Comment by Morpheus1101** [comment]
The 1st Round of intakes has been done, however intakes will happen frequently for both ModRequests and Whitelist Requests.

**Comment by Morpheus1101** [comment]
Please join our Discord Channel

**Comment by Morpheus1101** [comment]
You have been added.
