### ISSUE TITLE
Mod Request : Make the Nether Great Again

### ISSUE THREAD

**Issue by Joshwoo70** [MinecraftModDevelopment/MMD-Dev-Server#543]
Mod Name:
Make The Nether Great Again!
Mod Version:
1.1
Link To Download:
https://minecraft.curseforge.com/projects/mtnga
Dependant Mods:
No Dependancies

**Comment by Joshwoo70** [comment]
Tgis is purely your choice if you want to add it. i wont force to really accept the mod :P

**Comment by blupilot** [comment]
Looks like MTNGA is 1.12 and the MMD Dev Server is gonna be 1.11

**Comment by Morpheus1101** [comment]
Dev server will be running 1.11.2

**Comment by Joshwoo70** [comment]
coukd pirt it to 1.11.2 quickly

**Comment by Morpheus1101** [comment]
The 1st Round of intakes has been done, however intakes will happen frequently for both ModRequests and Whitelist Requests.

**Comment by Morpheus1101** [comment]
Thankyou for applying to have your mod tested.  However we feel that this particular mod dosent offer much that really requires much in the way of testing.  We wish you the best of luck in your future modding endevours.
