### ISSUE TITLE
Whitelist request: xalcon

### ISSUE THREAD

**Issue by Xalcon** [MinecraftModDevelopment/MMD-Dev-Server#545]
# MMD Dev Server Whitelist Template
**Minecraft IGN**: xalcon
**Discord Username**: xalcon#7230
**What you do** (*i.e streamer, mod developer, ect.*): Mod Developer of **[Torchmaster](https://minecraft.curseforge.com/projects/torchmaster)** and **[Energy Converters](https://minecraft.curseforge.com/projects/energy-converters?gameCategorySlug=mc-mods&projectID=254818)**
**How did you hear about MMD** (*i.e existing user, facebook etc.*): MMD Discord
- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
The 1st Round of intakes has been done, however intakes will happen frequently for both ModRequests and Whitelist Requests.

**Comment by Morpheus1101** [comment]
You have been added :)
