### ISSUE TITLE
Whitelist request: AEnterprise

### ISSUE THREAD

**Issue by AEnterprise** [MinecraftModDevelopment/MMD-Dev-Server#546]
**Minecraft IGN**: AEnterprise

**Discord Username**: AEnterprise#4693

**What you do** (*i.e streamer, mod developer, ect.*): Buildcraft developer, BCA (discontinued)

**How did you hear about MMD** (*i.e existing user, facebook etc.*): discord

- [X] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
You Have Been Added.
