### ISSUE TITLE
Mod Request: Villager Market

### ISSUE THREAD

**Issue by faceofcat** [MinecraftModDevelopment/MMD-Dev-Server#547]
Mod Name: Villager Market

Mod Version: 1.12-HF2

Link To Download: https://minecraft.curseforge.com/projects/villager-market

Dependant Mods: n/a

**Comment by Morpheus1101** [comment]
The 1st Round of intakes has been done, however intakes will happen frequently for both ModRequests and Whitelist Requests.

**Comment by Morpheus1101** [comment]
we will look at adding in more mods in a few days or so.

**Comment by Morpheus1101** [comment]
This has now been added into v1.5
