### ISSUE TITLE
Mod Request: Simply Conveyors & More

### ISSUE THREAD

**Issue by Zundrel** [MinecraftModDevelopment/MMD-Dev-Server#549]
Mod Name: Simply Conveyors & More

Mod Version: 4.0.3

Link To Download: https://minecraft.curseforge.com/projects/simply-conveyors-more

Dependant Mods: N/A

**Comment by Morpheus1101** [comment]
The 1st Round of intakes has been done, however intakes will happen frequently for both ModRequests and Whitelist Requests.

**Comment by Morpheus1101** [comment]
This has now been added into v1.5
