### ISSUE TITLE
Whitelist Request: Zundrel

### ISSUE THREAD

**Issue by Zundrel** [MinecraftModDevelopment/MMD-Dev-Server#550]
**Minecraft IGN**: Zundrel

**Discord Username**: Zundrel#7856

**What you do** (*i.e streamer, mod developer, ect.*): Mod Developer of [Simply Conveyors](https://minecraft.curseforge.com/projects/simply-conveyors-more), [Never Enough Currency](https://minecraft.curseforge.com/projects/never-enough-currency), and multiple other mods.

**How did you hear about MMD** (*i.e existing user, facebook etc.*): Reddit

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
The 1st Round of intakes has been done, however intakes will happen frequently for both ModRequests and Whitelist Requests.

**Comment by Morpheus1101** [comment]
You have been added to the Discord Channel and whitelisted :)
