### ISSUE TITLE
Mod Request: Dissolution

### ISSUE THREAD

**Issue by Pyrofab** [MinecraftModDevelopment/MMD-Dev-Server#551]
Mod Name: Dissolution

Mod Version: 0.4.2

Link To Download: https://minecraft.curseforge.com/projects/dissolution

Dependant Mods: N/A

**Comment by Morpheus1101** [comment]
While i am very intrigued by this mod, im not sure how well itd go with testing with the other mods we have on the server, so for myself im voting no.

**Comment by Pyrofab** [comment]
Actually, I was expecting this issue, so the version I gave you has the [WoWLikeRespawn config option](https://github.com/Pyrofab/Dissolution/wiki/Configuration#wowlikerespawn) on by default. (Meaning the mod has very little impact on normal gameplay). If you still don't want to include it however, I will understand :)

**Comment by Morpheus1101** [comment]
It was more the fact that with the /back command users can get straight back to their death point as well as items saved via grave mod, but we can only but give things a test run an see what happens

**Comment by Pyrofab** [comment]
Ah yes I understand. Even if this part can be entirely avoided, I would still like to get feedback on the other parts of the mod (though I'm still developping them)

**Comment by Morpheus1101** [comment]
The 1st Round of intakes has been done, however intakes will happen frequently for both ModRequests and Whitelist Requests.

**Comment by Morpheus1101** [comment]
We are looking to add more things in a few days or so, but since we are running with keepinv on by default rather than use a graves mod, i was wondering how this would impact upon your mod and its functionality?

**Comment by Pyrofab** [comment]
I did not really consider keepInventory so I think the bodies will force
the stuff transfer. I will probably correct that today. Otherwise,
everything should work fine.

Le 17 juil. 2017 00:20, "Morpheus1101" <notifications@github.com> a écrit :

We are looking to add more things in a few days or so, but since we are
running with keepinv on by default rather than use a graves mod, i was
wondering how this would impact upon your mod and its functionality?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MinecraftModDevelopment/MMD-Dev-Server/issues/551#issuecomment-315641870>,
or mute the thread

**Comment by Pyrofab** [comment]
I released the version 0.4.2 for Dissolution, which fixes a lot of bugs and takes into account keepInventory.

**Comment by Morpheus1101** [comment]
This has now been added into v1.5

**Comment by Morpheus1101** [comment]
I have had to remove your mod for now as it crashes myself and i dare say any other player that Dies now since we added this mod in.

Crash Console Message @ https://puu.sh/wOcX5/e712a21afe.txt

**Comment by Pyrofab** [comment]
Oh... I'm really sorry for the inconvenience. I will investigate.

**Comment by Pyrofab** [comment]
Looks like this bug only occurs on dedicated servers, which is why it slipped past my testing. The fix is already uploaded and under review.

**Comment by Morpheus1101** [comment]
okies, i shall test it out now and let you know.

**Comment by Morpheus1101** [comment]
Only possibly issue i can forsee is if a user dies in lava, with them not being able to collect or place blocks, this would make recovering there body uniquely difficult without others assistance

**Comment by Pyrofab** [comment]
If he dies in lava, his corpse will burn anyway. Without a corpse being available, they will have to either use one of the resurrection blocks (mercurius waystone / sepulture), go to the X:0 Z:0 coordinates of the world or find a mercury lake. If you have an idea that would be a bit more interesting / less annoying, feel free to suggest, that's why I opened this request in the first place :)

**Comment by Morpheus1101** [comment]
The test i did my corpse remained in lava an did not burn

**Comment by Pyrofab** [comment]
Ah, right, I did implement corpse invulnerability... Well then, that just adds an option I guess. Either another user helps them securing their corpse or they use one of the aforementioned other options.

**Comment by Morpheus1101** [comment]
This is most excellent, thanks for the quick fix an added understanding of ya mod, its appreciated.

**Comment by Morpheus1101** [comment]
While i like what you have and are doing with this mod, i dont feel as its suited for testing on the dev server at this time, however, should this change in the future, i will be sure to include it and give you a heads up.  I wish you the best with the future of this mod.

**Comment by Pyrofab** [comment]
I definitely understand your decision. Actually the reason I did not come play on the server is similar, I wanted to add more playable content first. Will it be possible for me to reopen this issue in the future, when I feel like it is interesting enough ?

**Comment by Morpheus1101** [comment]
Most certainly :)
