### ISSUE TITLE
Mod Request: Toast Control

### ISSUE THREAD

**Issue by blupilot** [MinecraftModDevelopment/MMD-Dev-Server#553]
- **Mod Name:** Toast Control
- **Mod Version:** 1.1.1
- **Link To Download:** https://minecraft.curseforge.com/projects/toast-control
- **Dependant Mods:** None
- **If you're not the author of the mod you are requesting, why should this mod be added:** So that players aren't sitting through a tutorial every time they download the pack.

**Comment by Morpheus1101** [comment]
This would be fantastic, ive had a couple mention about this all ready

**Comment by Morpheus1101** [comment]
This has now been added into v1.5
