### ISSUE TITLE
Whitelist Request: ADeathlyTouch

### ISSUE THREAD

**Issue by ADeathlyTouch** [MinecraftModDevelopment/MMD-Dev-Server#554]
Minecraft IGN: A_Deathly_Touch

Discord Username: ADeathlyTouch#7752

What you do (i.e streamer, mod developer, ect.): I am a mod developer, modpack developer, [Twitch](https://www.twitch.tv/a_deathly_touch) streamer, and [YouTuber](https://www.youtube.com/channel/UCPbW25z576ZKY9KlPbt8flg). Here are some of the mods I develop, [Tesla Essentials](https://minecraft.curseforge.com/projects/tesla-essentials), [Avionics](https://minecraft.curseforge.com/projects/avionics), [Purely Colors](https://minecraft.curseforge.com/projects/purely-colors), and [Spatial Systems](https://minecraft.curseforge.com/projects/spatial-systems). I only have one modpack public currently, you can find it [here](https://minecraft.curseforge.com/projects/exploring-tech), the other two are still in development.

How did you hear about MMD (i.e existing user, facebook etc.): I was previously in the Dev server. I originally heard about it from being a part of the MMD Discord server.

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
You've been added
