### ISSUE TITLE
Mod Request: Simple Corn

### ISSUE THREAD

**Issue by cleverpanda** [MinecraftModDevelopment/MMD-Dev-Server#555]
Mod Name: Simple Corn
Mod Version: 1.12-2.3.2
Link To Download:https://minecraft.curseforge.com/projects/simple-corn/files?filter-game-version=1738749986%3a628

Dependant Mods: none.

**Comment by cleverpanda** [comment]
Would like to test various auto farming setups from mods in multiplayer

**Comment by Morpheus1101** [comment]
This has now been added into v1.5
