### ISSUE TITLE
Mod Request: AdvanceBase

### ISSUE THREAD

**Issue by jarodsstuff** [MinecraftModDevelopment/MMD-Dev-Server#558]
#MMD Dev Server Mod Request Template

**Mod Name**: AdvanceBase

**Mod Version**: 2.0.1 for Minecraft 1.12

**Link To Download**: https://minecraft.curseforge.com/projects/advancebase/files/2453769

**Dependant Mods**: None

**If you're not the author of the mod you are requesting, why should this mod be added**: N/A, I am the author.

**If the mod is not currently hosted anywhere, please give a brief decription of the mod**: N/A

**Comment by Morpheus1101** [comment]
Done in v1.7
