### ISSUE TITLE
Mod Request: Vigilant Eureka

### ISSUE THREAD

**Issue by tkdberger** [MinecraftModDevelopment/MMD-Dev-Server#561]
# MMD Dev Server Mod Request Template

**Mod Name**: Vigilant Eureka

**Mod Version**: 0.0.0-beta

**Link To Download**: https://minecraft.curseforge.com/projects/vigilant-eureka/

**Dependant Mods**: none

**Comment by tkdberger** [comment]
(reccomend using whatever the latest is at time of addition, the builds tend to be stable enough)

**Comment by Morpheus1101** [comment]
Done

**Comment by Morpheus1101** [comment]
Mod Crashes on load of SMP Server: Log @ https://puu.sh/wZkGM/b093317f0f.txt

**Comment by tkdberger** [comment]
I (think I) fixed the nasty crashbug. Here's a new jar to test. https://minecraft.curseforge.com/projects/vigilant-eureka/files/2459432

**Comment by Morpheus1101** [comment]
Added in v1.8 Coming out very shortly
