### ISSUE TITLE
Mod Request: TheBOMPlugin

### ISSUE THREAD

**Issue by osum4est** [MinecraftModDevelopment/MMD-Dev-Server#570]
Mod Name: TheBOMPlugin
Mod Version: 0.1.2 (Or use latest)
Link To Download: https://minecraft.curseforge.com/projects/thebomplugin/files
Dependant Mods: JEI
If you're not the author of the mod you are requesting, why should this mod be added: Am author
If the mod is not currently hosted anywhere, please give a brief decription of the mod: On curse

**Comment by Morpheus1101** [comment]
i'll be checking mods in about 12hrs  to do an Update

**Comment by Morpheus1101** [comment]
This has been added in v1.9
