### ISSUE TITLE
Player Whitelist Request: osum4est

### ISSUE THREAD

**Issue by osum4est** [MinecraftModDevelopment/MMD-Dev-Server#571]
Minecraft IGN: osum4est
Discord Username: osum4est
What you do (i.e streamer, mod developer, ect.): mod dev of TheBOMPlugin
How did you hear about MMD (i.e existing user, facebook etc.): FTB Subreddit
 I agree to the terms set forth in the MMD Dev Server's Terms of Play: true

**Comment by Morpheus1101** [comment]
You have been added to the Dev-Server and Dev Discord Channel.
