### ISSUE TITLE
Mod Request: Chococraft

### ISSUE THREAD

**Issue by Xalcon** [MinecraftModDevelopment/MMD-Dev-Server#573]
**Mod Name:** Chococraft
**Mod Version:** latest
**Link To Download:** https://build.xalcon.net/job/Chococraft%203%20-%20MC1.12/
**Github:** https://github.com/Xalcon/ChocoCraft3
**Dependant Mods:** *None*
**Why should this mod be added:** I am the author :)
**If the mod is not currently hosted anywhere, please give a brief decription of the mod:**
The mod is available on [curseforge](https://minecraft.curseforge.com/projects/chococraft) up to Minecraft 1.8. On my Jenkins you can find the my port (from scratch D:) version for MC 1.12.

Chococraft is about taming, training and breeding chocobos - a big bird-like animal from the Final Fantasy universe.
At the current state, the Mod has the following features:
* World spawning of chocobos
* WorldGen for Gysahl Green (food for chocobos, used for taming)
* Basic vanilla style breeding (missing recipe for the breeding item, will be added later today)
* Taming and riding of chocobos (~~missing recipe for saddle, will be added later today~~ *added*)

There are configuration options for worldgen but I hope the defaults are alright, there is no retrogen though. (Thats what Testservers are for, right? 😄 )

There is a bunch of stuff planned, including an elaborate breeding and training system including specialized traits and abilities.

**Comment by Xalcon** [comment]
> Note: I know jenkins currently doesnt have up to date builds do to a bug in the build setup. I'll fix that later today :)

**Comment by Morpheus1101** [comment]
The latest code on your github dosent build and the last build successful on your Jenkins is Number 5 .. is this build accceptable to be used?

**Comment by Xalcon** [comment]
I've updated the mod. It now includes crafting recipes for all stuff that might be needed in a survival setting, including a loottable for the chocobo.
The latest version, as of now, is 0.2.0.16 and is available via jenkins :)

**Comment by Morpheus1101** [comment]
i'll be checking mods in about 12hrs  to do an Update

**Comment by Xalcon** [comment]
Thanks for the headsup. I've deployed a new version (0.2.1.27) which fixes an error with chocobos eating saddles. Its available on curseforge and my jenkins.

**Comment by Morpheus1101** [comment]
This has been added in v1.9
