### ISSUE TITLE
Mod Request: Realistic Cobwebs Mod

### ISSUE THREAD

**Issue by UpcraftLP** [MinecraftModDevelopment/MMD-Dev-Server#574]
Mod Name: Realistic Cobwebs mod

Mod Version: 1.12-1.0.2

Link To Download: https://minecraft.curseforge.com/projects/realistic-cobwebs-mod/files/2455124

Dependencies: None.

**Comment by Morpheus1101** [comment]
At this stage your request has been denied, we thankyou for applying to have your mod on the server.
