### ISSUE TITLE
Player Whitelist Request: TwilightGamerpro

### ISSUE THREAD

**Issue by TwilightGamerPro** [MinecraftModDevelopment/MMD-Dev-Server#577]
Minecraft IGN, Cutishu_Kawaii
What you do: Mod Developer- Still developing it before i release it
How did you hear about MMD: was scrolling thru the modpack list on the twitch client and came a crossed it
I agree to the terms set forth in the MMD Dev Server's Terms of Play: Yes # # #

**Comment by Morpheus1101** [comment]
What is your Discord Username?
