### ISSUE TITLE
Mod Request: Actually Additions

### ISSUE THREAD

**Issue by Zaweri** [MinecraftModDevelopment/MMD-Dev-Server#58]
Mod name: 
-
Actually Additions

Mod Version: 
-
r60 or bleeding edge build from GitHub/Jenkins

Link To Download:
-
https://minecraft.curseforge.com/projects/actually-additions

If you're not the author of the mod you are requesting, why should this mod be added: 
-
Actually Additions displays item IDs, and I like the mod. It is also a mod that is in the MMD channels. It is very useful in gameplay too.

**Comment by EmoKiba** [comment]
i hope this one gets approved ive recently started playing with this mod and its wonderful
