### ISSUE TITLE
Player Whitelist Request: Shukaro

### ISSUE THREAD

**Issue by AKA-Syenite** [MinecraftModDevelopment/MMD-Dev-Server#581]
**Minecraft IGN**: Shukaro

**Discord Username**: Syenite

**What you do** (*i.e streamer, mod developer, ect.*): Developer of [Artifice](https://github.com/Shukaro/Artifice), [Nodal Mechanics](https://github.com/Shukaro/Nodal-Mechanics), [Warp Theory](https://github.com/Shukaro/WarpTheory), [Ender Ore](https://github.com/Shukaro/EnderOre), and [Questlog](https://github.com/Shukaro/Questlog)

**How did you hear about MMD** (*i.e existing user, facebook etc.*): /r/feedthebeast

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
You have been added to the Dev-Server Channel
