### ISSUE TITLE
Mod Request: ARKCraft_Guns Mod Minecraft 1.12.1

### ISSUE THREAD

**Issue by BubbleTrouble14** [MinecraftModDevelopment/MMD-Dev-Server#582]
Mod Name: ARKCraft_Guns
Mod Version: 1.0 alpha
Github repo: https://github.com/BubbleTrouble14/ARKCraft_Guns
Download Link: https://1drv.ms/u/s!AmT9tCEFxKFIgZ0p8M8ATe6mg21S8Q 

Dependant Mods: none

Note: Its may still have a few bugs, as this is the first version of this mod.

Its a mod which aims to add 3d gun models to the world of minecraft, inspired by ark survival evolved.

**Comment by Morpheus1101** [comment]
The Server ha snow changed its purpose to become a Dev-Server for Modpacks.  We thankyou for your application though.
