### ISSUE TITLE
Whitelist Request: Kashike

### ISSUE THREAD

**Issue by kashike** [MinecraftModDevelopment/MMD-Dev-Server#583]
**Minecraft IGN**: `Kashike`

**Discord Username**: `kashike#8590`

**What you do**: mod developer - SpongeForge

**How did you hear about MMD**: existing user

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by Morpheus1101** [comment]
You've Been Added to the Dev-Server Discord Channel
