### ISSUE TITLE
Mod Request: InstantUnify & PlayerStorage

### ISSUE THREAD

**Issue by MrRiegel** [MinecraftModDevelopment/MMD-Dev-Server#588]
Mod Name: InstantUnify

Mod Version: 1.0.5

Link To Download: https://minecraft.curseforge.com/projects/instantunify/files/2488976

Dependant Mods: -

If you're not the author of the mod you are requesting, why should this mod be added: I am the author

-------------------------------------------------------------------------------------------------------

Mod Name: PlayerStorage

Mod Version: 1.0.3

Link To Download: https://minecraft.curseforge.com/projects/playerstorage/files/2488978

Dependant Mods: [LimeLib](https://minecraft.curseforge.com/projects/limelib/files/2484808) 

If you're not the author of the mod you are requesting, why should this mod be added: I am the author

**Comment by Morpheus1101** [comment]
The Server ha snow changed its purpose to become a Dev-Server for Modpacks.  We thankyou for your application though.
