### ISSUE TITLE
Whitelist request: YOYOK9 

### ISSUE THREAD

**Issue by YOYOK9** [MinecraftModDevelopment/MMD-Dev-Server#590]
Minecraft IGN: YOYOK9 

Discord Username: YOYOK9 

What you do (i.e streamer, mod developer, ect.): I am the current modpack owner of the pack businesselite-plus on curse. Before that I was a beta tester for the same pack. I have also tested some mods for  TheRealp455w0rd. 

How did you hear about MMD (i.e existing user, facebook etc.): found out about it while sitting in passwords discord channel. 

 I agree to the terms set forth in the MMD Dev Server's Terms of Play

**Comment by Morpheus1101** [comment]
The Server ha snow changed its purpose to become a Dev-Server for Modpacks.  We thankyou for your application though.
