### ISSUE TITLE
Whitelist Request: Yeyvo

### ISSUE THREAD

**Issue by Yeyvo** [MinecraftModDevelopment/MMD-Dev-Server#591]
Minecraft IGN: Yeyvo

Discord Username: Yeyvo #8024

What you do (i.e streamer, mod developer, ect.): Mod Developer  ( Arthania (this is the current server i work on it) / Paladium (an old server i worked on it))

How did you hear about MMD (i.e existing user, facebook etc.): From some other devolopper 

I Yeyvo listed above as IGN acknowledge and agree to the terms set forth in the Terms of Play, as stated in the new TERMS.md file and my GITLAB username is Yeyvo

**Comment by Morpheus1101** [comment]
The Server ha snow changed its purpose to become a Dev-Server for Modpacks.  We thankyou for your application though.
