### ISSUE TITLE
MMD Dev Server Whitelist

### ISSUE THREAD

**Issue by Geometrically** [MinecraftModDevelopment/MMD-Dev-Server#593]
Minecraft IGN: Geometrically

Discord Username: Geometrically#3996

What you do (i.e streamer, mod developer, ect.): A make mods.

How did you hear about MMD (i.e existing user, facebook etc.): A friend referred me.

 I agree to the terms set forth in the MMD Dev Server's Terms of Play: Yes.

**Comment by jriwanek** [comment]
Appologies, the Dev server has been shut down, so is no longer accepting whitelist requests
