### ISSUE TITLE
Whitelist Request

### ISSUE THREAD

**Issue by T145** [MinecraftModDevelopment/MMD-Dev-Server#595]
**Minecraft IGN**: T145

**Discord Username**: T145

**What you do** (*i.e streamer, mod developer, ect.*): Mod Developer

**How did you hear about MMD** (*i.e existing user, facebook etc.*): Just happened to find the Discord server.

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

**Comment by jriwanek** [comment]
Appologies, the Dev server has been shut down, so is no longer accepting whitelist requests

**Comment by T145** [comment]
Then why is the repo still up? xd

**Comment by jriwanek** [comment]
https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/README.md

See the big text at the top.....
