### ISSUE TITLE
Whitelist request

### ISSUE THREAD

**Issue by nullifiedcat** [MinecraftModDevelopment/MMD-Dev-Server#597]
# MMD Dev Server Whitelist Template

**Minecraft IGN**: nullifiedcat

**Discord Username**: nullifiedcat#1063

**What you do** (*i.e streamer, mod developer, ect.*): Beginner mod developer

**How did you hear about MMD** (*i.e existing user, facebook etc.*): Google

- [✓] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

- [✓] I have read the Readme file at: [Readme](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/README.md)

**Comment by knoxhack** [comment]
Accepted:
Invite to Modpack repository sent

**Comment by knoxhack** [comment]
You now have access to the server's discord channel
