### ISSUE TITLE
Server Whitelist Application

### ISSUE THREAD

**Issue by oaster2000** [MinecraftModDevelopment/MMD-Dev-Server#599]
**Minecraft IGN**: oaster2000

**Discord Username**:oaster2000#7636

**What you do** (*i.e streamer, mod developer, ect.*): developer, currently unreleased but working on it.

**How did you hear about MMD** (*i.e existing user, facebook etc.*): existing user

- [X] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

- [X] I have read the Readme file at: [Readme](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/README.md)

**Comment by knoxhack** [comment]
Accepted:
Invite to Modpack repository sent

**Comment by knoxhack** [comment]
You now have access to the server's discord channel
