### ISSUE TITLE
Whitelist Request: Darkhax

### ISSUE THREAD

**Issue by darkhax** [MinecraftModDevelopment/MMD-Dev-Server#6]
Minecraft IGN: Darkhax
Discord Username: Darkhax
What you do (i.e streamer, mod developer, ect.): Too many things

**Comment by darkhax** [comment]
Apparently I have not been accepted. @jriwanek asked me to post a request here.

**Comment by knoxhack** [comment]
#blameTheCodedOne for closing it and not adding you xD
