### ISSUE TITLE
Whitelist Request - FlintnSteel

### ISSUE THREAD

**Issue by flintnsteel** [MinecraftModDevelopment/MMD-Dev-Server#60]
Minecraft IGN: FlintnSteel_

Discord Username: flintnsteel (just call me Flint)

What you do (i.e streamer, mod developer, ect.): I have a small Youtube Channel and i am also starting to stream regularly. I know mods pretty well, but i also know what to google if I have problems.

YouTube : https://www.youtube.com/user/theflintnsteelgaming

**Comment by p455w0rd** [comment]
We're going to hold off on whitelisting anyone who doesnt have a mod on the server to give devs the opportunity to apply. We will accept more non-dev apps at a later date.

**Comment by p455w0rd** [comment]
@are you still interested in being whitelisted?

**Comment by flintnsteel** [comment]
Yes, I am still interested.

**Comment by Morpheus1101** [comment]
Where you added to the whitelist?

**Comment by p455w0rd** [comment]
please join our discord server

**Comment by Morpheus1101** [comment]
Welcome aboard :D
