### ISSUE TITLE
Whitelist Application

### ISSUE THREAD

**Issue by Selim042** [MinecraftModDevelopment/MMD-Dev-Server#600]
# MMD Dev Server Whitelist Template

**Minecraft IGN**: Selim_042

**Discord Username**: Selim#0062

**What you do** (*i.e streamer, mod developer, ect.*): Mod developer

**How did you hear about MMD** (*i.e existing user, facebook etc.*): MMD Discord Server

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

- [x] I have read the Readme file at: [Readme](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/README.md)

**Comment by knoxhack** [comment]
Accepted:
Invite to Modpack repository send

**Comment by knoxhack** [comment]
You now have access to the server's discord channel

**Comment by Selim042** [comment]
Thanks!
