### ISSUE TITLE
Whitelist Application

### ISSUE THREAD

**Issue by Buuz135** [MinecraftModDevelopment/MMD-Dev-Server#601]
# MMD Dev Server Whitelist Template

**Minecraft IGN**: Buuz135

**Discord Username**: Buuz135#0135

**What you do** (*i.e streamer, mod developer, ect.*): Mod developer

**How did you hear about MMD** (*i.e existing user, facebook etc.*): Existing User

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

- [x] I have read the Readme file at: [Readme](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/README.md)

**Comment by knoxhack** [comment]
Invite to Modpack repository sent

**Comment by knoxhack** [comment]
You now have access to the server's discord channel

**Comment by Buuz135** [comment]
Thanks!
