### ISSUE TITLE
Whitelist Request

### ISSUE THREAD

**Issue by ThePuzzlemaker** [MinecraftModDevelopment/MMD-Dev-Server#611]
**Minecraft IGN**: QuantumIO

**Discord Username**: QuantumIO

**What you do** (*i.e streamer, mod developer, etc.*): Mod developer, YouTuber, game developer.

**How did you hear about MMD** (*i.e existing user, facebook etc.*): existing user

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

- [x] I have read the Readme file at: [Readme](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/README.md)

**Comment by jriwanek** [comment]
The dev server is currently closed.
