### ISSUE TITLE
Whitelist Request

### ISSUE THREAD

**Issue by XenoMustache** [MinecraftModDevelopment/MMD-Dev-Server#612]
**Minecraft IGN**: XenoMustache

**Discord Username**: Nyx#8278

**What you do** (*i.e streamer, mod developer, ect.*): Mod Dev, Game Dev

**How did you hear about MMD** (*i.e existing user, facebook etc.*): Another user

- [x] I agree to the terms set forth in the MMD Dev Server's [Terms of Play](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/TERMS.md)

- [x] I have read the Readme file at: [Readme](https://github.com/MinecraftModDevelopment/MMD-Dev-Server/blob/master/README.md)

**Comment by jriwanek** [comment]
The dev server is currently closed.
