### ISSUE TITLE
Mod Request: CTweaks

### ISSUE THREAD

**Issue by darkhax** [MinecraftModDevelopment/MMD-Dev-Server#62]
Mod Name: Custom Tweaks
Mod Version: 1.0.0.0
Link To Download: [curse](https://minecraft.curseforge.com/projects/custom-tweaks/files/2327432)
Dependent Mods: N/A

This mod is a new one from me. It is intended to serve as a suit of utilities to allow basic customization of a minecraft instance. It allows for basic edits to the main menu, as well as automatically adding entries to the server list without replacing the server list file. I would recommend [this](https://gist.github.com/darkhax/acac50b355f5fe34ff0ea67695486c3d) config file. 
![image](https://cloud.githubusercontent.com/assets/2250798/18154121/5bc1abf2-6fbf-11e6-9a96-fa52d2609b90.png)

**Comment by knoxhack** [comment]
Is it compatible with Stabiliser? https://github.com/MinecraftModDevelopment/Stabiliser

**Comment by TheCodedOne** [comment]
@knoxhack no it isnt, Stabiliser completely replaces all the Gui's like main menu, singleplayer, multiplayer, options. it would need specific support for it to do it.
