### ISSUE TITLE
Texture bug: waila  and evil craft

### ISSUE THREAD

**Issue by battery3996** [MinecraftModDevelopment/MMD-Dev-Server#64]
When looking at an evilcraft item i get a missing texture in Waila 
![2016-09-01_04 29 35](https://cloud.githubusercontent.com/assets/10549249/18160789/fc9c7f9c-6ffc-11e6-96b9-7c2782cffda8.png)

**Comment by Zaweri** [comment]
This is fairly old, been there since 1.9.4

**Comment by rubensworks** [comment]
@battery3996 Could you report that here as well?: https://github.com/CyclopsMC/EvilCraft
This is the first time I hear of this issue...

**Comment by TheCodedOne** [comment]
its a common bug even some of vanilla things does it, its been this way since 1.7
