### ISSUE TITLE
Bug Issue: Modularity

### ISSUE THREAD

**Issue by battery3996** [MinecraftModDevelopment/MMD-Dev-Server#66]
What happened was i placed the pulverizer down and i accidentally placed a torch on it. Went to break torch block complete disappears. it didnt drop. just poof gone.

![modularity bug](https://cloud.githubusercontent.com/assets/10549249/18167169/143f6f7c-701d-11e6-92fa-0354723a85ef.gif)

**Comment by knoxhack** [comment]
#rip

**Comment by TheCodedOne** [comment]
just dont look!
