### ISSUE TITLE
Mod Request: ArdentCraft

### ISSUE THREAD

**Issue by CurtisLee1994** [MinecraftModDevelopment/MMD-Dev-Server#67]
Mod name:

ArdentCraft

Mod Version:

1.10.2-2.0.6

Link To Download:

https://minecraft.curseforge.com/projects/ardentcraft

If you're not the author of the mod you are requesting, why should this mod be added:

I am the author, And i would like this to be added for a few reason! 
1: I want to prove to you guys it can be done with Mcreator ;) 
2: It adds so much playabilty to minecraft and also works with other mods! 
3: I havnt had it tested in a server enviroment so you would be helping me out! 
4: With all you guys been devs etc, I would love feedback from the players on the server :)

**Comment by p455w0rd** [comment]
We have discussed this in detail and our decision didn't come easy. Basically it comes down to two things.
1) The mod is created with MCreator and therefore doesn't need testing. It works great OOB and will not produce conflict/bugs.
2) The mod should add an enticing element to give incentive to other players that should make them wish to use/test your mod. We feel this would not happen as it just doesn't add a unique gameplay element.

We thank you for taking time to submit your mod and if you feel that our reasons aren't valid, you are welcome to to submit an appeal in the form of a reply to this response.
