### ISSUE TITLE
Mod Request: Novacula Acuta

### ISSUE THREAD

**Issue by KitsuneAlex** [MinecraftModDevelopment/MMD-Dev-Server#77]
Mod Name: Novacula Acuta
[Description: This mod is based around little additions and tools. At the moment it adds one main block, the grindstone wich allows the player to sharpen tools and make them more efficient without using the enchantment table. The player can even use diamonds or emeralds as modifiers. Also this mod adds Item Cases wich can be used as Tool Racks or for decoration. There are more features to come !]

Mod Version: 0.0.3

Link To Download: https://www.dropbox.com/s/6g7s6hzmsluzzyw/NovaculaAcuta-%5B1.10.2%5D-0.0.3.jar?dl=1

Dependant Mods: none

**Comment by knoxhack** [comment]
Looking forward to try it out

**Comment by KitsuneAlex** [comment]
Thank you very much :) also i am already working on some new features but Modularity is my priority at the moment >.<
