### ISSUE TITLE
modularity.charger server crash

### ISSUE THREAD

**Issue by knoxhack** [MinecraftModDevelopment/MMD-Dev-Server#78]
https://gist.github.com/knoxhack/6ecc38c91623ab84cb5379c64d80869c

**Comment by knoxhack** [comment]
You should be able to re-add Tesla Arsenal after removing the changer you tried to use to charge Tesla Arsenal tools

**Comment by KitsuneAlex** [comment]
Thanks, i'll look into it right now !

**Comment by knoxhack** [comment]
I tested charging the Tesla Arsenal Tools with the Actually Additions charger and it worked, something might be wrong with your charger
