### ISSUE TITLE
Mod Request: Tomb Many Graves

### ISSUE THREAD

**Issue by EmoKiba** [MinecraftModDevelopment/MMD-Dev-Server#80]
Name: Tomb Many Graves
Version: 2.1.8
Download: https://minecraft.curseforge.com/projects/tomb-many-graves/files/2318067
Reason: I would prefer this Gravestone mod over Gravestone because its cleaner on server it doesnt store the graves as a tile entity so its easy on fps and its death inventory list is deleted by dropping it and the gravestones can be locked if they are needed to be and only someone on the tmg friendslist can open it

**Comment by TheCodedOne** [comment]
but... why...
