### ISSUE TITLE
Mod Request: PerfectSpawn

### ISSUE THREAD

**Issue by PIxelforgeentertainment** [MinecraftModDevelopment/MMD-Dev-Server#82]
Name: Perfect spawn
Version: PerfectSpawn-MC1.10.2-1.4.jar also it is the 1.10.2 version
Download: https://minecraft.curseforge.com/projects/perfect-spawn
Reason: It is going to spawn every time at the same spot. other than ftb util's only if you do /ftb spawn.

**Comment by p455w0rd** [comment]
simple small...IMO /setworldspawn should do what this mod does...has my approval
