### ISSUE TITLE
Mod Request: Modular Routers

### ISSUE THREAD

**Issue by desht** [MinecraftModDevelopment/MMD-Dev-Server#89]
**Mod Name**: Modular Routers

**Mod Version**: 1.0.2

**Link To Download**: https://minecraft.curseforge.com/projects/modular-routers/files/2328402

**Dependant Mods**: WAILA, TheOneProbe, Guide-API (all optional dependencies)

**If you're not the author of the mod you are requesting, why should this mod be added**:

**If the mod is not currently hosted anywhere, please give a brief decription of the mod**:

**Comment by desht** [comment]
Note: I am the mod author.

**Comment by desht** [comment]
Just updated the requested version to 1.0.2, which fixes a startup crash when Waila isn't installed.

**Comment by knoxhack** [comment]
Did I forget to add this one?

**Comment by p455w0rd** [comment]
yes :P

**Comment by knoxhack** [comment]
Oops
