### ISSUE TITLE
Mod request: Better Builder's Wands

### ISSUE THREAD

**Issue by EmoKiba** [MinecraftModDevelopment/MMD-Dev-Server#9]
Name: Better Builder's Wands
Version: 0.6.5
Download: https://minecraft.curseforge.com/projects/better-builders-wands/files/2310296

**Comment by knoxhack** [comment]
I don't see why not, It helps building our bases

**Comment by p455w0rd** [comment]
yeah..was actually just contacting Portablejim myself :)
